import type { Question } from './types.js'

/** Fresh SV bank — includes lightning (easy/fast) and double (trickier) seeds. */
export const MODE_SV_QUESTIONS: Question[] = [
  // Lightning — easy & snappy
  {
    id: 'msv-l1',
    category: 'Allmänt',
    text: 'Hur många dagar har en vanlig vecka?',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'msv-l2',
    category: 'Allmänt',
    text: 'Vilken färg får du om du blandar blått och gult?',
    options: ['Lila', 'Grön', 'Orange', 'Brun'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'msv-l3',
    category: 'Popkultur',
    text: 'Vad heter Harry Potters bästa vän som är en rödlätt kille?',
    options: ['Draco', 'Neville', 'Ron', 'Hagrid'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'msv-l4',
    category: 'Mat & Dryck',
    text: 'Vad heter den italienska rätten med deg, tomatsås och ost?',
    options: ['Pasta', 'Pizza', 'Risotto', 'Lasagne'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'msv-l5',
    category: 'Sverige',
    text: 'Vilken färg har den svenska flaggan utöver blått?',
    options: ['Rött', 'Gult', 'Vitt', 'Grönt'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'msv-l6',
    category: 'Film & TV',
    text: 'Vilket djur är Nemo i Hitta Nemo?',
    options: ['Haj', 'Bläckfisk', 'Clownfisk', 'Delfin'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'msv-l7',
    category: 'Musik',
    text: 'Hur många strängar har en vanlig gitarr?',
    options: ['4', '5', '6', '8'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'msv-l8',
    category: 'Allmänt',
    text: 'Vad är motsatsen till “varm”?',
    options: ['Torr', 'Kall', 'Mjuk', 'Hög'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'msv-l9',
    category: 'Sport',
    text: 'Hur många spelare har ett fotbollslag på planen?',
    options: ['9', '10', '11', '12'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'msv-l10',
    category: 'Popkultur',
    text: 'Vad heter snögubben i Frost?',
    options: ['Sven', 'Olof', 'Kristoffer', 'Hans'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'msv-l11',
    category: 'Mat & Dryck',
    text: 'Vilken frukt är huvudråvara i apelsinjuice?',
    options: ['Citron', 'Apelsin', 'Äpple', 'Päron'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'msv-l12',
    category: 'Allmänt',
    text: 'Hur många hjul har en vanlig bil?',
    options: ['2', '3', '4', '6'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'msv-l13',
    category: 'Geografi',
    text: 'Vilket land ligger närmast Sverige: Norge eller Spanien?',
    options: ['Spanien', 'Norge', 'Lika långt', 'Ingen av dem'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'msv-l14',
    category: 'Musik',
    text: 'Vilket band sjöng “Dancing Queen”?',
    options: ['Beatles', 'ABBA', 'Queen', 'Ace of Base'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'msv-l15',
    category: 'Allmänt',
    text: 'Vad heter den första månaden på året?',
    options: ['Mars', 'December', 'Januari', 'Juni'],
    correctIndex: 2,
    mode: 'lightning',
  },

  // Double — trickier / worth more
  {
    id: 'msv-d1',
    category: 'Historia',
    text: 'Vilket år blev Sverige medlem i EU?',
    options: ['1989', '1995', '2001', '2004'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'msv-d2',
    category: 'Vetenskap',
    text: 'Vilket grundämne har kemiska symbolen Au?',
    options: ['Silver', 'Guld', 'Aluminium', 'Argon'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'msv-d3',
    category: 'Geografi',
    text: 'Vilken är världens näst största kontinent till ytan?',
    options: ['Afrika', 'Nordamerika', 'Europa', 'Antarktis'],
    correctIndex: 0,
    mode: 'double',
  },
  {
    id: 'msv-d4',
    category: 'Film & TV',
    text: 'Vem regisserade filmen Inception?',
    options: ['Steven Spielberg', 'Christopher Nolan', 'Ridley Scott', 'James Cameron'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'msv-d5',
    category: 'Litteratur',
    text: 'Vem skrev “Bröderna Lejonhjärta”?',
    options: ['Astrid Lindgren', 'Selma Lagerlöf', 'Maria Gripe', 'Tove Jansson'],
    correctIndex: 0,
    mode: 'double',
  },
  {
    id: 'msv-d6',
    category: 'Sport',
    text: 'Hur många spelare har ett ishockeylag samtidigt på isen (per lag, utan målvakt räknas ofta 5+1)?',
    options: ['4 utespelare + MV', '5 utespelare + MV', '6 utespelare + MV', '3 utespelare + MV'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'msv-d7',
    category: 'Musik',
    text: 'Vilket instrument är Yo-Yo Ma mest känd för?',
    options: ['Violin', 'Cello', 'Piano', 'Flöjt'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'msv-d8',
    category: 'Teknik',
    text: 'Vad står HTTP för (ungefär)?',
    options: [
      'HyperText Transfer Protocol',
      'High Tech Transfer Program',
      'Host Transfer Text Path',
      'Hyper Tool Transport Packet',
    ],
    correctIndex: 0,
    mode: 'double',
  },
  {
    id: 'msv-d9',
    category: 'Sverige',
    text: 'Vilken svensk kung kallades “Lejonet från Norden” i propagandan under 1600-talet?',
    options: ['Karl XII', 'Gustav II Adolf', 'Gustav Vasa', 'Erik XIV'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'msv-d10',
    category: 'Natur',
    text: 'Vilket djur lägger störst ägg relativt sin kroppsstorlek bland fåglar (ofta nämnt)?',
    options: ['Örn', 'Kiwifågel', 'Struts', 'Pingvin'],
    correctIndex: 1,
    mode: 'double',
  },

  // Extra normal SV to expand the bank
  {
    id: 'msv-n1',
    category: 'Geografi',
    text: 'Vilken flod rinner genom London?',
    options: ['Seine', 'Themsen', 'Donau', 'Rhen'],
    correctIndex: 1,
  },
  {
    id: 'msv-n2',
    category: 'Geografi',
    text: 'Vilket land har huvudstaden Ottawa?',
    options: ['Australien', 'Kanada', 'Nya Zeeland', 'Irland'],
    correctIndex: 1,
  },
  {
    id: 'msv-n3',
    category: 'Historia',
    text: 'Vilket år föll Berlinmuren?',
    options: ['1985', '1989', '1991', '1995'],
    correctIndex: 1,
  },
  {
    id: 'msv-n4',
    category: 'Historia',
    text: 'Vem var Sveriges statsminister längst under 1900-talet?',
    options: ['Olof Palme', 'Tage Erlander', 'Göran Persson', 'Per Albin Hansson'],
    correctIndex: 1,
  },
  {
    id: 'msv-n5',
    category: 'Sport',
    text: 'I vilken sport används en shuttlecock?',
    options: ['Tennis', 'Badminton', 'Squash', 'Bordtennis'],
    correctIndex: 1,
  },
  {
    id: 'msv-n6',
    category: 'Sport',
    text: 'Hur många perioder har en ishockeymatch normalt?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
  },
  {
    id: 'msv-n7',
    category: 'Film & TV',
    text: 'Vilken skådespelare spelar Iron Man i MCU?',
    options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
    correctIndex: 1,
  },
  {
    id: 'msv-n8',
    category: 'Film & TV',
    text: 'Vad heter den gula familjen i The Simpsons efternamn?',
    options: ['Flanders', 'Simpson', 'Burns', 'Smith'],
    correctIndex: 1,
  },
  {
    id: 'msv-n9',
    category: 'Musik',
    text: 'Vilket instrument spelar en trummis främst?',
    options: ['Bas', 'Trummor', 'Keyboard', 'Saxofon'],
    correctIndex: 1,
  },
  {
    id: 'msv-n10',
    category: 'Musik',
    text: 'Vilken artist släppte albumet “1989”?',
    options: ['Adele', 'Taylor Swift', 'Billie Eilish', 'Rihanna'],
    correctIndex: 1,
  },
  {
    id: 'msv-n11',
    category: 'Vetenskap',
    text: 'Vad kallas den närmaste stjärnan till jorden (förutom solen, ofta)?',
    options: ['Sirius', 'Proxima Centauri', 'Betelgeuse', 'Polaris'],
    correctIndex: 1,
  },
  {
    id: 'msv-n12',
    category: 'Vetenskap',
    text: 'Hur många ben har en vuxen människa ungefär?',
    options: ['106', '206', '306', '406'],
    correctIndex: 1,
  },
  {
    id: 'msv-n13',
    category: 'Mat & Dryck',
    text: 'Vilket land kommer sushi ursprungligen från?',
    options: ['Kina', 'Japan', 'Korea', 'Thailand'],
    correctIndex: 1,
  },
  {
    id: 'msv-n14',
    category: 'Mat & Dryck',
    text: 'Vad är guacamole huvudsakligen gjord på?',
    options: ['Tomat', 'Avokado', 'Gurka', 'Paprika'],
    correctIndex: 1,
  },
  {
    id: 'msv-n15',
    category: 'Teknik',
    text: 'Vad heter Apples röstassistent?',
    options: ['Alexa', 'Siri', 'Cortana', 'Google'],
    correctIndex: 1,
  },
  {
    id: 'msv-n16',
    category: 'Teknik',
    text: 'Vad betyder “www” i en webbadress?',
    options: ['World Wide Web', 'Web World Wide', 'Wide Web World', 'Wireless Web Wave'],
    correctIndex: 0,
  },
  {
    id: 'msv-n17',
    category: 'Natur',
    text: 'Vilket är det snabbaste landlevande djuret?',
    options: ['Lejon', 'Gepard', 'Antilop', 'Häst'],
    correctIndex: 1,
  },
  {
    id: 'msv-n18',
    category: 'Natur',
    text: 'Vad kallas en grupp lejon?',
    options: ['Flock', 'Stim', 'Pride', 'Svärm'],
    correctIndex: 2,
  },
  {
    id: 'msv-n19',
    category: 'Sverige',
    text: 'Vilken är Sveriges största sjö?',
    options: ['Vättern', 'Vänern', 'Mälaren', 'Hjälmaren'],
    correctIndex: 1,
  },
  {
    id: 'msv-n20',
    category: 'Sverige',
    text: 'I vilken stad ligger Turning Torso?',
    options: ['Göteborg', 'Stockholm', 'Malmö', 'Helsingborg'],
    correctIndex: 2,
  },
  {
    id: 'msv-n21',
    category: 'Popkultur',
    text: 'Vad heter spelvärlden i Minecraft (övervärlden)?',
    options: ['Nether', 'Overworld', 'End', 'Realm'],
    correctIndex: 1,
  },
  {
    id: 'msv-n22',
    category: 'Popkultur',
    text: 'Vilken app ägs av Meta och handlar om korta videor?',
    options: ['TikTok', 'Instagram Reels', 'Snapchat', 'YouTube Shorts'],
    correctIndex: 1,
  },
  {
    id: 'msv-n23',
    category: 'Kultur',
    text: 'Vad kallas den svenska högtiden med majstång?',
    options: ['Valborg', 'Midsommar', 'Lucia', 'Nyår'],
    correctIndex: 1,
  },
  {
    id: 'msv-n24',
    category: 'Kultur',
    text: 'Vilken färg har tomtens klassiska dräkt oftast i modern popkultur?',
    options: ['Blå', 'Grön', 'Röd', 'Vit'],
    correctIndex: 2,
  },
  {
    id: 'msv-n25',
    category: 'Allmänt',
    text: 'Hur många sekunder finns i en minut?',
    options: ['30', '60', '90', '100'],
    correctIndex: 1,
  },
  {
    id: 'msv-n26',
    category: 'Allmänt',
    text: 'Vad heter motsatsen till “norr”?',
    options: ['Öst', 'Väst', 'Syd', 'Nordost'],
    correctIndex: 2,
  },
  {
    id: 'msv-n27',
    category: 'Geografi',
    text: 'Vilket hav ligger mellan Sverige och Finland?',
    options: ['Nordsjön', 'Östersjön', 'Atlanten', 'Ishavet'],
    correctIndex: 1,
  },
  {
    id: 'msv-n28',
    category: 'Historia',
    text: 'Vilket land byggde den kinesiska muren?',
    options: ['Japan', 'Kina', 'Mongoliet', 'Korea'],
    correctIndex: 1,
  },
  {
    id: 'msv-n29',
    category: 'Film & TV',
    text: 'Vad heter skurken i de flesta klassiska Batman-filmer som ler mycket?',
    options: ['Pingvinen', 'Joker', 'Bane', 'Riddler'],
    correctIndex: 1,
  },
  {
    id: 'msv-n30',
    category: 'Mat & Dryck',
    text: 'Vilken dryck görs av rostade kaffebönor?',
    options: ['Te', 'Kaffe', 'Kakao', 'Cola'],
    correctIndex: 1,
  },
  {
    id: 'msv-n31',
    category: 'Vetenskap',
    text: 'Vilken planet är närmast solen?',
    options: ['Venus', 'Merkurius', 'Mars', 'Jorden'],
    correctIndex: 1,
  },
  {
    id: 'msv-n32',
    category: 'Sport',
    text: 'I tennis, vad heter poängen 0?',
    options: ['Nil', 'Love', 'Zero', 'Blank'],
    correctIndex: 1,
  },
  {
    id: 'msv-n33',
    category: 'Teknik',
    text: 'Vad heter Googles mobiloperativsystem?',
    options: ['iOS', 'Android', 'Windows', 'Linux'],
    correctIndex: 1,
  },
  {
    id: 'msv-n34',
    category: 'Natur',
    text: 'Vad andas fiskar med?',
    options: ['Lungor', 'Gälar', 'Hud', 'Näsa'],
    correctIndex: 1,
  },
  {
    id: 'msv-n35',
    category: 'Litteratur',
    text: 'Vem skrev “Pippi Långstrump”?',
    options: ['Astrid Lindgren', 'Elsa Beskow', 'Tove Jansson', 'Maria Gripe'],
    correctIndex: 0,
  },
  {
    id: 'msv-n36',
    category: 'Popkultur',
    text: 'Vad heter plattformen där man “tweetar”?',
    options: ['Facebook', 'X (Twitter)', 'LinkedIn', 'Reddit'],
    correctIndex: 1,
  },
  {
    id: 'msv-n37',
    category: 'Sverige',
    text: 'Vilken är Sveriges sydligaste landskap?',
    options: ['Halland', 'Skåne', 'Blekinge', 'Småland'],
    correctIndex: 1,
  },
  {
    id: 'msv-n38',
    category: 'Musik',
    text: 'Vad kallas en sång utan instrument?',
    options: ['Remix', 'A cappella', 'Beatbox', 'Cover'],
    correctIndex: 1,
  },
  {
    id: 'msv-n39',
    category: 'Allmänt',
    text: 'Hur många bokstäver har det svenska alfabetet?',
    options: ['26', '28', '29', '30'],
    correctIndex: 2,
  },
  {
    id: 'msv-n40',
    category: 'Geografi',
    text: 'Vilken är världens största ö?',
    options: ['Madagaskar', 'Grönland', 'Island', 'Borneo'],
    correctIndex: 1,
  },
]

/** Fresh EN bank — lightning + double seeds + normals. */
export const MODE_EN_QUESTIONS: Question[] = [
  {
    id: 'men-l1',
    category: 'General',
    text: 'How many days are in a week?',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'men-l2',
    category: 'General',
    text: 'What color do you get mixing blue and yellow?',
    options: ['Purple', 'Green', 'Orange', 'Brown'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'men-l3',
    category: 'Pop Culture',
    text: 'Who is Harry Potter’s red-haired best friend?',
    options: ['Draco', 'Neville', 'Ron', 'Hagrid'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'men-l4',
    category: 'Food',
    text: 'Italian dish with dough, tomato sauce and cheese?',
    options: ['Pasta', 'Pizza', 'Risotto', 'Lasagna'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'men-l5',
    category: 'Movies & TV',
    text: 'What kind of fish is Nemo?',
    options: ['Shark', 'Octopus', 'Clownfish', 'Dolphin'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'men-l6',
    category: 'Music',
    text: 'How many strings does a standard guitar have?',
    options: ['4', '5', '6', '8'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'men-l7',
    category: 'Sports',
    text: 'How many players does a soccer team field?',
    options: ['9', '10', '11', '12'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'men-l8',
    category: 'Pop Culture',
    text: 'What is the snowman’s name in Frozen?',
    options: ['Sven', 'Olaf', 'Kristoff', 'Hans'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'men-l9',
    category: 'General',
    text: 'How many wheels does a typical car have?',
    options: ['2', '3', '4', '6'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'men-l10',
    category: 'Music',
    text: 'Which band sang “Dancing Queen”?',
    options: ['The Beatles', 'ABBA', 'Queen', 'Ace of Base'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'men-l11',
    category: 'Food',
    text: 'Orange juice is mainly made from which fruit?',
    options: ['Lemon', 'Orange', 'Apple', 'Pear'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'men-l12',
    category: 'General',
    text: 'What is the first month of the year?',
    options: ['March', 'December', 'January', 'June'],
    correctIndex: 2,
    mode: 'lightning',
  },
  {
    id: 'men-l13',
    category: 'Geography',
    text: 'Which is closer to Sweden: Norway or Spain?',
    options: ['Spain', 'Norway', 'Same', 'Neither'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'men-l14',
    category: 'General',
    text: 'What is the opposite of “hot”?',
    options: ['Dry', 'Cold', 'Soft', 'High'],
    correctIndex: 1,
    mode: 'lightning',
  },
  {
    id: 'men-l15',
    category: 'Culture',
    text: 'What color is Santa’s classic modern suit?',
    options: ['Blue', 'Green', 'Red', 'White'],
    correctIndex: 2,
    mode: 'lightning',
  },

  {
    id: 'men-d1',
    category: 'History',
    text: 'In which year did the Berlin Wall fall?',
    options: ['1985', '1989', '1991', '1995'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'men-d2',
    category: 'Science',
    text: 'What is the chemical symbol for gold?',
    options: ['Ag', 'Au', 'Al', 'Ar'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'men-d3',
    category: 'Geography',
    text: 'What is the world’s second-largest continent by area?',
    options: ['Africa', 'North America', 'Europe', 'Antarctica'],
    correctIndex: 0,
    mode: 'double',
  },
  {
    id: 'men-d4',
    category: 'Movies & TV',
    text: 'Who directed Inception?',
    options: ['Steven Spielberg', 'Christopher Nolan', 'Ridley Scott', 'James Cameron'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'men-d5',
    category: 'Literature',
    text: 'Who wrote “1984”?',
    options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'Jules Verne'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'men-d6',
    category: 'Tech',
    text: 'What does HTTP stand for?',
    options: [
      'HyperText Transfer Protocol',
      'High Tech Transfer Program',
      'Host Transfer Text Path',
      'Hyper Tool Transport Packet',
    ],
    correctIndex: 0,
    mode: 'double',
  },
  {
    id: 'men-d7',
    category: 'Music',
    text: 'Yo-Yo Ma is famous for which instrument?',
    options: ['Violin', 'Cello', 'Piano', 'Flute'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'men-d8',
    category: 'Science',
    text: 'Which planet is closest to the Sun?',
    options: ['Venus', 'Mercury', 'Mars', 'Earth'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'men-d9',
    category: 'History',
    text: 'Who was the first President of the United States?',
    options: ['Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John Adams'],
    correctIndex: 1,
    mode: 'double',
  },
  {
    id: 'men-d10',
    category: 'Nature',
    text: 'Which bird is often said to lay the largest egg relative to body size?',
    options: ['Eagle', 'Kiwi', 'Ostrich', 'Penguin'],
    correctIndex: 1,
    mode: 'double',
  },

  {
    id: 'men-n1',
    category: 'Geography',
    text: 'Which river runs through London?',
    options: ['Seine', 'Thames', 'Danube', 'Rhine'],
    correctIndex: 1,
  },
  {
    id: 'men-n2',
    category: 'Geography',
    text: 'What is the capital of Canada?',
    options: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'],
    correctIndex: 1,
  },
  {
    id: 'men-n3',
    category: 'Sports',
    text: 'Which sport uses a shuttlecock?',
    options: ['Tennis', 'Badminton', 'Squash', 'Table tennis'],
    correctIndex: 1,
  },
  {
    id: 'men-n4',
    category: 'Sports',
    text: 'How many periods are in a standard ice hockey game?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
  },
  {
    id: 'men-n5',
    category: 'Movies & TV',
    text: 'Who plays Iron Man in the MCU?',
    options: ['Chris Evans', 'Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo'],
    correctIndex: 1,
  },
  {
    id: 'men-n6',
    category: 'Movies & TV',
    text: 'What is the yellow family’s last name in The Simpsons?',
    options: ['Flanders', 'Simpson', 'Burns', 'Smith'],
    correctIndex: 1,
  },
  {
    id: 'men-n7',
    category: 'Music',
    text: 'Who released the album “1989”?',
    options: ['Adele', 'Taylor Swift', 'Billie Eilish', 'Rihanna'],
    correctIndex: 1,
  },
  {
    id: 'men-n8',
    category: 'Science',
    text: 'About how many bones does an adult human have?',
    options: ['106', '206', '306', '406'],
    correctIndex: 1,
  },
  {
    id: 'men-n9',
    category: 'Food',
    text: 'Where does sushi originally come from?',
    options: ['China', 'Japan', 'Korea', 'Thailand'],
    correctIndex: 1,
  },
  {
    id: 'men-n10',
    category: 'Food',
    text: 'Guacamole is mainly made from which fruit?',
    options: ['Tomato', 'Avocado', 'Cucumber', 'Pepper'],
    correctIndex: 1,
  },
  {
    id: 'men-n11',
    category: 'Tech',
    text: 'What is Apple’s voice assistant called?',
    options: ['Alexa', 'Siri', 'Cortana', 'Google'],
    correctIndex: 1,
  },
  {
    id: 'men-n12',
    category: 'Tech',
    text: 'What does “www” stand for?',
    options: ['World Wide Web', 'Web World Wide', 'Wide Web World', 'Wireless Web Wave'],
    correctIndex: 0,
  },
  {
    id: 'men-n13',
    category: 'Nature',
    text: 'What is the fastest land animal?',
    options: ['Lion', 'Cheetah', 'Antelope', 'Horse'],
    correctIndex: 1,
  },
  {
    id: 'men-n14',
    category: 'Nature',
    text: 'What is a group of lions called?',
    options: ['Herd', 'School', 'Pride', 'Swarm'],
    correctIndex: 2,
  },
  {
    id: 'men-n15',
    category: 'Pop Culture',
    text: 'What is the main world in Minecraft called?',
    options: ['Nether', 'Overworld', 'End', 'Realm'],
    correctIndex: 1,
  },
  {
    id: 'men-n16',
    category: 'General',
    text: 'How many seconds are in a minute?',
    options: ['30', '60', '90', '100'],
    correctIndex: 1,
  },
  {
    id: 'men-n17',
    category: 'General',
    text: 'What is the opposite of “north”?',
    options: ['East', 'West', 'South', 'Northeast'],
    correctIndex: 2,
  },
  {
    id: 'men-n18',
    category: 'Geography',
    text: 'What is the largest island in the world?',
    options: ['Madagascar', 'Greenland', 'Iceland', 'Borneo'],
    correctIndex: 1,
  },
  {
    id: 'men-n19',
    category: 'History',
    text: 'Which country built the Great Wall?',
    options: ['Japan', 'China', 'Mongolia', 'Korea'],
    correctIndex: 1,
  },
  {
    id: 'men-n20',
    category: 'Movies & TV',
    text: 'Which Batman villain is known for a wide grin?',
    options: ['Penguin', 'Joker', 'Bane', 'Riddler'],
    correctIndex: 1,
  },
  {
    id: 'men-n21',
    category: 'Food',
    text: 'Which drink is made from roasted coffee beans?',
    options: ['Tea', 'Coffee', 'Cocoa', 'Cola'],
    correctIndex: 1,
  },
  {
    id: 'men-n22',
    category: 'Sports',
    text: 'In tennis, what is a score of zero called?',
    options: ['Nil', 'Love', 'Zero', 'Blank'],
    correctIndex: 1,
  },
  {
    id: 'men-n23',
    category: 'Tech',
    text: 'What is Google’s mobile OS called?',
    options: ['iOS', 'Android', 'Windows', 'Linux'],
    correctIndex: 1,
  },
  {
    id: 'men-n24',
    category: 'Nature',
    text: 'What do fish primarily breathe with?',
    options: ['Lungs', 'Gills', 'Skin', 'Nose'],
    correctIndex: 1,
  },
  {
    id: 'men-n25',
    category: 'Literature',
    text: 'Who wrote “Pride and Prejudice”?',
    options: ['Charlotte Brontë', 'Jane Austen', 'Emily Dickinson', 'Mary Shelley'],
    correctIndex: 1,
  },
  {
    id: 'men-n26',
    category: 'Pop Culture',
    text: 'Which platform is known for “tweets”?',
    options: ['Facebook', 'X (Twitter)', 'LinkedIn', 'Reddit'],
    correctIndex: 1,
  },
  {
    id: 'men-n27',
    category: 'Music',
    text: 'Singing without instruments is called…',
    options: ['Remix', 'A cappella', 'Beatbox', 'Cover'],
    correctIndex: 1,
  },
  {
    id: 'men-n28',
    category: 'Geography',
    text: 'Which ocean is the largest?',
    options: ['Atlantic', 'Indian', 'Pacific', 'Arctic'],
    correctIndex: 2,
  },
  {
    id: 'men-n29',
    category: 'Science',
    text: 'What gas do plants absorb for photosynthesis?',
    options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Helium'],
    correctIndex: 1,
  },
  {
    id: 'men-n30',
    category: 'Culture',
    text: 'Which holiday features a maypole in Sweden?',
    options: ['Christmas', 'Midsummer', 'Easter', 'Halloween'],
    correctIndex: 1,
  },
  {
    id: 'men-n31',
    category: 'Sports',
    text: 'How many points is a touchdown worth in American football (without kick)?',
    options: ['3', '6', '7', '8'],
    correctIndex: 1,
  },
  {
    id: 'men-n32',
    category: 'General',
    text: 'How many letters are in the English alphabet?',
    options: ['24', '25', '26', '27'],
    correctIndex: 2,
  },
  {
    id: 'men-n33',
    category: 'Geography',
    text: 'What is the capital of Japan?',
    options: ['Osaka', 'Tokyo', 'Kyoto', 'Nagoya'],
    correctIndex: 1,
  },
  {
    id: 'men-n34',
    category: 'Music',
    text: 'Which Beatle was known as the “quiet one”?',
    options: ['John', 'Paul', 'George', 'Ringo'],
    correctIndex: 2,
  },
  {
    id: 'men-n35',
    category: 'Science',
    text: 'Water freezes at what temperature Celsius?',
    options: ['-10', '0', '10', '32'],
    correctIndex: 1,
  },
  {
    id: 'men-n36',
    category: 'Food',
    text: 'Which cheese is traditionally used on pizza margherita?',
    options: ['Cheddar', 'Mozzarella', 'Gouda', 'Feta'],
    correctIndex: 1,
  },
  {
    id: 'men-n37',
    category: 'History',
    text: 'The Titanic sank in which year?',
    options: ['1905', '1912', '1918', '1923'],
    correctIndex: 1,
  },
  {
    id: 'men-n38',
    category: 'Nature',
    text: 'What do bees collect to make honey?',
    options: ['Pollen only', 'Nectar', 'Sap', 'Dew'],
    correctIndex: 1,
  },
  {
    id: 'men-n39',
    category: 'Tech',
    text: 'What company makes the PlayStation?',
    options: ['Microsoft', 'Sony', 'Nintendo', 'Sega'],
    correctIndex: 1,
  },
  {
    id: 'men-n40',
    category: 'Pop Culture',
    text: 'In Star Wars, what color is Luke’s first lightsaber?',
    options: ['Red', 'Blue', 'Green', 'Purple'],
    correctIndex: 1,
  },
]
