import type { Question } from './types.js'

export const BULK_EN_QUESTIONS: Question[] = [
  {
    id: "bulk-en-47",
    category: "Geography",
    text: "What is the capital of Morocco?",
    options: ["Madrid","Rabat","Moscow","Amsterdam"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-110",
    category: "Science",
    text: "What is the chemical symbol for Hydrogen?",
    options: ["F","H","Li","Cl"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-757",
    category: "General",
    text: "What number is the Roman numeral IV?",
    options: ["4","7","9","50"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-795",
    category: "General",
    text: "Which month comes after October?",
    options: ["November","October","July","April"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-724",
    category: "General",
    text: "How many meters are in 37 km?",
    options: ["37100","37000","3700","370"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-119",
    category: "Science",
    text: "What element has the symbol O?",
    options: ["Oxygen","Aluminum","Manganese","Cobalt"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-106",
    category: "Geography",
    text: "Which country has the capital Abu Dhabi?",
    options: ["United Arab Emirates","Bulgaria","Greece","Belgium"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-145",
    category: "Science",
    text: "What element has the symbol Cu?",
    options: ["Copper","Titanium","Chlorine","Magnesium"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-691",
    category: "Sports",
    text: "What is primarily used in soccer?",
    options: ["puck","shuttlecock","disk","ball"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-95",
    category: "Geography",
    text: "Which country has the capital Hanoi?",
    options: ["Indonesia","Australia","Vietnam","Iran"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-665",
    category: "Nature",
    text: "Where does a penguin typically live?",
    options: ["Antarctica","forest","savanna","ocean"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-142",
    category: "Science",
    text: "What is the chemical symbol for Calcium?",
    options: ["Li","Hg","Ca","Co"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-779",
    category: "General",
    text: "Which month comes after February?",
    options: ["February","April","January","March"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-65",
    category: "Geography",
    text: "Which country has the capital Warsaw?",
    options: ["Poland","Mexico","Belgium","Ukraine"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-656",
    category: "History",
    text: "In which year: First iPhone released?",
    options: ["1991","1977","2007","1963"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-35",
    category: "Geography",
    text: "What is the capital of Colombia?",
    options: ["Bogotá","Abu Dhabi","Cairo","Prague"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-115",
    category: "Science",
    text: "What element has the symbol C?",
    options: ["Silver","Carbon","Sodium","Iodine"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-174",
    category: "Science",
    text: "Which planet is #1 from the Sun?",
    options: ["Uranus","Jupiter","Mercury","Mars"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-26",
    category: "Geography",
    text: "What is the capital of Croatia?",
    options: ["Warsaw","Santiago","Buenos Aires","Zagreb"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-32",
    category: "Geography",
    text: "What is the capital of Argentina?",
    options: ["Beijing","Buenos Aires","Pretoria","Zagreb"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-729",
    category: "General",
    text: "How many meters are in 47 km?",
    options: ["4700","47000","470","48000"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-41",
    category: "Geography",
    text: "What is the capital of Vietnam?",
    options: ["Rabat","Hanoi","Tokyo","Copenhagen"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-135",
    category: "Science",
    text: "What element has the symbol S?",
    options: ["Sulfur","Calcium","Cobalt","Manganese"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-664",
    category: "Nature",
    text: "What is a baby penguin called?",
    options: ["eaglet","pup","chick","owlet"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-150",
    category: "Science",
    text: "What is the chemical symbol for Silver?",
    options: ["Pt","Cr","Ag","Cu"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-773",
    category: "General",
    text: "What number is the Roman numeral L?",
    options: ["6","3","100","50"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-786",
    category: "General",
    text: "How many days does June have (common year)?",
    options: ["29","31","30","28"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-73",
    category: "Geography",
    text: "Which country has the capital Athens?",
    options: ["Turkey","France","South Korea","Greece"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-180",
    category: "Science",
    text: "Which planet is #4 from the Sun?",
    options: ["Venus","Jupiter","Saturn","Mars"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-144",
    category: "Science",
    text: "What is the chemical symbol for Iron?",
    options: ["Fe","H","Zn","C"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-643",
    category: "History",
    text: "In which year: Moon landing?",
    options: ["1977","1969","1963","2001"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-49",
    category: "Geography",
    text: "What is the capital of Kenya?",
    options: ["Nairobi","Pretoria","Paris","Kyiv"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-698",
    category: "Sports",
    text: "How many players per team are typically on the field in volleyball?",
    options: ["7","12","6","10"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-797",
    category: "General",
    text: "Which month comes after November?",
    options: ["August","December","July","March"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-737",
    category: "General",
    text: "How many minutes are in 13 hours?",
    options: ["840","780","1300","810"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-663",
    category: "Nature",
    text: "Where does a elephant typically live?",
    options: ["savanna","swamp","Antarctica","forest"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-713",
    category: "General",
    text: "How many meters are in 15 km?",
    options: ["150","14900","15000","1500"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-126",
    category: "Science",
    text: "What is the chemical symbol for Sodium?",
    options: ["Cu","Na","F","Ag"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-134",
    category: "Science",
    text: "What is the chemical symbol for Phosphorus?",
    options: ["P","Mn","Li","Cu"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-778",
    category: "General",
    text: "How many days does February have (common year)?",
    options: ["29","30","28","31"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-673",
    category: "Nature",
    text: "Where does a bear typically live?",
    options: ["savanna","forest","China","savanna"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-681",
    category: "Nature",
    text: "Where does a owl typically live?",
    options: ["forest","mountains","savanna","savanna"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-111",
    category: "Science",
    text: "What element has the symbol He?",
    options: ["Helium","Phosphorus","Hydrogen","Potassium"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-825",
    category: "Geography",
    text: "Which continent is the largest by area?",
    options: ["Africa","Asia","North America","Europe"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-742",
    category: "General",
    text: "How many minutes are in 23 hours?",
    options: ["1440","552","2300","1380"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-66",
    category: "Geography",
    text: "Which country has the capital Prague?",
    options: ["Greece","Colombia","Czech Republic","Italy"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-748",
    category: "General",
    text: "How many hours are in 11 days?",
    options: ["240","264","132","265"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-718",
    category: "General",
    text: "How many meters are in 25 km?",
    options: ["25000","25100","250","24900"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-160",
    category: "Science",
    text: "What is the chemical symbol for Tin?",
    options: ["Ag","H","Ne","Sn"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-20",
    category: "Geography",
    text: "What is the capital of Turkey?",
    options: ["Ankara","Copenhagen","Helsinki","Budapest"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-780",
    category: "General",
    text: "How many days does March have (common year)?",
    options: ["30","31","29","28"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-763",
    category: "General",
    text: "What number is the Roman numeral VII?",
    options: ["9","7","50","8"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-90",
    category: "Geography",
    text: "Which country has the capital Tokyo?",
    options: ["Ireland","Japan","Morocco","Serbia"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-741",
    category: "General",
    text: "How many minutes are in 21 hours?",
    options: ["1260","1320","504","1290"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-820",
    category: "Science",
    text: "Approximately how many °F is 20°C?",
    options: ["40","73","68","78"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-775",
    category: "General",
    text: "What number is the Roman numeral C?",
    options: ["1","10","20","100"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-19",
    category: "Geography",
    text: "What is the capital of Greece?",
    options: ["Berlin","Bangkok","Athens","Bern"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-721",
    category: "General",
    text: "How many meters are in 31 km?",
    options: ["31000","32000","310","31100"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-50",
    category: "Geography",
    text: "What is the capital of Israel?",
    options: ["Mexico City","Ankara","Jerusalem","London"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-696",
    category: "Sports",
    text: "How many players per team are typically on the field in basketball?",
    options: ["10","5","7","9"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-651",
    category: "History",
    text: "In which year: JFK assassination?",
    options: ["1492","1963","1977","1961"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-739",
    category: "General",
    text: "How many minutes are in 17 hours?",
    options: ["1050","1020","408","1080"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-117",
    category: "Science",
    text: "What element has the symbol N?",
    options: ["Nitrogen","Calcium","Sodium","Tin"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-109",
    category: "Science",
    text: "What element has the symbol H?",
    options: ["Zinc","Phosphorus","Hydrogen","Copper"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-181",
    category: "Science",
    text: "Which position from the Sun is Jupiter?",
    options: ["1","7","4","5"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-675",
    category: "Nature",
    text: "Where does a shark typically live?",
    options: ["China","Australia","ocean","savanna"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-37",
    category: "Geography",
    text: "What is the capital of China?",
    options: ["Nairobi","Ottawa","Pretoria","Beijing"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-659",
    category: "Nature",
    text: "Where does a moose typically live?",
    options: ["savanna","swamp","forest","savanna"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-102",
    category: "Geography",
    text: "Which country has the capital Abuja?",
    options: ["Vietnam","Netherlands","Nigeria","Mexico"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-788",
    category: "General",
    text: "How many days does July have (common year)?",
    options: ["29","30","31","28"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-40",
    category: "Geography",
    text: "What is the capital of Thailand?",
    options: ["London","Paris","Bangkok","Kyiv"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-24",
    category: "Geography",
    text: "What is the capital of Romania?",
    options: ["Bucharest","Abuja","Tokyo","Berlin"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-156",
    category: "Science",
    text: "What is the chemical symbol for Lead?",
    options: ["Pb","Ca","Mg","He"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-793",
    category: "General",
    text: "Which month comes after September?",
    options: ["September","November","July","October"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-79",
    category: "Geography",
    text: "Which country has the capital Sofia?",
    options: ["Saudi Arabia","Vietnam","Bulgaria","Turkey"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-44",
    category: "Geography",
    text: "What is the capital of New Zealand?",
    options: ["Reykjavik","Rome","London","Wellington"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-112",
    category: "Science",
    text: "What is the chemical symbol for Helium?",
    options: ["Al","Fe","He","Ti"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-755",
    category: "General",
    text: "What number is the Roman numeral III?",
    options: ["6","1","3","7"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-720",
    category: "General",
    text: "How many meters are in 29 km?",
    options: ["29000","30000","28900","290"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-687",
    category: "Nature",
    text: "Where does a zebra typically live?",
    options: ["forest","Australia","savanna","ocean"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-709",
    category: "General",
    text: "How many meters are in 7 km?",
    options: ["7100","7000","70","700"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-650",
    category: "History",
    text: "In which year: September 11 attacks?",
    options: ["1991","1989","2001","1945"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-824",
    category: "Geography",
    text: "How many continents are there usually?",
    options: ["5","6","7","8"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-751",
    category: "General",
    text: "What number is the Roman numeral I?",
    options: ["2","20","10","1"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-688",
    category: "Nature",
    text: "What is a baby gorilla called?",
    options: ["calf","pup","infant","cub"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-645",
    category: "History",
    text: "In which year: Columbus reaches America?",
    options: ["1961","1492","1939","1991"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-658",
    category: "Nature",
    text: "What is a baby moose called?",
    options: ["pup","joey","owlet","calf"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-77",
    category: "Geography",
    text: "Which country has the capital Budapest?",
    options: ["Japan","Croatia","Bulgaria","Hungary"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-172",
    category: "Science",
    text: "What is the chemical symbol for Platinum?",
    options: ["Pt","Ag","P","Al"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-108",
    category: "Geography",
    text: "Which country has the capital Baghdad?",
    options: ["Thailand","New Zealand","Iraq","Spain"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-164",
    category: "Science",
    text: "What is the chemical symbol for Cobalt?",
    options: ["S","He","Co","Ag"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-179",
    category: "Science",
    text: "Which position from the Sun is Mars?",
    options: ["1","8","4","6"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-7",
    category: "Geography",
    text: "What is the capital of France?",
    options: ["Jakarta","Abuja","Paris","Ankara"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-132",
    category: "Science",
    text: "What is the chemical symbol for Silicon?",
    options: ["Co","Pt","Si","O"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-137",
    category: "Science",
    text: "What element has the symbol Cl?",
    options: ["Phosphorus","Nitrogen","Fluorine","Chlorine"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-11",
    category: "Geography",
    text: "What is the capital of Poland?",
    options: ["Riyadh","New Delhi","Warsaw","Canberra"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-682",
    category: "Nature",
    text: "What is a baby crocodile called?",
    options: ["hatchling","owlet","eaglet","joey"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-88",
    category: "Geography",
    text: "Which country has the capital Lima?",
    options: ["Peru","Norway","China","Iraq"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-694",
    category: "Sports",
    text: "How many players per team are typically on the field in handball?",
    options: ["11","6","8","7"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-677",
    category: "Nature",
    text: "Where does a dolphin typically live?",
    options: ["swamp","ocean","forest","savanna"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-787",
    category: "General",
    text: "Which month comes after June?",
    options: ["July","May","February","September"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-740",
    category: "General",
    text: "How many minutes are in 19 hours?",
    options: ["1200","1140","1110","1170"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-91",
    category: "Geography",
    text: "Which country has the capital Beijing?",
    options: ["China","Turkey","Norway","Netherlands"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-68",
    category: "Geography",
    text: "Which country has the capital Bern?",
    options: ["Saudi Arabia","Ireland","Switzerland","Morocco"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-167",
    category: "Science",
    text: "What element has the symbol Cr?",
    options: ["Chromium","Nitrogen","Sulfur","Titanium"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-139",
    category: "Science",
    text: "What element has the symbol K?",
    options: ["Fluorine","Sulfur","Hydrogen","Potassium"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-153",
    category: "Science",
    text: "What element has the symbol Hg?",
    options: ["Oxygen","Copper","Helium","Mercury"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-75",
    category: "Geography",
    text: "Which country has the capital Moscow?",
    options: ["Russia","Morocco","New Zealand","France"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-823",
    category: "Science",
    text: "Approximately how many °F is 37°C?",
    options: ["98.6","74","108.6","0"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-782",
    category: "General",
    text: "How many days does April have (common year)?",
    options: ["31","30","28","29"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-85",
    category: "Geography",
    text: "Which country has the capital Brasília?",
    options: ["India","South Africa","Brazil","Serbia"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-124",
    category: "Science",
    text: "What is the chemical symbol for Neon?",
    options: ["S","Li","Ne","Ag"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-745",
    category: "General",
    text: "How many hours are in 5 days?",
    options: ["120","300","60","96"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-686",
    category: "Nature",
    text: "What is a baby zebra called?",
    options: ["foal","calf","infant","eaglet"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-118",
    category: "Science",
    text: "What is the chemical symbol for Nitrogen?",
    options: ["Fe","Al","N","Ti"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-731",
    category: "General",
    text: "How many minutes are in 1 hours?",
    options: ["60","30","120","100"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-127",
    category: "Science",
    text: "What element has the symbol Mg?",
    options: ["Titanium","Magnesium","Copper","Manganese"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-646",
    category: "History",
    text: "In which year: US Declaration of Independence?",
    options: ["1991","1776","1977","1989"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-34",
    category: "Geography",
    text: "What is the capital of Peru?",
    options: ["Moscow","Lima","Pretoria","Buenos Aires"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-83",
    category: "Geography",
    text: "Which country has the capital Ottawa?",
    options: ["Ireland","Belgium","Iraq","Canada"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-649",
    category: "History",
    text: "In which year: End of WWII in Europe?",
    options: ["1903","1989","1945","1776"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-169",
    category: "Science",
    text: "What element has the symbol Ti?",
    options: ["Titanium","Oxygen","Hydrogen","Phosphorus"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-131",
    category: "Science",
    text: "What element has the symbol Si?",
    options: ["Silicon","Copper","Fluorine","Lithium"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-749",
    category: "General",
    text: "How many hours are in 13 days?",
    options: ["313","312","780","156"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-9",
    category: "Geography",
    text: "What is the capital of Italy?",
    options: ["Rome","Prague","Madrid","Budapest"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-154",
    category: "Science",
    text: "What is the chemical symbol for Mercury?",
    options: ["P","Al","Ag","Hg"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-765",
    category: "General",
    text: "What number is the Roman numeral VIII?",
    options: ["100","8","4","6"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-162",
    category: "Science",
    text: "What is the chemical symbol for Nickel?",
    options: ["Ni","H","He","I"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-62",
    category: "Geography",
    text: "Which country has the capital Madrid?",
    options: ["Finland","United Arab Emirates","Spain","Egypt"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-674",
    category: "Nature",
    text: "What is a baby shark called?",
    options: ["joey","pup","infant","foal"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-1",
    category: "Geography",
    text: "What is the capital of Sweden?",
    options: ["Hanoi","Vienna","Ottawa","Stockholm"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-727",
    category: "General",
    text: "How many meters are in 43 km?",
    options: ["430","44000","43100","43000"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-734",
    category: "General",
    text: "How many minutes are in 7 hours?",
    options: ["390","420","450","168"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-84",
    category: "Geography",
    text: "Which country has the capital Mexico City?",
    options: ["Australia","Chile","Mexico","Argentina"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-152",
    category: "Science",
    text: "What is the chemical symbol for Gold?",
    options: ["Mn","Au","Ca","O"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-187",
    category: "Science",
    text: "Which position from the Sun is Neptune?",
    options: ["2","4","8","1"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-122",
    category: "Science",
    text: "What is the chemical symbol for Fluorine?",
    options: ["Hg","Li","Fe","F"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-59",
    category: "Geography",
    text: "Which country has the capital Reykjavik?",
    options: ["Canada","Ukraine","Austria","Iceland"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-746",
    category: "General",
    text: "How many hours are in 7 days?",
    options: ["420","192","84","168"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-168",
    category: "Science",
    text: "What is the chemical symbol for Chromium?",
    options: ["O","Cl","Cr","Mn"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-151",
    category: "Science",
    text: "What element has the symbol Au?",
    options: ["Titanium","Carbon","Silver","Gold"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-60",
    category: "Geography",
    text: "Which country has the capital Berlin?",
    options: ["Norway","Germany","Italy","Australia"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-708",
    category: "General",
    text: "How many meters are in 5 km?",
    options: ["4900","5100","500","5000"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-76",
    category: "Geography",
    text: "Which country has the capital Kyiv?",
    options: ["Hungary","Nigeria","Spain","Ukraine"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-725",
    category: "General",
    text: "How many meters are in 39 km?",
    options: ["40000","39000","39100","390"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-744",
    category: "General",
    text: "How many hours are in 3 days?",
    options: ["36","96","73","72"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-96",
    category: "Geography",
    text: "Which country has the capital Jakarta?",
    options: ["Indonesia","France","New Zealand","Iraq"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-143",
    category: "Science",
    text: "What element has the symbol Fe?",
    options: ["Manganese","Iron","Cobalt","Helium"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-671",
    category: "Nature",
    text: "Where does a wolf typically live?",
    options: ["savanna","forest","savanna","swamp"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-123",
    category: "Science",
    text: "What element has the symbol Ne?",
    options: ["Manganese","Calcium","Neon","Magnesium"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-699",
    category: "Sports",
    text: "What is primarily used in volleyball?",
    options: ["disk","ball","shuttlecock","puck"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-53",
    category: "Geography",
    text: "What is the capital of Iran?",
    options: ["Mexico City","Rome","Tehran","Tokyo"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-676",
    category: "Nature",
    text: "What is a baby dolphin called?",
    options: ["owlet","eaglet","calf","chick"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-655",
    category: "History",
    text: "In which year: Dissolution of the Soviet Union?",
    options: ["1977","1939","1991","1789"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-711",
    category: "General",
    text: "How many meters are in 11 km?",
    options: ["11000","10900","12000","110"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-685",
    category: "Nature",
    text: "Where does a giraffe typically live?",
    options: ["savanna","Antarctica","forest","jungle"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-3",
    category: "Geography",
    text: "What is the capital of Denmark?",
    options: ["Abuja","Pretoria","Copenhagen","Tokyo"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-173",
    category: "Science",
    text: "Which position from the Sun is Mercury?",
    options: ["3","8","6","1"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-33",
    category: "Geography",
    text: "What is the capital of Chile?",
    options: ["Santiago","Amsterdam","New Delhi","Rome"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-684",
    category: "Nature",
    text: "What is a baby giraffe called?",
    options: ["owlet","cub","chick","calf"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-186",
    category: "Science",
    text: "Which planet is #7 from the Sun?",
    options: ["Earth","Jupiter","Venus","Uranus"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-28",
    category: "Geography",
    text: "What is the capital of USA?",
    options: ["Tehran","Washington, D.C.","Brussels","Bucharest"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-101",
    category: "Geography",
    text: "Which country has the capital Rabat?",
    options: ["Austria","United Arab Emirates","New Zealand","Morocco"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-98",
    category: "Geography",
    text: "Which country has the capital Wellington?",
    options: ["Israel","New Zealand","Romania","Egypt"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-715",
    category: "General",
    text: "How many meters are in 19 km?",
    options: ["20000","19000","190","19100"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-12",
    category: "Geography",
    text: "What is the capital of Czech Republic?",
    options: ["Tehran","Seoul","Prague","Oslo"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-693",
    category: "Sports",
    text: "What is primarily used in ice hockey?",
    options: ["disk","ball","puck","shuttlecock"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-72",
    category: "Geography",
    text: "Which country has the capital London?",
    options: ["Kenya","United Kingdom","United Arab Emirates","Iraq"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-10",
    category: "Geography",
    text: "What is the capital of Portugal?",
    options: ["Berlin","Rome","Lisbon","Reykjavik"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-165",
    category: "Science",
    text: "What element has the symbol Mn?",
    options: ["Manganese","Sulfur","Fluorine","Phosphorus"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-48",
    category: "Geography",
    text: "What is the capital of Nigeria?",
    options: ["Abu Dhabi","Helsinki","Tehran","Abuja"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-184",
    category: "Science",
    text: "Which planet is #6 from the Sun?",
    options: ["Jupiter","Saturn","Mars","Neptune"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-15",
    category: "Geography",
    text: "What is the capital of Netherlands?",
    options: ["Buenos Aires","Brussels","Amsterdam","Moscow"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-652",
    category: "History",
    text: "In which year: First human in space?",
    options: ["1991","1961","1945","1939"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-794",
    category: "General",
    text: "How many days does October have (common year)?",
    options: ["29","31","30","28"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-697",
    category: "Sports",
    text: "What is primarily used in basketball?",
    options: ["disk","puck","shuttlecock","ball"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-680",
    category: "Nature",
    text: "What is a baby owl called?",
    options: ["cub","joey","calf","owlet"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-56",
    category: "Geography",
    text: "Which country has the capital Oslo?",
    options: ["Norway","China","Colombia","Poland"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-661",
    category: "Nature",
    text: "Where does a lion typically live?",
    options: ["Antarctica","forest","mountains","savanna"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-97",
    category: "Geography",
    text: "Which country has the capital Canberra?",
    options: ["Czech Republic","Egypt","Germany","Australia"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-690",
    category: "Sports",
    text: "How many players per team are typically on the field in soccer?",
    options: ["11","9","10","8"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-159",
    category: "Science",
    text: "What element has the symbol Sn?",
    options: ["Mercury","Iron","Tin","Gold"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-57",
    category: "Geography",
    text: "Which country has the capital Copenhagen?",
    options: ["Austria","Denmark","Poland","Vietnam"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-669",
    category: "Nature",
    text: "Where does a panda typically live?",
    options: ["China","jungle","forest","ocean"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-51",
    category: "Geography",
    text: "What is the capital of Saudi Arabia?",
    options: ["Bangkok","Riyadh","Jakarta","Cairo"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-148",
    category: "Science",
    text: "What is the chemical symbol for Zinc?",
    options: ["Li","Pt","C","Zn"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-163",
    category: "Science",
    text: "What element has the symbol Co?",
    options: ["Lead","Cobalt","Sodium","Potassium"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-74",
    category: "Geography",
    text: "Which country has the capital Ankara?",
    options: ["Iceland","Thailand","Bulgaria","Turkey"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-166",
    category: "Science",
    text: "What is the chemical symbol for Manganese?",
    options: ["Ni","He","I","Mn"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-61",
    category: "Geography",
    text: "Which country has the capital Paris?",
    options: ["Sweden","Germany","Chile","France"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-188",
    category: "Science",
    text: "Which planet is #8 from the Sun?",
    options: ["Venus","Earth","Mars","Neptune"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-78",
    category: "Geography",
    text: "Which country has the capital Bucharest?",
    options: ["Brazil","Sweden","Romania","Belgium"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-45",
    category: "Geography",
    text: "What is the capital of Egypt?",
    options: ["Paris","Washington, D.C.","Cairo","Vienna"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-38",
    category: "Geography",
    text: "What is the capital of South Korea?",
    options: ["Zagreb","Seoul","Berlin","Abu Dhabi"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-149",
    category: "Science",
    text: "What element has the symbol Ag?",
    options: ["Helium","Silver","Carbon","Chromium"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-791",
    category: "General",
    text: "Which month comes after August?",
    options: ["September","March","February","April"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-662",
    category: "Nature",
    text: "What is a baby elephant called?",
    options: ["cub","calf","owlet","foal"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-22",
    category: "Geography",
    text: "What is the capital of Ukraine?",
    options: ["Kyiv","Baghdad","Belgrade","Paris"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-46",
    category: "Geography",
    text: "What is the capital of South Africa?",
    options: ["Pretoria","Athens","Ottawa","Baghdad"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-784",
    category: "General",
    text: "How many days does May have (common year)?",
    options: ["30","29","31","28"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-121",
    category: "Science",
    text: "What element has the symbol F?",
    options: ["Fluorine","Silver","Platinum","Gold"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-36",
    category: "Geography",
    text: "What is the capital of Japan?",
    options: ["Zagreb","Riyadh","Helsinki","Tokyo"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-769",
    category: "General",
    text: "What number is the Roman numeral X?",
    options: ["10","2","5","50"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-672",
    category: "Nature",
    text: "What is a baby bear called?",
    options: ["cub","chick","calf","joey"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-113",
    category: "Science",
    text: "What element has the symbol Li?",
    options: ["Platinum","Chromium","Lithium","Neon"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-23",
    category: "Geography",
    text: "What is the capital of Hungary?",
    options: ["Brussels","Cairo","Budapest","Paris"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-31",
    category: "Geography",
    text: "What is the capital of Brazil?",
    options: ["Nairobi","Brasília","Belgrade","Stockholm"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-738",
    category: "General",
    text: "How many minutes are in 15 hours?",
    options: ["360","1500","930","900"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-647",
    category: "History",
    text: "In which year: Start of WWI?",
    options: ["1914","1789","2001","1903"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-170",
    category: "Science",
    text: "What is the chemical symbol for Titanium?",
    options: ["Ti","Pb","Cr","S"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-128",
    category: "Science",
    text: "What is the chemical symbol for Magnesium?",
    options: ["Cr","Ni","Mg","P"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-783",
    category: "General",
    text: "Which month comes after April?",
    options: ["October","August","March","May"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-130",
    category: "Science",
    text: "What is the chemical symbol for Aluminum?",
    options: ["P","Al","Cl","I"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-71",
    category: "Geography",
    text: "Which country has the capital Dublin?",
    options: ["Ireland","Colombia","Serbia","Austria"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-14",
    category: "Geography",
    text: "What is the capital of Switzerland?",
    options: ["Beijing","Budapest","Cairo","Bern"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-730",
    category: "General",
    text: "How many meters are in 49 km?",
    options: ["49000","4900","49100","490"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-732",
    category: "General",
    text: "How many minutes are in 3 hours?",
    options: ["150","180","210","300"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-146",
    category: "Science",
    text: "What is the chemical symbol for Copper?",
    options: ["Cu","Fe","Ni","Li"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-785",
    category: "General",
    text: "Which month comes after May?",
    options: ["May","June","February","April"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-182",
    category: "Science",
    text: "Which planet is #5 from the Sun?",
    options: ["Jupiter","Neptune","Uranus","Mercury"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-657",
    category: "History",
    text: "In which year: First Star Wars film?",
    options: ["1789","1939","1977","1492"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-728",
    category: "General",
    text: "How many meters are in 45 km?",
    options: ["4500","450","45100","45000"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-183",
    category: "Science",
    text: "Which position from the Sun is Saturn?",
    options: ["3","7","8","6"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-668",
    category: "Nature",
    text: "What is a baby panda called?",
    options: ["hatchling","pup","calf","cub"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-818",
    category: "Science",
    text: "Approximately how many °F is -40°C?",
    options: ["-35","0","-30","-40"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-644",
    category: "History",
    text: "In which year: Fall of the Berlin Wall?",
    options: ["1977","2001","1903","1989"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-87",
    category: "Geography",
    text: "Which country has the capital Santiago?",
    options: ["South Africa","Germany","Chile","Russia"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-178",
    category: "Science",
    text: "Which planet is #3 from the Sun?",
    options: ["Mars","Neptune","Earth","Mercury"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-822",
    category: "Science",
    text: "Approximately how many °F is 30°C?",
    options: ["86","0","60","81"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-704",
    category: "Sports",
    text: "How many players per team are typically on the field in baseball?",
    options: ["8","5","6","9"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-743",
    category: "General",
    text: "How many hours are in 1 days?",
    options: ["24","12","48","25"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-722",
    category: "General",
    text: "How many meters are in 33 km?",
    options: ["34000","3300","32900","33000"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-702",
    category: "Sports",
    text: "How many players per team are typically on the field in golf?",
    options: ["5","1","11","9"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-667",
    category: "Nature",
    text: "Where does a kangaroo typically live?",
    options: ["forest","swamp","China","Australia"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-177",
    category: "Science",
    text: "Which position from the Sun is Earth?",
    options: ["5","7","4","3"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-114",
    category: "Science",
    text: "What is the chemical symbol for Lithium?",
    options: ["Li","Al","I","C"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-99",
    category: "Geography",
    text: "Which country has the capital Cairo?",
    options: ["United Arab Emirates","New Zealand","Egypt","Nigeria"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-660",
    category: "Nature",
    text: "What is a baby lion called?",
    options: ["joey","pup","cub","calf"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-120",
    category: "Science",
    text: "What is the chemical symbol for Oxygen?",
    options: ["Ni","Zn","O","Cr"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-147",
    category: "Science",
    text: "What element has the symbol Zn?",
    options: ["Tin","Zinc","Sodium","Lead"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-735",
    category: "General",
    text: "How many minutes are in 9 hours?",
    options: ["510","216","900","540"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-86",
    category: "Geography",
    text: "Which country has the capital Buenos Aires?",
    options: ["Indonesia","Romania","Argentina","Morocco"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-27",
    category: "Geography",
    text: "What is the capital of Serbia?",
    options: ["Bucharest","Riyadh","Budapest","Belgrade"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-81",
    category: "Geography",
    text: "Which country has the capital Belgrade?",
    options: ["Serbia","South Korea","Austria","China"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-736",
    category: "General",
    text: "How many minutes are in 11 hours?",
    options: ["264","690","660","1100"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-759",
    category: "General",
    text: "What number is the Roman numeral V?",
    options: ["5","8","20","2"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-8",
    category: "Geography",
    text: "What is the capital of Spain?",
    options: ["Pretoria","Madrid","Baghdad","Kyiv"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-89",
    category: "Geography",
    text: "Which country has the capital Bogotá?",
    options: ["Iraq","Ireland","China","Colombia"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-158",
    category: "Science",
    text: "What is the chemical symbol for Iodine?",
    options: ["F","Al","Pt","I"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-771",
    category: "General",
    text: "What number is the Roman numeral XX?",
    options: ["10","20","100","6"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-5",
    category: "Geography",
    text: "What is the capital of Iceland?",
    options: ["Reykjavik","Lisbon","Stockholm","Moscow"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-701",
    category: "Sports",
    text: "What is primarily used in tennis?",
    options: ["puck","shuttlecock","ball","disk"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-703",
    category: "Sports",
    text: "What is primarily used in golf?",
    options: ["shuttlecock","puck","disk","ball"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-175",
    category: "Science",
    text: "Which position from the Sun is Venus?",
    options: ["8","2","7","5"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-706",
    category: "General",
    text: "How many meters are in 1 km?",
    options: ["900","2000","100","1000"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-714",
    category: "General",
    text: "How many meters are in 17 km?",
    options: ["1700","16900","17000","18000"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-185",
    category: "Science",
    text: "Which position from the Sun is Uranus?",
    options: ["7","3","8","5"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-52",
    category: "Geography",
    text: "What is the capital of United Arab Emirates?",
    options: ["Ottawa","Dublin","Mexico City","Abu Dhabi"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-157",
    category: "Science",
    text: "What element has the symbol I?",
    options: ["Iodine","Magnesium","Lithium","Helium"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-707",
    category: "General",
    text: "How many meters are in 3 km?",
    options: ["4000","300","2900","3000"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-69",
    category: "Geography",
    text: "Which country has the capital Amsterdam?",
    options: ["Spain","Netherlands","Sweden","Ireland"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-17",
    category: "Geography",
    text: "What is the capital of Ireland?",
    options: ["Reykjavik","Jakarta","Abuja","Dublin"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-716",
    category: "General",
    text: "How many meters are in 21 km?",
    options: ["20900","2100","21100","21000"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-39",
    category: "Geography",
    text: "What is the capital of India?",
    options: ["Washington, D.C.","Sofia","Brussels","New Delhi"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-140",
    category: "Science",
    text: "What is the chemical symbol for Potassium?",
    options: ["Cu","K","Cl","S"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-4",
    category: "Geography",
    text: "What is the capital of Finland?",
    options: ["Bangkok","Tokyo","Tehran","Helsinki"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-138",
    category: "Science",
    text: "What is the chemical symbol for Chlorine?",
    options: ["Li","Cl","Co","He"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-683",
    category: "Nature",
    text: "Where does a crocodile typically live?",
    options: ["mountains","forest","swamp","savanna"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-2",
    category: "Geography",
    text: "What is the capital of Norway?",
    options: ["Oslo","Moscow","Canberra","Kyiv"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-30",
    category: "Geography",
    text: "What is the capital of Mexico?",
    options: ["Mexico City","Tehran","Reykjavik","Helsinki"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-141",
    category: "Science",
    text: "What element has the symbol Ca?",
    options: ["Hydrogen","Zinc","Chromium","Calcium"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-670",
    category: "Nature",
    text: "What is a baby wolf called?",
    options: ["calf","chick","cub","pup"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-6",
    category: "Geography",
    text: "What is the capital of Germany?",
    options: ["Jakarta","Amsterdam","Dublin","Berlin"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-155",
    category: "Science",
    text: "What element has the symbol Pb?",
    options: ["Lead","Titanium","Iodine","Nitrogen"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-648",
    category: "History",
    text: "In which year: Start of WWII?",
    options: ["1945","1939","1789","2001"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-176",
    category: "Science",
    text: "Which planet is #2 from the Sun?",
    options: ["Jupiter","Venus","Mercury","Earth"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-29",
    category: "Geography",
    text: "What is the capital of Canada?",
    options: ["Canberra","Ottawa","Wellington","Dublin"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-103",
    category: "Geography",
    text: "Which country has the capital Nairobi?",
    options: ["Colombia","United Kingdom","Kenya","Morocco"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-819",
    category: "Science",
    text: "Approximately how many °F is 10°C?",
    options: ["55","60","0","50"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-776",
    category: "General",
    text: "How many days does January have (common year)?",
    options: ["29","28","31","30"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-796",
    category: "General",
    text: "How many days does November have (common year)?",
    options: ["31","29","28","30"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-82",
    category: "Geography",
    text: "Which country has the capital Washington, D.C.?",
    options: ["Iran","USA","Australia","United Kingdom"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-733",
    category: "General",
    text: "How many minutes are in 5 hours?",
    options: ["270","360","500","300"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-789",
    category: "General",
    text: "Which month comes after July?",
    options: ["June","August","December","October"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-129",
    category: "Science",
    text: "What element has the symbol Al?",
    options: ["Cobalt","Chromium","Aluminum","Oxygen"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-654",
    category: "History",
    text: "In which year: French Revolution begins?",
    options: ["1963","1789","1492","1977"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-723",
    category: "General",
    text: "How many meters are in 35 km?",
    options: ["3500","34900","36000","35000"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-767",
    category: "General",
    text: "What number is the Roman numeral IX?",
    options: ["9","5","10","8"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-689",
    category: "Nature",
    text: "Where does a gorilla typically live?",
    options: ["ocean","forest","jungle","Antarctica"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-719",
    category: "General",
    text: "How many meters are in 27 km?",
    options: ["2700","27000","27100","270"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-747",
    category: "General",
    text: "How many hours are in 9 days?",
    options: ["540","192","216","108"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-761",
    category: "General",
    text: "What number is the Roman numeral VI?",
    options: ["1","6","2","5"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-43",
    category: "Geography",
    text: "What is the capital of Australia?",
    options: ["Oslo","Athens","Brasília","Canberra"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-107",
    category: "Geography",
    text: "Which country has the capital Tehran?",
    options: ["Iran","Argentina","Ireland","Romania"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-67",
    category: "Geography",
    text: "Which country has the capital Vienna?",
    options: ["Ukraine","Turkey","Saudi Arabia","Austria"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-753",
    category: "General",
    text: "What number is the Roman numeral II?",
    options: ["7","8","2","9"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-666",
    category: "Nature",
    text: "What is a baby kangaroo called?",
    options: ["cub","hatchling","pup","joey"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-100",
    category: "Geography",
    text: "Which country has the capital Pretoria?",
    options: ["Australia","Colombia","Kenya","South Africa"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-93",
    category: "Geography",
    text: "Which country has the capital New Delhi?",
    options: ["Canada","Romania","India","Bulgaria"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-171",
    category: "Science",
    text: "What element has the symbol Pt?",
    options: ["Manganese","Carbon","Chromium","Platinum"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-710",
    category: "General",
    text: "How many meters are in 9 km?",
    options: ["8900","9100","9000","10000"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-105",
    category: "Geography",
    text: "Which country has the capital Riyadh?",
    options: ["Romania","Saudi Arabia","France","Russia"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-695",
    category: "Sports",
    text: "What is primarily used in handball?",
    options: ["disk","puck","shuttlecock","ball"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-712",
    category: "General",
    text: "How many meters are in 13 km?",
    options: ["130","13000","12900","1300"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-94",
    category: "Geography",
    text: "Which country has the capital Bangkok?",
    options: ["Thailand","Kenya","Austria","Egypt"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-798",
    category: "General",
    text: "How many days does December have (common year)?",
    options: ["31","30","29","28"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-726",
    category: "General",
    text: "How many meters are in 41 km?",
    options: ["42000","410","41000","40900"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-705",
    category: "Sports",
    text: "What is primarily used in baseball?",
    options: ["shuttlecock","ball","puck","disk"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-692",
    category: "Sports",
    text: "How many players per team are typically on the field in ice hockey?",
    options: ["6","10","7","8"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-133",
    category: "Science",
    text: "What element has the symbol P?",
    options: ["Nitrogen","Phosphorus","Zinc","Lithium"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-104",
    category: "Geography",
    text: "Which country has the capital Jerusalem?",
    options: ["Iran","Ireland","Israel","Mexico"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-16",
    category: "Geography",
    text: "What is the capital of Belgium?",
    options: ["Lisbon","Madrid","Helsinki","Brussels"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-64",
    category: "Geography",
    text: "Which country has the capital Lisbon?",
    options: ["Portugal","Mexico","United Kingdom","Morocco"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-21",
    category: "Geography",
    text: "What is the capital of Russia?",
    options: ["Moscow","Tokyo","Amsterdam","Pretoria"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-58",
    category: "Geography",
    text: "Which country has the capital Helsinki?",
    options: ["Israel","Finland","Denmark","Egypt"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-125",
    category: "Science",
    text: "What element has the symbol Na?",
    options: ["Lithium","Tin","Sodium","Sulfur"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-92",
    category: "Geography",
    text: "Which country has the capital Seoul?",
    options: ["India","Spain","South Korea","Indonesia"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-790",
    category: "General",
    text: "How many days does August have (common year)?",
    options: ["30","31","28","29"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-678",
    category: "Nature",
    text: "What is a baby eagle called?",
    options: ["joey","calf","owlet","eaglet"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-799",
    category: "General",
    text: "Which month comes after December?",
    options: ["November","March","January","July"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-54",
    category: "Geography",
    text: "What is the capital of Iraq?",
    options: ["Rome","Baghdad","Rabat","Prague"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-821",
    category: "Science",
    text: "Approximately how many °F is 25°C?",
    options: ["87","0","77","72"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-781",
    category: "General",
    text: "Which month comes after March?",
    options: ["November","April","August","March"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-13",
    category: "Geography",
    text: "What is the capital of Austria?",
    options: ["Vienna","Tokyo","Dublin","Amsterdam"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-18",
    category: "Geography",
    text: "What is the capital of United Kingdom?",
    options: ["Abu Dhabi","Hanoi","Washington, D.C.","London"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-717",
    category: "General",
    text: "How many meters are in 23 km?",
    options: ["23100","230","23000","2300"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-679",
    category: "Nature",
    text: "Where does a eagle typically live?",
    options: ["savanna","China","jungle","mountains"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-42",
    category: "Geography",
    text: "What is the capital of Indonesia?",
    options: ["Budapest","Riyadh","Jakarta","Washington, D.C."],
    correctIndex: 2,
  },
  {
    id: "bulk-en-161",
    category: "Science",
    text: "What element has the symbol Ni?",
    options: ["Sodium","Carbon","Titanium","Nickel"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-700",
    category: "Sports",
    text: "How many players per team are typically on the field in tennis?",
    options: ["8","1","11","6"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-136",
    category: "Science",
    text: "What is the chemical symbol for Sulfur?",
    options: ["S","Ti","Cl","Sn"],
    correctIndex: 0,
  },
  {
    id: "bulk-en-817",
    category: "Science",
    text: "Approximately how many °F is 100°C?",
    options: ["207","217","200","212"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-80",
    category: "Geography",
    text: "Which country has the capital Zagreb?",
    options: ["Finland","South Africa","Croatia","Turkey"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-116",
    category: "Science",
    text: "What is the chemical symbol for Carbon?",
    options: ["Al","Li","C","Pb"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-816",
    category: "Science",
    text: "Approximately how many °F is 0°C?",
    options: ["37","42","0","32"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-792",
    category: "General",
    text: "How many days does September have (common year)?",
    options: ["31","29","30","28"],
    correctIndex: 2,
  },
  {
    id: "bulk-en-777",
    category: "General",
    text: "Which month comes after January?",
    options: ["July","December","April","February"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-55",
    category: "Geography",
    text: "Which country has the capital Stockholm?",
    options: ["United Arab Emirates","Sweden","Mexico","Austria"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-653",
    category: "History",
    text: "In which year: First powered flight?",
    options: ["1492","1903","1789","1914"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-63",
    category: "Geography",
    text: "Which country has the capital Rome?",
    options: ["Portugal","Italy","New Zealand","Ireland"],
    correctIndex: 1,
  },
  {
    id: "bulk-en-25",
    category: "Geography",
    text: "What is the capital of Bulgaria?",
    options: ["Ankara","Tehran","Brasília","Sofia"],
    correctIndex: 3,
  },
  {
    id: "bulk-en-70",
    category: "Geography",
    text: "Which country has the capital Brussels?",
    options: ["Finland","Thailand","Belgium","Colombia"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-367",
    category: "General",
    text: "What position in the alphabet is the letter O?",
    options: ["15","14","17","16"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-657",
    category: "General",
    text: "You pay 500 for an item costing 80. How much change?",
    options: ["500","425","415","420"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-357",
    category: "General",
    text: "What position in the alphabet is the letter E?",
    options: ["4","7","6","5"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-356",
    category: "General",
    text: "What position in the alphabet is the letter D?",
    options: ["4","5","26","3"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-374",
    category: "General",
    text: "What position in the alphabet is the letter V?",
    options: ["23","24","22","21"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-348",
    category: "General",
    text: "How many letters are in the word \"python\"?",
    options: ["6","5","10","8"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-665",
    category: "General",
    text: "You pay 170 for an item costing 120. How much change?",
    options: ["120","170","55","50"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-360",
    category: "General",
    text: "What position in the alphabet is the letter H?",
    options: ["10","26","8","9"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-358",
    category: "General",
    text: "What position in the alphabet is the letter F?",
    options: ["6","8","26","7"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-659",
    category: "General",
    text: "You pay 119 for an item costing 99. How much change?",
    options: ["15","25","99","20"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-339",
    category: "General",
    text: "How many letters are in the word \"factopia\"?",
    options: ["10","9","8","1446"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-364",
    category: "General",
    text: "What position in the alphabet is the letter L?",
    options: ["12","14","26","13"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-667",
    category: "General",
    text: "You pay 500 for an item costing 120. How much change?",
    options: ["380","500","375","120"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-351",
    category: "General",
    text: "How many letters are in the word \"thunder\"?",
    options: ["8","10","9","7"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-377",
    category: "General",
    text: "What position in the alphabet is the letter Y?",
    options: ["25","26","24","1200"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-375",
    category: "General",
    text: "What position in the alphabet is the letter W?",
    options: ["23","25","26","24"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-651",
    category: "General",
    text: "You pay 200 for an item costing 40. How much change?",
    options: ["155","40","165","160"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-658",
    category: "General",
    text: "You pay 109 for an item costing 99. How much change?",
    options: ["109","10","5","15"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-346",
    category: "General",
    text: "How many letters are in the word \"guitar\"?",
    options: ["8","10","5","6"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-338",
    category: "General",
    text: "How many letters are in the word \"quiz\"?",
    options: ["3","5","6","4"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-663",
    category: "General",
    text: "You pay 130 for an item costing 120. How much change?",
    options: ["130","10","15","120"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-355",
    category: "General",
    text: "What position in the alphabet is the letter C?",
    options: ["26","4","3","5"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-656",
    category: "General",
    text: "You pay 200 for an item costing 80. How much change?",
    options: ["80","120","115","125"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-650",
    category: "General",
    text: "You pay 90 for an item costing 40. How much change?",
    options: ["90","55","40","50"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-362",
    category: "General",
    text: "What position in the alphabet is the letter J?",
    options: ["10","9","12","26"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-343",
    category: "General",
    text: "How many letters are in the word \"computer\"?",
    options: ["10","8","9","1885"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-340",
    category: "General",
    text: "How many letters are in the word \"london\"?",
    options: ["5","10","8","6"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-350",
    category: "General",
    text: "How many letters are in the word \"galaxy\"?",
    options: ["5","8","6","7"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-347",
    category: "General",
    text: "How many letters are in the word \"soccer\"?",
    options: ["6","8","10","5"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-366",
    category: "General",
    text: "What position in the alphabet is the letter N?",
    options: ["14","16","15","13"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-363",
    category: "General",
    text: "What position in the alphabet is the letter K?",
    options: ["10","26","11","13"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-654",
    category: "General",
    text: "You pay 100 for an item costing 80. How much change?",
    options: ["100","15","20","80"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-341",
    category: "General",
    text: "How many letters are in the word \"paris\"?",
    options: ["5","4","10","7"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-376",
    category: "General",
    text: "What position in the alphabet is the letter X?",
    options: ["24","23","25","26"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-373",
    category: "General",
    text: "What position in the alphabet is the letter U?",
    options: ["23","26","20","21"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-345",
    category: "General",
    text: "How many letters are in the word \"ocean\"?",
    options: ["10","6","5","4"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-365",
    category: "General",
    text: "What position in the alphabet is the letter M?",
    options: ["15","13","26","14"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-661",
    category: "General",
    text: "You pay 200 for an item costing 99. How much change?",
    options: ["101","96","99","200"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-342",
    category: "General",
    text: "How many letters are in the word \"banana\"?",
    options: ["7","8","5","6"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-369",
    category: "General",
    text: "What position in the alphabet is the letter Q?",
    options: ["17","18","16","19"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-359",
    category: "General",
    text: "What position in the alphabet is the letter G?",
    options: ["9","8","26","7"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-662",
    category: "General",
    text: "You pay 500 for an item costing 99. How much change?",
    options: ["406","99","396","401"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-653",
    category: "General",
    text: "You pay 90 for an item costing 80. How much change?",
    options: ["80","5","10","90"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-344",
    category: "General",
    text: "How many letters are in the word \"planet\"?",
    options: ["7","6","8","5"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-349",
    category: "General",
    text: "How many letters are in the word \"javascript\"?",
    options: ["12","10","9","11"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-664",
    category: "General",
    text: "You pay 140 for an item costing 120. How much change?",
    options: ["120","25","20","140"],
    correctIndex: 2,
  },
  {
    id: "bulk2-en-378",
    category: "General",
    text: "What position in the alphabet is the letter Z?",
    options: ["28","27","25","26"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-648",
    category: "General",
    text: "You pay 50 for an item costing 40. How much change?",
    options: ["50","10","40","5"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-372",
    category: "General",
    text: "What position in the alphabet is the letter T?",
    options: ["19","21","22","20"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-352",
    category: "General",
    text: "How many letters are in the word \"puzzle\"?",
    options: ["7","6","8","5"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-368",
    category: "General",
    text: "What position in the alphabet is the letter P?",
    options: ["16","17","18","15"],
    correctIndex: 0,
  },
  {
    id: "bulk2-en-353",
    category: "General",
    text: "What position in the alphabet is the letter A?",
    options: ["26","2","3","1"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-655",
    category: "General",
    text: "You pay 130 for an item costing 80. How much change?",
    options: ["130","55","45","50"],
    correctIndex: 3,
  },
  {
    id: "bulk2-en-660",
    category: "General",
    text: "You pay 149 for an item costing 99. How much change?",
    options: ["149","50","99","55"],
    correctIndex: 1,
  },
  {
    id: "bulk2-en-354",
    category: "General",
    text: "What position in the alphabet is the letter B?",
    options: ["2","1","3","26"],
    correctIndex: 0,
  },
  {
    id: "tri-en-1",
    category: "History",
    text: "Who is credited with the telephone?",
    options: ["Tim Berners-Lee","Alfred Nobel","Alexander Graham Bell","Johannes Gutenberg"],
    correctIndex: 2,
  },
  {
    id: "tri-en-2",
    category: "History",
    text: "Who is credited with the light bulb (practical)?",
    options: ["The Wright brothers","Alexander Graham Bell","Marie Curie","Thomas Edison"],
    correctIndex: 3,
  },
  {
    id: "tri-en-3",
    category: "History",
    text: "Who is credited with dynamite?",
    options: ["Thomas Edison","Alexander Fleming","Alfred Nobel","The Wright brothers"],
    correctIndex: 2,
  },
  {
    id: "tri-en-4",
    category: "History",
    text: "Who is credited with penicillin?",
    options: ["The Wright brothers","Marie Curie","Alexander Fleming","Alexander Graham Bell"],
    correctIndex: 2,
  },
  {
    id: "tri-en-5",
    category: "History",
    text: "Who is credited with the printing press in Europe?",
    options: ["Alexander Fleming","Alfred Nobel","Johannes Gutenberg","Marie Curie"],
    correctIndex: 2,
  },
  {
    id: "tri-en-6",
    category: "History",
    text: "Who is credited with powered flight?",
    options: ["The Wright brothers","Marie Curie","Johannes Gutenberg","Alexander Fleming"],
    correctIndex: 0,
  },
  {
    id: "tri-en-7",
    category: "History",
    text: "Who is credited with radioactivity (discovery)?",
    options: ["Marie Curie","The Wright brothers","Alexander Graham Bell","Alfred Nobel"],
    correctIndex: 0,
  },
  {
    id: "tri-en-8",
    category: "History",
    text: "Who is credited with the World Wide Web?",
    options: ["Thomas Edison","The Wright brothers","Johannes Gutenberg","Tim Berners-Lee"],
    correctIndex: 3,
  },
  {
    id: "tri-en-9",
    category: "Culture",
    text: "Who wrote Harry Potter?",
    options: ["J.K. Rowling","F. Scott Fitzgerald","J.R.R. Tolkien","Jane Austen"],
    correctIndex: 0,
  },
  {
    id: "tri-en-10",
    category: "Culture",
    text: "Who wrote The Hobbit?",
    options: ["Jane Austen","F. Scott Fitzgerald","Homer","J.R.R. Tolkien"],
    correctIndex: 3,
  },
  {
    id: "tri-en-11",
    category: "Culture",
    text: "Who wrote 1984?",
    options: ["J.R.R. Tolkien","William Shakespeare","George Orwell","F. Scott Fitzgerald"],
    correctIndex: 2,
  },
  {
    id: "tri-en-12",
    category: "Culture",
    text: "Who wrote Pride and Prejudice?",
    options: ["George Orwell","J.K. Rowling","F. Scott Fitzgerald","Jane Austen"],
    correctIndex: 3,
  },
  {
    id: "tri-en-13",
    category: "Culture",
    text: "Who wrote The Great Gatsby?",
    options: ["Mary Shelley","J.R.R. Tolkien","F. Scott Fitzgerald","Jane Austen"],
    correctIndex: 2,
  },
  {
    id: "tri-en-14",
    category: "Culture",
    text: "Who wrote Romeo and Juliet?",
    options: ["William Shakespeare","J.R.R. Tolkien","J.K. Rowling","George Orwell"],
    correctIndex: 0,
  },
  {
    id: "tri-en-15",
    category: "Culture",
    text: "Who wrote The Odyssey?",
    options: ["Homer","J.K. Rowling","J.R.R. Tolkien","F. Scott Fitzgerald"],
    correctIndex: 0,
  },
  {
    id: "tri-en-16",
    category: "Culture",
    text: "Who wrote Frankenstein?",
    options: ["J.K. Rowling","Mary Shelley","George Orwell","Jane Austen"],
    correctIndex: 1,
  },
  {
    id: "tri-en-17",
    category: "Music",
    text: "How many strings does a guitar typically have?",
    options: ["6","4","7","3"],
    correctIndex: 0,
  },
  {
    id: "tri-en-18",
    category: "Music",
    text: "How many strings does a violin typically have?",
    options: ["7","4","3","6"],
    correctIndex: 1,
  },
  {
    id: "tri-en-19",
    category: "Music",
    text: "How many strings does a cello typically have?",
    options: ["7","4","5","6"],
    correctIndex: 1,
  },
  {
    id: "tri-en-20",
    category: "Music",
    text: "How many strings does a bass typically have?",
    options: ["8","6","7","4"],
    correctIndex: 3,
  },
  {
    id: "tri-en-21",
    category: "Music",
    text: "How many strings does a ukulele typically have?",
    options: ["3","4","7","6"],
    correctIndex: 1,
  },
  {
    id: "tri-en-22",
    category: "Food",
    text: "Which country is most associated with pizza?",
    options: ["Italy","China","Thailand","India"],
    correctIndex: 0,
  },
  {
    id: "tri-en-23",
    category: "Food",
    text: "Which country is most associated with sushi?",
    options: ["Japan","Greece","Spain","China"],
    correctIndex: 0,
  },
  {
    id: "tri-en-24",
    category: "Food",
    text: "Which country is most associated with tacos?",
    options: ["Italy","Mexico","Spain","Greece"],
    correctIndex: 1,
  },
  {
    id: "tri-en-25",
    category: "Food",
    text: "Which country is most associated with curry?",
    options: ["Thailand","Japan","Spain","India"],
    correctIndex: 3,
  },
  {
    id: "tri-en-26",
    category: "Food",
    text: "Which country is most associated with croissant?",
    options: ["France","Japan","Turkey","Italy"],
    correctIndex: 0,
  },
  {
    id: "tri-en-27",
    category: "Food",
    text: "Which country is most associated with moussaka?",
    options: ["Italy","China","Greece","Mexico"],
    correctIndex: 2,
  },
  {
    id: "tri-en-28",
    category: "Food",
    text: "Which country is most associated with paella?",
    options: ["China","Spain","Mexico","Italy"],
    correctIndex: 1,
  },
  {
    id: "tri-en-29",
    category: "Food",
    text: "Which country is most associated with hamburger?",
    options: ["Italy","Thailand","USA","Japan"],
    correctIndex: 2,
  },
  {
    id: "tri-en-30",
    category: "Food",
    text: "Which country is most associated with dim sum?",
    options: ["China","USA","Italy","Spain"],
    correctIndex: 0,
  },
  {
    id: "tri-en-31",
    category: "Food",
    text: "Which country is most associated with pad thai?",
    options: ["France","Japan","China","Thailand"],
    correctIndex: 3,
  },
  {
    id: "tri-en-32",
    category: "Food",
    text: "Which country is most associated with meatballs?",
    options: ["Sweden","Turkey","China","Mexico"],
    correctIndex: 0,
  },
  {
    id: "tri-en-33",
    category: "Food",
    text: "Which country is most associated with kebab?",
    options: ["China","Thailand","Italy","Turkey"],
    correctIndex: 3,
  },
  {
    id: "tri-en-34",
    category: "Geography",
    text: "Where is the Eiffel Tower located?",
    options: ["Cairo","Pisa","Rome","Paris"],
    correctIndex: 3,
  },
  {
    id: "tri-en-35",
    category: "Geography",
    text: "Where is the Colosseum located?",
    options: ["Cairo","Rome","Pisa","Paris"],
    correctIndex: 1,
  },
  {
    id: "tri-en-36",
    category: "Geography",
    text: "Where is the Pyramids of Giza located?",
    options: ["Cairo","Athens","London","New York"],
    correctIndex: 0,
  },
  {
    id: "tri-en-37",
    category: "Geography",
    text: "Where is the Great Wall located?",
    options: ["London","Sydney","Paris","Beijing"],
    correctIndex: 3,
  },
  {
    id: "tri-en-38",
    category: "Geography",
    text: "Where is the Taj Mahal located?",
    options: ["London","Paris","Athens","Agra"],
    correctIndex: 3,
  },
  {
    id: "tri-en-39",
    category: "Geography",
    text: "Where is the Opera House located?",
    options: ["Sydney","Agra","New York","Athens"],
    correctIndex: 0,
  },
  {
    id: "tri-en-40",
    category: "Geography",
    text: "Where is the Statue of Liberty located?",
    options: ["Paris","Cairo","New York","Sydney"],
    correctIndex: 2,
  },
  {
    id: "tri-en-41",
    category: "Geography",
    text: "Where is the Big Ben located?",
    options: ["Rome","Paris","London","Athens"],
    correctIndex: 2,
  },
  {
    id: "tri-en-42",
    category: "Geography",
    text: "Where is the Acropolis located?",
    options: ["Beijing","Cairo","Athens","New York"],
    correctIndex: 2,
  },
  {
    id: "tri-en-43",
    category: "Geography",
    text: "Where is the Leaning Tower located?",
    options: ["New York","Paris","Pisa","Athens"],
    correctIndex: 2,
  },
  {
    id: "tri-en-44",
    category: "Movies & TV",
    text: "Who directed Titanic?",
    options: ["Christopher Nolan","Francis Ford Coppola","James Cameron","Steven Spielberg"],
    correctIndex: 2,
  },
  {
    id: "tri-en-45",
    category: "Movies & TV",
    text: "Who directed Inception?",
    options: ["Steven Spielberg","Christopher Nolan","Quentin Tarantino","James Cameron"],
    correctIndex: 1,
  },
  {
    id: "tri-en-46",
    category: "Movies & TV",
    text: "Who directed Jurassic Park?",
    options: ["Quentin Tarantino","Christopher Nolan","Francis Ford Coppola","Steven Spielberg"],
    correctIndex: 3,
  },
  {
    id: "tri-en-47",
    category: "Movies & TV",
    text: "Who directed Pulp Fiction?",
    options: ["Christopher Nolan","Francis Ford Coppola","James Cameron","Quentin Tarantino"],
    correctIndex: 3,
  },
  {
    id: "tri-en-48",
    category: "Movies & TV",
    text: "Who directed Avatar?",
    options: ["James Cameron","Quentin Tarantino","Francis Ford Coppola","Christopher Nolan"],
    correctIndex: 0,
  },
  {
    id: "tri-en-49",
    category: "Movies & TV",
    text: "Who directed The Godfather?",
    options: ["Quentin Tarantino","Christopher Nolan","Steven Spielberg","Francis Ford Coppola"],
    correctIndex: 3,
  },
  {
    id: "tri-en-50",
    category: "Tech",
    text: "Which company is behind iPhone?",
    options: ["Google","Apple","Meta","—3"],
    correctIndex: 1,
  },
  {
    id: "tri-en-51",
    category: "Tech",
    text: "Which company is behind Windows?",
    options: ["Apple","Meta","Nintendo","Microsoft"],
    correctIndex: 3,
  },
  {
    id: "tri-en-52",
    category: "Tech",
    text: "Which company is behind Android?",
    options: ["Microsoft","Google","Nintendo","—3"],
    correctIndex: 1,
  },
  {
    id: "tri-en-53",
    category: "Tech",
    text: "Which company is behind PlayStation?",
    options: ["Microsoft","Nintendo","Sony","—3"],
    correctIndex: 2,
  },
  {
    id: "tri-en-54",
    category: "Tech",
    text: "Which company is behind Xbox?",
    options: ["Meta","Nintendo","Microsoft","Sony"],
    correctIndex: 2,
  },
  {
    id: "tri-en-55",
    category: "Tech",
    text: "Which company is behind Switch?",
    options: ["Nintendo","Apple","Sony","Google"],
    correctIndex: 0,
  },
  {
    id: "tri-en-56",
    category: "Tech",
    text: "Which company is behind Instagram?",
    options: ["Microsoft","Meta","Sony","—3"],
    correctIndex: 1,
  },
  {
    id: "tri-en-57",
    category: "Tech",
    text: "Which company is behind YouTube?",
    options: ["Microsoft","Sony","Google","—3"],
    correctIndex: 2,
  },
  {
    id: "tri-en-58",
    category: "Science",
    text: "Which element has the symbol Au?",
    options: ["Iron","Oxygen","Gold","Mercury"],
    correctIndex: 2,
  },
  {
    id: "tri-en-59",
    category: "Science",
    text: "What is the symbol for Gold?",
    options: ["Au","H","Pb","C"],
    correctIndex: 0,
  },
  {
    id: "tri-en-60",
    category: "Science",
    text: "Which element has the symbol Ag?",
    options: ["Silver","Sodium","Hydrogen","Carbon"],
    correctIndex: 0,
  },
  {
    id: "tri-en-61",
    category: "Science",
    text: "What is the symbol for Silver?",
    options: ["Ag","He","Fe","Pb"],
    correctIndex: 0,
  },
  {
    id: "tri-en-62",
    category: "Science",
    text: "Which element has the symbol Fe?",
    options: ["Mercury","Oxygen","Iron","Silver"],
    correctIndex: 2,
  },
  {
    id: "tri-en-63",
    category: "Science",
    text: "What is the symbol for Iron?",
    options: ["N","Fe","H","C"],
    correctIndex: 1,
  },
  {
    id: "tri-en-64",
    category: "Science",
    text: "Which element has the symbol O?",
    options: ["Hydrogen","Oxygen","Mercury","Carbon"],
    correctIndex: 1,
  },
  {
    id: "tri-en-65",
    category: "Science",
    text: "What is the symbol for Oxygen?",
    options: ["N","O","Fe","Ag"],
    correctIndex: 1,
  },
  {
    id: "tri-en-66",
    category: "Science",
    text: "Which element has the symbol H?",
    options: ["Silver","Iron","Helium","Hydrogen"],
    correctIndex: 3,
  },
  {
    id: "tri-en-67",
    category: "Science",
    text: "What is the symbol for Hydrogen?",
    options: ["Hg","Cu","H","Ag"],
    correctIndex: 2,
  },
  {
    id: "tri-en-68",
    category: "Science",
    text: "Which element has the symbol C?",
    options: ["Silver","Hydrogen","Sodium","Carbon"],
    correctIndex: 3,
  },
  {
    id: "tri-en-69",
    category: "Science",
    text: "What is the symbol for Carbon?",
    options: ["O","Ag","C","Na"],
    correctIndex: 2,
  },
  {
    id: "tri-en-70",
    category: "Science",
    text: "Which element has the symbol N?",
    options: ["Hydrogen","Nitrogen","Lead","Oxygen"],
    correctIndex: 1,
  },
  {
    id: "tri-en-71",
    category: "Science",
    text: "What is the symbol for Nitrogen?",
    options: ["Pb","Na","H","N"],
    correctIndex: 3,
  },
  {
    id: "tri-en-72",
    category: "Science",
    text: "Which element has the symbol Na?",
    options: ["Lead","Iron","Helium","Sodium"],
    correctIndex: 3,
  },
  {
    id: "tri-en-73",
    category: "Science",
    text: "What is the symbol for Sodium?",
    options: ["He","C","Na","N"],
    correctIndex: 2,
  },
  {
    id: "tri-en-74",
    category: "Science",
    text: "Which element has the symbol He?",
    options: ["Gold","Mercury","Helium","Copper"],
    correctIndex: 2,
  },
  {
    id: "tri-en-75",
    category: "Science",
    text: "What is the symbol for Helium?",
    options: ["He","Pb","O","Fe"],
    correctIndex: 0,
  },
  {
    id: "tri-en-76",
    category: "Science",
    text: "Which element has the symbol Cu?",
    options: ["Hydrogen","Nitrogen","Helium","Copper"],
    correctIndex: 3,
  },
  {
    id: "tri-en-77",
    category: "Science",
    text: "What is the symbol for Copper?",
    options: ["H","Ag","N","Cu"],
    correctIndex: 3,
  },
  {
    id: "tri-en-78",
    category: "Science",
    text: "Which element has the symbol Pb?",
    options: ["Lead","Sodium","Nitrogen","Copper"],
    correctIndex: 0,
  },
  {
    id: "tri-en-79",
    category: "Science",
    text: "What is the symbol for Lead?",
    options: ["Pb","O","Ag","Cu"],
    correctIndex: 0,
  },
  {
    id: "tri-en-80",
    category: "Science",
    text: "Which element has the symbol Hg?",
    options: ["Mercury","Sodium","Nitrogen","Oxygen"],
    correctIndex: 0,
  },
  {
    id: "tri-en-81",
    category: "Science",
    text: "What is the symbol for Mercury?",
    options: ["Hg","Au","Cu","C"],
    correctIndex: 0,
  },
  {
    id: "tri-en-82",
    category: "Sports",
    text: "How many players on a soccer team on the field?",
    options: ["10","11","9","12"],
    correctIndex: 1,
  },
  {
    id: "tri-en-83",
    category: "Sports",
    text: "How often are the Summer Olympics held?",
    options: ["Every 5 years","Every year","Every 4 years","Every 2 years"],
    correctIndex: 2,
  },
  {
    id: "tri-en-84",
    category: "Sports",
    text: "What does ice hockey use instead of a ball?",
    options: ["A ring","A puck","A disk","A stick only"],
    correctIndex: 1,
  },
  {
    id: "tri-en-85",
    category: "Sports",
    text: "Which sport is played at Wimbledon?",
    options: ["Squash","Tennis","Cricket","Golf"],
    correctIndex: 1,
  },
  {
    id: "tri-en-86",
    category: "Sports",
    text: "How long is a marathon (approx)?",
    options: ["50 km","21 km","10 km","42 km"],
    correctIndex: 3,
  },
  {
    id: "tri-en-87",
    category: "Geography",
    text: "What is the largest ocean?",
    options: ["Pacific","Indian","Atlantic","Arctic"],
    correctIndex: 0,
  },
  {
    id: "tri-en-88",
    category: "Geography",
    text: "What is the longest river often debated with Amazon?",
    options: ["Danube","Congo","Nile","Yangtze"],
    correctIndex: 2,
  },
  {
    id: "tri-en-89",
    category: "Geography",
    text: "What is the largest desert (hot)?",
    options: ["Kalahari","Sahara","Mojave","Gobi"],
    correctIndex: 1,
  },
  {
    id: "tri-en-90",
    category: "Geography",
    text: "Which country has the most people?",
    options: ["USA","China","Indonesia","India"],
    correctIndex: 3,
  },
  {
    id: "tri-en-91",
    category: "Nature",
    text: "What is the largest animal?",
    options: ["Shark","Elephant","Giraffe","Blue whale"],
    correctIndex: 3,
  },
  {
    id: "tri-en-92",
    category: "Nature",
    text: "Which animal is famous for changing color?",
    options: ["Chameleon","Gecko","Lizard","Iguana"],
    correctIndex: 0,
  },
  {
    id: "tri-en-93",
    category: "Nature",
    text: "What do koalas mainly eat?",
    options: ["Eucalyptus","Fish","Grass","Bamboo"],
    correctIndex: 0,
  },
  {
    id: "tri-en-94",
    category: "Nature",
    text: "How many legs does a spider have?",
    options: ["12","6","10","8"],
    correctIndex: 3,
  },
  {
    id: "tri-en-95",
    category: "Science",
    text: "Which planet is the Red Planet?",
    options: ["Mercury","Venus","Jupiter","Mars"],
    correctIndex: 3,
  },
  {
    id: "tri-en-96",
    category: "Science",
    text: "What is H2O?",
    options: ["Hydrogen","Oxygen","Water","Salt"],
    correctIndex: 2,
  },
  {
    id: "tri-en-97",
    category: "Science",
    text: "Which organ pumps blood?",
    options: ["Heart","Liver","Lung","Kidney"],
    correctIndex: 0,
  },
  {
    id: "tri-en-98",
    category: "History",
    text: "In which year did the Berlin Wall fall?",
    options: ["1991","1989","1987","1985"],
    correctIndex: 1,
  },
  {
    id: "tri-en-99",
    category: "History",
    text: "In which year did Apollo 11 land on the Moon?",
    options: ["1965","1961","1972","1969"],
    correctIndex: 3,
  },
  {
    id: "tri-en-100",
    category: "History",
    text: "Who painted the Mona Lisa?",
    options: ["Leonardo da Vinci","Michelangelo","Raphael","Donatello"],
    correctIndex: 0,
  },
  {
    id: "tri-en-101",
    category: "Music",
    text: "Which band made Bohemian Rhapsody?",
    options: ["ABBA","Queen","Led Zeppelin","The Beatles"],
    correctIndex: 1,
  },
  {
    id: "tri-en-102",
    category: "Pop Culture",
    text: "What color is Pikachu?",
    options: ["Red","Yellow","Blue","Green"],
    correctIndex: 1,
  },
  {
    id: "tri-en-103",
    category: "Pop Culture",
    text: "What is Mario's brother called?",
    options: ["Wario","Toad","Luigi","Yoshi"],
    correctIndex: 2,
  },
  {
    id: "tri-en-104",
    category: "Pop Culture",
    text: "What school does Harry Potter attend?",
    options: ["Durmstrang","Hogwarts","Beauxbatons","Ilvermorny"],
    correctIndex: 1,
  },
  {
    id: "tri-en-105",
    category: "History",
    text: "Which year is associated with Apollo 11?",
    options: ["1989","1776","1492","1969"],
    correctIndex: 3,
  },
  {
    id: "tri-en-106",
    category: "History",
    text: "Which year is associated with the Berlin Wall?",
    options: ["1945","1776","1989","1492"],
    correctIndex: 2,
  },
  {
    id: "tri-en-107",
    category: "History",
    text: "Which year is associated with Columbus voyage?",
    options: ["1776","1961","2001","1492"],
    correctIndex: 3,
  },
  {
    id: "tri-en-108",
    category: "History",
    text: "Which year is associated with US independence?",
    options: ["1776","2007","1903","1945"],
    correctIndex: 0,
  },
  {
    id: "tri-en-109",
    category: "History",
    text: "Which year is associated with WWI start?",
    options: ["2007","1914","1903","1977"],
    correctIndex: 1,
  },
  {
    id: "tri-en-110",
    category: "History",
    text: "Which year is associated with WWII start?",
    options: ["1939","1945","2007","1961"],
    correctIndex: 0,
  },
  {
    id: "tri-en-111",
    category: "History",
    text: "Which year is associated with WWII end Europe?",
    options: ["1945","2007","1989","1961"],
    correctIndex: 0,
  },
  {
    id: "tri-en-112",
    category: "History",
    text: "Which year is associated with 9/11?",
    options: ["1492","2001","1776","1961"],
    correctIndex: 1,
  },
  {
    id: "tri-en-113",
    category: "History",
    text: "Which year is associated with first iPhone?",
    options: ["2007","1939","1969","1492"],
    correctIndex: 0,
  },
  {
    id: "tri-en-114",
    category: "History",
    text: "Which year is associated with Star Wars?",
    options: ["2001","1969","1977","1939"],
    correctIndex: 2,
  },
  {
    id: "tri-en-115",
    category: "History",
    text: "Which year is associated with Gagarin in space?",
    options: ["1969","1945","1961","1989"],
    correctIndex: 2,
  },
  {
    id: "tri-en-116",
    category: "History",
    text: "Which year is associated with first flight?",
    options: ["1492","1989","1903","2007"],
    correctIndex: 2,
  },
  {
    id: "tri-en-117",
    category: "Geography",
    text: "On which continent is Sweden?",
    options: ["Oceania","Asia","North America","Europe"],
    correctIndex: 3,
  },
  {
    id: "tri-en-118",
    category: "Geography",
    text: "On which continent is Egypt?",
    options: ["Oceania","South America","Africa","Antarctica"],
    correctIndex: 2,
  },
  {
    id: "tri-en-119",
    category: "Geography",
    text: "On which continent is Brazil?",
    options: ["South America","Africa","Asia","Antarctica"],
    correctIndex: 0,
  },
  {
    id: "tri-en-120",
    category: "Geography",
    text: "On which continent is Canada?",
    options: ["North America","Antarctica","Oceania","South America"],
    correctIndex: 0,
  },
  {
    id: "tri-en-121",
    category: "Geography",
    text: "On which continent is China?",
    options: ["Europe","Oceania","Asia","Antarctica"],
    correctIndex: 2,
  },
  {
    id: "tri-en-122",
    category: "Geography",
    text: "On which continent is Australia?",
    options: ["Oceania","Europe","Asia","North America"],
    correctIndex: 0,
  },
  {
    id: "tri-en-123",
    category: "Geography",
    text: "On which continent is Nigeria?",
    options: ["North America","Africa","Oceania","South America"],
    correctIndex: 1,
  },
  {
    id: "tri-en-124",
    category: "Geography",
    text: "On which continent is Japan?",
    options: ["South America","Asia","Oceania","Africa"],
    correctIndex: 1,
  },
  {
    id: "tri-en-125",
    category: "Geography",
    text: "On which continent is Argentina?",
    options: ["Antarctica","South America","Africa","North America"],
    correctIndex: 1,
  },
  {
    id: "tri-en-126",
    category: "Geography",
    text: "On which continent is France?",
    options: ["Europe","South America","Oceania","Antarctica"],
    correctIndex: 0,
  },
  {
    id: "tri-en-127",
    category: "Geography",
    text: "On which continent is Mexico?",
    options: ["Africa","Asia","North America","Antarctica"],
    correctIndex: 2,
  },
  {
    id: "tri-en-128",
    category: "Geography",
    text: "On which continent is New Zealand?",
    options: ["Antarctica","North America","Oceania","South America"],
    correctIndex: 2,
  },
]
