import type { Question } from './types.js'

export const TP_SV_QUESTIONS: Question[] = [
  {
    id: "tp-sv-s1",
    category: "Historia",
    text: "Vilket år blev Sverige medlem i EU?",
    options: ["1995","1989","2001","1973"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s2",
    category: "Historia",
    text: "Vad hette Sveriges kung under merparten av 1900-talets slut?",
    options: ["Carl XVI Gustaf","Gustav V","Oscar II","Karl XIV Johan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s3",
    category: "Geografi",
    text: "Vilken är Sveriges största sjö?",
    options: ["Vänern","Vättern","Mälaren","Hjälmaren"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s4",
    category: "Geografi",
    text: "Vilken är Sveriges längsta flod?",
    options: ["Klarälven–Göta älv","Dalälven","Umeälven","Luleälven"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s5",
    category: "Geografi",
    text: "I vilket landskap ligger Kiruna?",
    options: ["Lappland","Norrbotten","Västerbotten","Jämtland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s6",
    category: "Kultur",
    text: "Vad kallas Sveriges nationaldag?",
    options: ["6 juni","1 maj","24 juni","13 december"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s7",
    category: "Kultur",
    text: "Vilken dag firas Lucia i Sverige?",
    options: ["13 december","24 december","6 januari","1 november"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s8",
    category: "Litteratur",
    text: "Vem skrev Pippi Långstrump?",
    options: ["Astrid Lindgren","Selma Lagerlöf","Maria Gripe","Elsa Beskow"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s9",
    category: "Litteratur",
    text: "Vem skrev Nils Holgerssons underbara resa?",
    options: ["Selma Lagerlöf","Astrid Lindgren","August Strindberg","Vilhelm Moberg"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s10",
    category: "Litteratur",
    text: "Vem skrev Röda rummet?",
    options: ["August Strindberg","Hjalmar Söderberg","Selma Lagerlöf","Gustaf Fröding"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s11",
    category: "Musik",
    text: "Vilket svenskt band vann Eurovision 1974?",
    options: ["ABBA","Ace of Base","Roxette","Europe"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s13",
    category: "Sport",
    text: "Vilken sport är Björn Borg mest känd för?",
    options: ["Tennis","Golf","Ishockey","Fotboll"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s14",
    category: "Sport",
    text: "Vilken sport är Ingemar Stenmark mest känd för?",
    options: ["Alpin skidåkning","Längdskidor","Backhoppning","Ishockey"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s15",
    category: "Sport",
    text: "I vilken sport blev Zlatan Ibrahimović världsstjärna?",
    options: ["Fotboll","Basket","Handboll","Ishockey"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s16",
    category: "Historia",
    text: "Vad hette Sveriges första kvinnliga statsminister?",
    options: ["Magdalena Andersson","Anna Lindh","Mona Sahlin","Margot Wallström"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s17",
    category: "Geografi",
    text: "Vilken stad är Sveriges näst största?",
    options: ["Göteborg","Malmö","Uppsala","Linköping"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s18",
    category: "Kultur",
    text: "Vad är en typisk svensk midsommarrätt bland dessa?",
    options: ["Sill och färskpotatis","Tacos","Sushi","Pizza"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s19",
    category: "Vetenskap",
    text: "Vad upptäckte Alfred Nobel som gjort honom berömd (utöver priset)?",
    options: ["Dynamiten","Penicillinet","Telefonen","Ångmaskinen"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s20",
    category: "Historia",
    text: "I vilken stad delas Nobelpriset i fred ut?",
    options: ["Oslo","Stockholm","Göteborg","Köpenhamn"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s21",
    category: "Film & TV",
    text: "Vilken svensk regissör står bakom Fanny och Alexander?",
    options: ["Ingmar Bergman","Lasse Hallström","Ruben Östlund","Roy Andersson"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s22",
    category: "Film & TV",
    text: "Vilken film av Ruben Östlund vann Guldpalmen 2017?",
    options: ["The Square","Force Majeure","Triangle of Sadness","Turist"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s23",
    category: "Geografi",
    text: "Vilket hav ligger väster om Sverige?",
    options: ["Nordsjön/Skagerrak–Kattegatt","Östersjön","Barents hav","Svarta havet"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s24",
    category: "Historia",
    text: "Vad kallas perioden när Sverige var stormakt på 1600-talet?",
    options: ["Stormaktstiden","Vikingatiden","Frihetstiden","Vasatiden"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-s25",
    category: "Kultur",
    text: "Vilken färg har den svenska flaggan förutom blått?",
    options: ["Gult","Rött","Vitt","Grönt"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-1",
    category: "Geografi",
    text: "Vad är huvudstaden i Sverige?",
    options: ["Stockholm","Pretoria","Seoul","Teheran"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-2",
    category: "Geografi",
    text: "Vilket land har huvudstaden Stockholm?",
    options: ["Sverige","Tyskland","Ukraina","Malaysia"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-3",
    category: "Geografi",
    text: "Vad är huvudstaden i Norge?",
    options: ["Oslo","Washington, D.C.","Paris","Riyadh"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-4",
    category: "Geografi",
    text: "Vilket land har huvudstaden Oslo?",
    options: ["Norge","Kuba","Peru","Irland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-5",
    category: "Geografi",
    text: "Vad är huvudstaden i Danmark?",
    options: ["Köpenhamn","Amsterdam","Nairobi","London"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-6",
    category: "Geografi",
    text: "Vilket land har huvudstaden Köpenhamn?",
    options: ["Danmark","Irak","Schweiz","Singapore"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-7",
    category: "Geografi",
    text: "Vad är huvudstaden i Finland?",
    options: ["Helsingfors","Sofia","Tokyo","Jakarta"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-8",
    category: "Geografi",
    text: "Vilket land har huvudstaden Helsingfors?",
    options: ["Finland","Grekland","Kroatien","Indien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-9",
    category: "Geografi",
    text: "Vad är huvudstaden i Island?",
    options: ["Reykjavik","Köpenhamn","Kuala Lumpur","London"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-10",
    category: "Geografi",
    text: "Vilket land har huvudstaden Reykjavik?",
    options: ["Island","Rumänien","Ukraina","Bulgarien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-11",
    category: "Geografi",
    text: "Vad är huvudstaden i Frankrike?",
    options: ["Paris","Islamabad","Amsterdam","Havanna"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-12",
    category: "Geografi",
    text: "Vilket land har huvudstaden Paris?",
    options: ["Frankrike","Bangladesh","Grekland","Kuba"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-13",
    category: "Geografi",
    text: "Vad är huvudstaden i Tyskland?",
    options: ["Berlin","Sofia","Belgrad","Peking"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-14",
    category: "Geografi",
    text: "Vilket land har huvudstaden Berlin?",
    options: ["Tyskland","Iran","Ryssland","Israel"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-15",
    category: "Geografi",
    text: "Vad är huvudstaden i Italien?",
    options: ["Rom","Wien","Reykjavik","New Delhi"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-16",
    category: "Geografi",
    text: "Vilket land har huvudstaden Rom?",
    options: ["Italien","Marocko","Kanada","Danmark"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-17",
    category: "Geografi",
    text: "Vad är huvudstaden i Spanien?",
    options: ["Madrid","Rom","Seoul","Wellington"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-18",
    category: "Geografi",
    text: "Vilket land har huvudstaden Madrid?",
    options: ["Spanien","Colombia","Ryssland","Thailand"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-19",
    category: "Geografi",
    text: "Vad är huvudstaden i Portugal?",
    options: ["Lissabon","Hanoi","Aten","Kiev"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-20",
    category: "Geografi",
    text: "Vilket land har huvudstaden Lissabon?",
    options: ["Portugal","Turkiet","Chile","Israel"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-21",
    category: "Geografi",
    text: "Vad är huvudstaden i Grekland?",
    options: ["Aten","Brasília","Kuala Lumpur","Moskva"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-22",
    category: "Geografi",
    text: "Vilket land har huvudstaden Aten?",
    options: ["Grekland","Spanien","Vietnam","USA"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-23",
    category: "Geografi",
    text: "Vad är huvudstaden i Polen?",
    options: ["Warszawa","Reykjavik","Singapore","Seoul"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-24",
    category: "Geografi",
    text: "Vilket land har huvudstaden Warszawa?",
    options: ["Polen","Frankrike","Portugal","Finland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-25",
    category: "Geografi",
    text: "Vad är huvudstaden i Tjeckien?",
    options: ["Prag","Kiev","Brasília","Oslo"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-26",
    category: "Geografi",
    text: "Vilket land har huvudstaden Prag?",
    options: ["Tjeckien","Turkiet","Thailand","Irak"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-27",
    category: "Geografi",
    text: "Vad är huvudstaden i Österrike?",
    options: ["Wien","Havanna","Belgrad","Singapore"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-28",
    category: "Geografi",
    text: "Vilket land har huvudstaden Wien?",
    options: ["Österrike","Danmark","Kanada","Kenya"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-29",
    category: "Geografi",
    text: "Vad är huvudstaden i Schweiz?",
    options: ["Bern","Sofia","Santiago","Wien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-30",
    category: "Geografi",
    text: "Vilket land har huvudstaden Bern?",
    options: ["Schweiz","Vietnam","Brasilien","Jamaica"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-31",
    category: "Geografi",
    text: "Vad är huvudstaden i Belgien?",
    options: ["Bryssel","Seoul","Reykjavik","Dhaka"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-32",
    category: "Geografi",
    text: "Vilket land har huvudstaden Bryssel?",
    options: ["Belgien","Chile","Sydafrika","Malaysia"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-33",
    category: "Geografi",
    text: "Vad är huvudstaden i Nederländerna?",
    options: ["Amsterdam","Helsingfors","Kairo","Kiev"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-34",
    category: "Geografi",
    text: "Vilket land har huvudstaden Amsterdam?",
    options: ["Nederländerna","Nya Zeeland","Nigeria","Österrike"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-35",
    category: "Geografi",
    text: "Vad är huvudstaden i Irland?",
    options: ["Dublin","Pretoria","Santiago","Budapest"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-36",
    category: "Geografi",
    text: "Vilket land har huvudstaden Dublin?",
    options: ["Irland","Australien","Polen","Danmark"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-37",
    category: "Geografi",
    text: "Vad är huvudstaden i Storbritannien?",
    options: ["London","Rabat","Singapore","Stockholm"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-38",
    category: "Geografi",
    text: "Vilket land har huvudstaden London?",
    options: ["Storbritannien","Kina","Peru","Schweiz"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-39",
    category: "Geografi",
    text: "Vad är huvudstaden i Ungern?",
    options: ["Budapest","Wien","Seoul","Wellington"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-40",
    category: "Geografi",
    text: "Vilket land har huvudstaden Budapest?",
    options: ["Ungern","Schweiz","Grekland","Serbien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-41",
    category: "Geografi",
    text: "Vad är huvudstaden i Rumänien?",
    options: ["Bukarest","Lima","Madrid","Brasília"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-42",
    category: "Geografi",
    text: "Vilket land har huvudstaden Bukarest?",
    options: ["Rumänien","Marocko","Spanien","Nederländerna"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-43",
    category: "Geografi",
    text: "Vad är huvudstaden i Bulgarien?",
    options: ["Sofia","Prag","Moskva","Warszawa"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-44",
    category: "Geografi",
    text: "Vilket land har huvudstaden Sofia?",
    options: ["Bulgarien","Japan","Ryssland","Peru"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-45",
    category: "Geografi",
    text: "Vad är huvudstaden i Kroatien?",
    options: ["Zagreb","Bukarest","Lissabon","Manila"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-46",
    category: "Geografi",
    text: "Vilket land har huvudstaden Zagreb?",
    options: ["Kroatien","Österrike","Ryssland","Ukraina"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-47",
    category: "Geografi",
    text: "Vad är huvudstaden i Serbien?",
    options: ["Belgrad","Dublin","Bryssel","Manila"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-48",
    category: "Geografi",
    text: "Vilket land har huvudstaden Belgrad?",
    options: ["Serbien","Nya Zeeland","Schweiz","Vietnam"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-49",
    category: "Geografi",
    text: "Vad är huvudstaden i Ukraina?",
    options: ["Kiev","Singapore","London","Tokyo"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-50",
    category: "Geografi",
    text: "Vilket land har huvudstaden Kiev?",
    options: ["Ukraina","Serbien","Irland","Japan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-51",
    category: "Geografi",
    text: "Vad är huvudstaden i Turkiet?",
    options: ["Ankara","Ottawa","Jakarta","Teheran"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-52",
    category: "Geografi",
    text: "Vilket land har huvudstaden Ankara?",
    options: ["Turkiet","Schweiz","Iran","Tjeckien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-53",
    category: "Geografi",
    text: "Vad är huvudstaden i Ryssland?",
    options: ["Moskva","Brasília","Helsingfors","Riyadh"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-54",
    category: "Geografi",
    text: "Vilket land har huvudstaden Moskva?",
    options: ["Ryssland","Serbien","Vietnam","Egypten"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-55",
    category: "Geografi",
    text: "Vad är huvudstaden i Japan?",
    options: ["Tokyo","Nairobi","Buenos Aires","Berlin"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-56",
    category: "Geografi",
    text: "Vilket land har huvudstaden Tokyo?",
    options: ["Japan","Italien","Marocko","Österrike"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-57",
    category: "Geografi",
    text: "Vad är huvudstaden i Kina?",
    options: ["Peking","Paris","Zagreb","Kairo"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-58",
    category: "Geografi",
    text: "Vilket land har huvudstaden Peking?",
    options: ["Kina","Singapore","Bulgarien","Brasilien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-59",
    category: "Geografi",
    text: "Vad är huvudstaden i Sydkorea?",
    options: ["Seoul","Bern","Buenos Aires","Köpenhamn"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-60",
    category: "Geografi",
    text: "Vilket land har huvudstaden Seoul?",
    options: ["Sydkorea","Sydafrika","Serbien","Israel"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-61",
    category: "Geografi",
    text: "Vad är huvudstaden i Indien?",
    options: ["New Delhi","Mexico City","Jakarta","Kuala Lumpur"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-62",
    category: "Geografi",
    text: "Vilket land har huvudstaden New Delhi?",
    options: ["Indien","Portugal","Sydkorea","Schweiz"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-63",
    category: "Geografi",
    text: "Vad är huvudstaden i Thailand?",
    options: ["Bangkok","Warszawa","Ottawa","Bogotá"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-64",
    category: "Geografi",
    text: "Vilket land har huvudstaden Bangkok?",
    options: ["Thailand","Nederländerna","Mexiko","Turkiet"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-65",
    category: "Geografi",
    text: "Vad är huvudstaden i Vietnam?",
    options: ["Hanoi","Lima","Paris","New Delhi"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-66",
    category: "Geografi",
    text: "Vilket land har huvudstaden Hanoi?",
    options: ["Vietnam","Island","Tjeckien","Filippinerna"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-67",
    category: "Geografi",
    text: "Vad är huvudstaden i Indonesien?",
    options: ["Jakarta","Belgrad","Jerusalem","Brasília"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-68",
    category: "Geografi",
    text: "Vilket land har huvudstaden Jakarta?",
    options: ["Indonesien","Kanada","Marocko","Portugal"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-69",
    category: "Geografi",
    text: "Vad är huvudstaden i Australien?",
    options: ["Canberra","Oslo","Prag","Hanoi"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-70",
    category: "Geografi",
    text: "Vilket land har huvudstaden Canberra?",
    options: ["Australien","USA","Island","Jamaica"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-71",
    category: "Geografi",
    text: "Vad är huvudstaden i Nya Zeeland?",
    options: ["Wellington","Pretoria","Lissabon","Kingston"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-72",
    category: "Geografi",
    text: "Vilket land har huvudstaden Wellington?",
    options: ["Nya Zeeland","Japan","Indonesien","Egypten"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-73",
    category: "Geografi",
    text: "Vad är huvudstaden i Kanada?",
    options: ["Ottawa","Peking","Kairo","Rom"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-74",
    category: "Geografi",
    text: "Vilket land har huvudstaden Ottawa?",
    options: ["Kanada","Malaysia","Indonesien","Irak"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-75",
    category: "Geografi",
    text: "Vad är huvudstaden i USA?",
    options: ["Washington, D.C.","Bern","Bogotá","Kairo"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-76",
    category: "Geografi",
    text: "Vilket land har huvudstaden Washington, D.C.?",
    options: ["USA","Thailand","Pakistan","Danmark"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-77",
    category: "Geografi",
    text: "Vad är huvudstaden i Mexiko?",
    options: ["Mexico City","Moskva","Washington, D.C.","Bangkok"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-78",
    category: "Geografi",
    text: "Vilket land har huvudstaden Mexico City?",
    options: ["Mexiko","Australien","Argentina","Saudiarabien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-79",
    category: "Geografi",
    text: "Vad är huvudstaden i Brasilien?",
    options: ["Brasília","Manila","New Delhi","Jakarta"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-80",
    category: "Geografi",
    text: "Vilket land har huvudstaden Brasília?",
    options: ["Brasilien","Österrike","Belgien","Filippinerna"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-81",
    category: "Geografi",
    text: "Vad är huvudstaden i Argentina?",
    options: ["Buenos Aires","Havanna","Kuala Lumpur","Rom"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-82",
    category: "Geografi",
    text: "Vilket land har huvudstaden Buenos Aires?",
    options: ["Argentina","Indonesien","Iran","Island"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-83",
    category: "Geografi",
    text: "Vad är huvudstaden i Chile?",
    options: ["Santiago","Paris","Wellington","Aten"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-84",
    category: "Geografi",
    text: "Vilket land har huvudstaden Santiago?",
    options: ["Chile","Singapore","Nigeria","Irland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-85",
    category: "Geografi",
    text: "Vad är huvudstaden i Peru?",
    options: ["Lima","Kuala Lumpur","Tokyo","Paris"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-86",
    category: "Geografi",
    text: "Vilket land har huvudstaden Lima?",
    options: ["Peru","Bulgarien","Iran","Chile"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-87",
    category: "Geografi",
    text: "Vad är huvudstaden i Colombia?",
    options: ["Bogotá","Helsingfors","Wien","Mexico City"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-88",
    category: "Geografi",
    text: "Vilket land har huvudstaden Bogotá?",
    options: ["Colombia","Sverige","Japan","Kuba"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-89",
    category: "Geografi",
    text: "Vad är huvudstaden i Egypten?",
    options: ["Kairo","Zagreb","Helsingfors","Oslo"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-90",
    category: "Geografi",
    text: "Vilket land har huvudstaden Kairo?",
    options: ["Egypten","Australien","Spanien","Norge"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-91",
    category: "Geografi",
    text: "Vad är huvudstaden i Sydafrika?",
    options: ["Pretoria","Lissabon","Peking","Stockholm"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-92",
    category: "Geografi",
    text: "Vilket land har huvudstaden Pretoria?",
    options: ["Sydafrika","Frankrike","Ungern","Jamaica"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-93",
    category: "Geografi",
    text: "Vad är huvudstaden i Kenya?",
    options: ["Nairobi","Moskva","Paris","Singapore"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-94",
    category: "Geografi",
    text: "Vilket land har huvudstaden Nairobi?",
    options: ["Kenya","Frankrike","Iran","Polen"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-95",
    category: "Geografi",
    text: "Vad är huvudstaden i Marocko?",
    options: ["Rabat","Helsingfors","Jakarta","Kiev"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-96",
    category: "Geografi",
    text: "Vilket land har huvudstaden Rabat?",
    options: ["Marocko","Irak","Rumänien","Grekland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-97",
    category: "Geografi",
    text: "Vad är huvudstaden i Nigeria?",
    options: ["Abuja","Wellington","Kiev","Singapore"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-98",
    category: "Geografi",
    text: "Vilket land har huvudstaden Abuja?",
    options: ["Nigeria","Kuba","Singapore","Island"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-99",
    category: "Geografi",
    text: "Vad är huvudstaden i Saudiarabien?",
    options: ["Riyadh","Moskva","Buenos Aires","Abuja"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-100",
    category: "Geografi",
    text: "Vilket land har huvudstaden Riyadh?",
    options: ["Saudiarabien","Kanada","Singapore","Schweiz"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-101",
    category: "Geografi",
    text: "Vad är huvudstaden i Israel?",
    options: ["Jerusalem","Berlin","Islamabad","Warszawa"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-102",
    category: "Geografi",
    text: "Vilket land har huvudstaden Jerusalem?",
    options: ["Israel","Pakistan","Filippinerna","Chile"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-103",
    category: "Geografi",
    text: "Vad är huvudstaden i Iran?",
    options: ["Teheran","Belgrad","Stockholm","Kiev"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-104",
    category: "Geografi",
    text: "Vilket land har huvudstaden Teheran?",
    options: ["Iran","Schweiz","Thailand","Island"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-105",
    category: "Geografi",
    text: "Vad är huvudstaden i Irak?",
    options: ["Bagdad","Lima","Kiev","Wien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-106",
    category: "Geografi",
    text: "Vilket land har huvudstaden Bagdad?",
    options: ["Irak","Norge","Tjeckien","Sydkorea"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-107",
    category: "Geografi",
    text: "Vad är huvudstaden i Pakistan?",
    options: ["Islamabad","Brasília","Teheran","Peking"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-108",
    category: "Geografi",
    text: "Vilket land har huvudstaden Islamabad?",
    options: ["Pakistan","Vietnam","Sverige","Bulgarien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-109",
    category: "Geografi",
    text: "Vad är huvudstaden i Bangladesh?",
    options: ["Dhaka","Sofia","Bryssel","Abuja"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-110",
    category: "Geografi",
    text: "Vilket land har huvudstaden Dhaka?",
    options: ["Bangladesh","Australien","Israel","Pakistan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-111",
    category: "Geografi",
    text: "Vad är huvudstaden i Filippinerna?",
    options: ["Manila","Wellington","Brasília","Ankara"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-112",
    category: "Geografi",
    text: "Vilket land har huvudstaden Manila?",
    options: ["Filippinerna","Thailand","Pakistan","Italien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-113",
    category: "Geografi",
    text: "Vad är huvudstaden i Malaysia?",
    options: ["Kuala Lumpur","Brasília","Lima","Berlin"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-114",
    category: "Geografi",
    text: "Vilket land har huvudstaden Kuala Lumpur?",
    options: ["Malaysia","Saudiarabien","Tyskland","Sydkorea"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-115",
    category: "Geografi",
    text: "Vad är huvudstaden i Singapore?",
    options: ["Singapore","Santiago","Amsterdam","Rom"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-116",
    category: "Geografi",
    text: "Vilket land har huvudstaden Singapore?",
    options: ["Singapore","Danmark","Bangladesh","Brasilien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-117",
    category: "Geografi",
    text: "Vad är huvudstaden i Kuba?",
    options: ["Havanna","Buenos Aires","Bogotá","Kairo"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-118",
    category: "Geografi",
    text: "Vilket land har huvudstaden Havanna?",
    options: ["Kuba","Grekland","Japan","Storbritannien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-cap-119",
    category: "Geografi",
    text: "Vad är huvudstaden i Jamaica?",
    options: ["Kingston","Ankara","Rom","Helsingfors"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-land-120",
    category: "Geografi",
    text: "Vilket land har huvudstaden Kingston?",
    options: ["Jamaica","Sydkorea","Saudiarabien","Tyskland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-121",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Nilén?",
    options: ["Egypten","Frankrike","Europa","Europa"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-122",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Amazonfloden?",
    options: ["Brasilien","Kina","Egypten","Storbritannien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-123",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Yangtze?",
    options: ["Kina","Egypten","Ryssland","USA"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-124",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Mississippifloden?",
    options: ["USA","Brasilien","Kina","Egypten"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-125",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Donau?",
    options: ["Europa","Brasilien","USA","Storbritannien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-126",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Rhen?",
    options: ["Europa","USA","Ryssland","Kina"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-127",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Themsen?",
    options: ["Storbritannien","Brasilien","Kina","Egypten"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-128",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Seine?",
    options: ["Frankrike","Ryssland","Egypten","USA"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-129",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Ganges?",
    options: ["Indien","Europa","USA","Frankrike"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-riv-130",
    category: "Geografi",
    text: "I vilket land/område förknippas främst floden Volga?",
    options: ["Ryssland","Europa","Kina","Indien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mtn-131",
    category: "Geografi",
    text: "Var ligger berget Mount Everest?",
    options: ["Nepal/Kina","Pakistan/Kina","Frankrike/Italien","Argentina"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mtn-132",
    category: "Geografi",
    text: "Var ligger berget K2?",
    options: ["Pakistan/Kina","Argentina","Nepal/Kina","USA"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mtn-133",
    category: "Geografi",
    text: "Var ligger berget Kilimanjaro?",
    options: ["Tanzania","Ryssland","Argentina","Pakistan/Kina"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mtn-134",
    category: "Geografi",
    text: "Var ligger berget Mont Blanc?",
    options: ["Frankrike/Italien","Pakistan/Kina","Ryssland","Schweiz/Italien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mtn-135",
    category: "Geografi",
    text: "Var ligger berget Matterhorn?",
    options: ["Schweiz/Italien","USA","Frankrike/Italien","Nepal/Kina"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mtn-136",
    category: "Geografi",
    text: "Var ligger berget Denali?",
    options: ["USA","Pakistan/Kina","Frankrike/Italien","Schweiz/Italien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mtn-137",
    category: "Geografi",
    text: "Var ligger berget Aconcagua?",
    options: ["Argentina","Nepal/Kina","Frankrike/Italien","Ryssland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mtn-138",
    category: "Geografi",
    text: "Var ligger berget Elbrus?",
    options: ["Ryssland","Nepal/Kina","Argentina","Schweiz/Italien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-139",
    category: "Historia",
    text: "Vem förknippas mest med telefonen?",
    options: ["Alexander Graham Bell","Thomas Edison","Charles Darwin","Edward Jenner"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-140",
    category: "Historia",
    text: "Vem förknippas mest med glödlampan (praktisk)?",
    options: ["Thomas Edison","Alexander Fleming","Dmitrij Mendelejev","Charles Darwin"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-141",
    category: "Historia",
    text: "Vem förknippas mest med boktryckarkonsten i Europa?",
    options: ["Johannes Gutenberg","Dmitrij Mendelejev","Charles Darwin","Albert Einstein"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-142",
    category: "Vetenskap",
    text: "Vem förknippas mest med penicillin?",
    options: ["Alexander Fleming","Tim Berners-Lee","Alexander Graham Bell","Edward Jenner"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-143",
    category: "Vetenskap",
    text: "Vem förknippas mest med relativitetsteorin?",
    options: ["Albert Einstein","Johannes Gutenberg","Thomas Edison","Charles Darwin"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-144",
    category: "Historia",
    text: "Vem förknippas mest med världens första vaccin (koppor)?",
    options: ["Edward Jenner","Dmitrij Mendelejev","Marie Curie","Albert Einstein"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-145",
    category: "Vetenskap",
    text: "Vem förknippas mest med periodiska systemet?",
    options: ["Dmitrij Mendelejev","Johannes Gutenberg","Charles Darwin","Alexander Graham Bell"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-146",
    category: "Vetenskap",
    text: "Vem förknippas mest med radioaktivitet (namnet)?",
    options: ["Marie Curie","Charles Darwin","Albert Einstein","Thomas Edison"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-147",
    category: "Vetenskap",
    text: "Vem förknippas mest med evolution genom naturligt urval?",
    options: ["Charles Darwin","Alexander Graham Bell","Johannes Gutenberg","Edward Jenner"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-inv-148",
    category: "Teknik",
    text: "Vem förknippas mest med WWW (World Wide Web)?",
    options: ["Tim Berners-Lee","Dmitrij Mendelejev","Johannes Gutenberg","Alexander Graham Bell"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-149",
    category: "Historia",
    text: "Vilket år Berlinmuren föll?",
    options: ["1989","1995","2020","1957"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-150",
    category: "Historia",
    text: "Vilket år människan landade på månen?",
    options: ["1969","2007","1995","1957"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-151",
    category: "Historia",
    text: "Vilket år första världskriget började?",
    options: ["1914","1492","2007","1989"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-152",
    category: "Historia",
    text: "Vilket år andra världskriget slutade i Europa?",
    options: ["1945","2007","1961","1789"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-153",
    category: "Historia",
    text: "Vilket år Titanic förliste?",
    options: ["1912","1957","1914","1969"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-154",
    category: "Historia",
    text: "Vilket år EU:s föregångare EEC bildades (Romfördraget)?",
    options: ["1957","1912","1492","1914"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-155",
    category: "Historia",
    text: "Vilket år Sverige gick med i EU?",
    options: ["1995","1776","1914","1961"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-156",
    category: "Historia",
    text: "Vilket år Berlinmuren byggdes?",
    options: ["1961","1995","1776","1989"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-157",
    category: "Historia",
    text: "Vilket år USA:s självständighetsförklaring?",
    options: ["1776","1492","1957","1969"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-158",
    category: "Historia",
    text: "Vilket år franska revolutionen började?",
    options: ["1789","1912","1945","1957"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-159",
    category: "Historia",
    text: "Vilket år Columbus nådde Amerika?",
    options: ["1492","1912","2007","1776"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-yr-160",
    category: "Teknik",
    text: "Vilket år första iPhone lanserades?",
    options: ["2007","1789","1995","1957"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-205",
    category: "Sport",
    text: "Vilken sport förknippas främst med Wimbledon?",
    options: ["tennis","ishockey","flera sporter","basket"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-206",
    category: "Sport",
    text: "Vilken sport förknippas främst med Tour de France?",
    options: ["cykling","amerikansk fotboll","fotboll","längdskidor"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-207",
    category: "Sport",
    text: "Vilken sport förknippas främst med Super Bowl?",
    options: ["amerikansk fotboll","fotboll","ishockey","golf"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-208",
    category: "Sport",
    text: "Vilken sport förknippas främst med Stanley Cup?",
    options: ["ishockey","basket","tennis","amerikansk fotboll"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-209",
    category: "Sport",
    text: "Vilken sport förknippas främst med Champions League?",
    options: ["fotboll","flera sporter","golf","basket"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-210",
    category: "Sport",
    text: "Vilken sport förknippas främst med Olympiska spelen?",
    options: ["flera sporter","amerikansk fotboll","fotboll","tennis"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-211",
    category: "Sport",
    text: "Vilken sport förknippas främst med FIFA World Cup?",
    options: ["fotboll","golf","längdskidor","basket"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-212",
    category: "Sport",
    text: "Vilken sport förknippas främst med NBA-finalerna?",
    options: ["basket","fotboll","tennis","ishockey"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-213",
    category: "Sport",
    text: "Vilken sport förknippas främst med PGA Championship?",
    options: ["golf","ishockey","cykling","basket"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-spo-214",
    category: "Sport",
    text: "Vilken sport förknippas främst med Tour de Ski?",
    options: ["längdskidor","fotboll","fotboll","amerikansk fotboll"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-215",
    category: "Vetenskap",
    text: "Vad är kemiskt tecken för guld?",
    options: ["Au","Ag","Fe","Pb"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-216",
    category: "Vetenskap",
    text: "Vad är kemiskt tecken för järn?",
    options: ["Fe","Ir","Au","Na"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-217",
    category: "Vetenskap",
    text: "Vad är kemiskt tecken för natrium?",
    options: ["Na","N","S","Ne"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-218",
    category: "Vetenskap",
    text: "Vad är kemiskt tecken för syre?",
    options: ["O","Ox","Oy","Or"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-219",
    category: "Vetenskap",
    text: "Vad är kemiskt tecken för kol?",
    options: ["C","Co","Ca","K"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-220",
    category: "Vetenskap",
    text: "Vad är kemiskt tecken för silver?",
    options: ["Ag","Si","Sv","Au"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-221",
    category: "Vetenskap",
    text: "Vad är kemiskt tecken för kvicksilver?",
    options: ["Hg","Q","Kv","Me"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-222",
    category: "Vetenskap",
    text: "Vad är planeten närmast solen?",
    options: ["Merkurius","Venus","Mars","Jorden"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-223",
    category: "Vetenskap",
    text: "Vad är största planeten i solsystemet?",
    options: ["Jupiter","Saturnus","Neptunus","Uranus"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-224",
    category: "Vetenskap",
    text: "Vad är planeten med tydliga ringar?",
    options: ["Saturnus","Jupiter","Uranus","Neptunus"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-225",
    category: "Vetenskap",
    text: "Vad är röd planet?",
    options: ["Mars","Venus","Merkurius","Jupiter"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-226",
    category: "Vetenskap",
    text: "Vad är ljusets ungefärliga hastighet i vakuum?",
    options: ["300 000 km/s","300 km/s","3 000 km/s","30 000 km/s"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-227",
    category: "Vetenskap",
    text: "Vad är vatten i kemisk formel?",
    options: ["H2O","CO2","O2","NaCl"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-228",
    category: "Vetenskap",
    text: "Vad är koldioxid i kemisk formel?",
    options: ["CO2","H2O","CO","C2O"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-229",
    category: "Vetenskap",
    text: "Vad är människans normala kroppstemperatur ungefär?",
    options: ["37°C","27°C","42°C","32°C"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-230",
    category: "Vetenskap",
    text: "Vad är DNA:s form beskrivs ofta som?",
    options: ["dubbelhelix","enkelspiral","kub","pyramid"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-231",
    category: "Vetenskap",
    text: "Vad är jordens kärna består främst av?",
    options: ["järn och nickel","guld och silver","vatten","kvarts"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-sci-232",
    category: "Vetenskap",
    text: "Vad är fotosyntes sker främst i?",
    options: ["växternas blad","rötter","blommor","frön"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-233",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med sushi?",
    options: ["Japan","Kanada","Spanien","Italien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-234",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med paella?",
    options: ["Spanien","Kanada","Japan","Korea"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-235",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med pizza (ursprung)?",
    options: ["Italien","Kanada","Spanien","Japan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-236",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med croissant (starkt förknippas med)?",
    options: ["Frankrike","Mellanöstern","Japan","Sverige"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-237",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med taco?",
    options: ["Mexiko","Italien","Kanada","Korea"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-238",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med kimchi?",
    options: ["Korea","Mellanöstern","Spanien","Sverige"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-239",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med falafel?",
    options: ["Mellanöstern","Korea","Kanada","Spanien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-240",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med fish and chips?",
    options: ["Storbritannien","Sverige","Korea","Japan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-241",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med surströmming?",
    options: ["Sverige","Japan","Mellanöstern","Spanien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-mat-242",
    category: "Mat & dryck",
    text: "Vilket land/område förknippas främst med poutine?",
    options: ["Kanada","Sverige","Frankrike","Korea"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-243",
    category: "Historia",
    text: "Vem var den första människan på månen?",
    options: ["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","John Glenn"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-244",
    category: "Historia",
    text: "Vem var den första människan i rymden?",
    options: ["Yuri Gagarin","Neil Armstrong","Alan Shepard","Valentina Tereshkova"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-245",
    category: "Historia",
    text: "Vilket imperium byggde Colosseum i Rom?",
    options: ["Romerska riket","Grekiska riket","Osmanska riket","Bysantinska riket"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-246",
    category: "Historia",
    text: "Vilken farao är mest känd för sin nästan orörda grav?",
    options: ["Tutankhamun","Ramses II","Kleopatra","Akhenaton"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-247",
    category: "Historia",
    text: "Vem var Storbritanniens premiärminister under större delen av andra världskriget?",
    options: ["Winston Churchill","Neville Chamberlain","Tony Blair","Margaret Thatcher"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-248",
    category: "Historia",
    text: "Vilket land leddes av Adolf Hitler?",
    options: ["Tyskland","Italien","Österrike","Spanien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-249",
    category: "Historia",
    text: "Vad hette det kinesiska kejsardynastin som byggde stora delar av Kinesiska muren?",
    options: ["Qin","Han","Tang","Ming"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-250",
    category: "Geografi",
    text: "Vilken är världens största ö (om man räknar Grönland)?",
    options: ["Grönland","Madagaskar","Borneo","Australien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-251",
    category: "Geografi",
    text: "Vilken kontinent är den minsta till ytan?",
    options: ["Oceanien/Australien","Europa","Antarktis","Sydamerika"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-252",
    category: "Geografi",
    text: "Vilket land har flest tidszoner?",
    options: ["Frankrike (inkl. territorier)","Ryssland","USA","Kina"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-253",
    category: "Geografi",
    text: "Vad heter öknen som täcker stora delar av Nordafrika?",
    options: ["Sahara","Gobi","Kalahari","Atacama"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-254",
    category: "Geografi",
    text: "Vilket hav ligger mellan Europa och Afrika?",
    options: ["Medelhavet","Svarta havet","Röda havet","Kaspiska havet"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-255",
    category: "Geografi",
    text: "Vilken stad är känd som Big Apple?",
    options: ["New York","Los Angeles","Chicago","Boston"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-256",
    category: "Geografi",
    text: "I vilket land ligger staden Marrakech?",
    options: ["Marocko","Egypten","Tunisien","Algeriet"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-257",
    category: "Vetenskap",
    text: "Hur många ben har en vuxen människa ungefär?",
    options: ["206","156","256","306"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-258",
    category: "Vetenskap",
    text: "Vilket organ pumpar blod i kroppen?",
    options: ["Hjärtat","Levern","Lungorna","Njurarna"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-259",
    category: "Vetenskap",
    text: "Vad kallas den största delen av den mänskliga hjärnan?",
    options: ["Storhjärnan (cerebrum)","Lillhjärnan","Hjärnstammen","Hypofysen"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-260",
    category: "Vetenskap",
    text: "Vilken gas andas växter främst in vid fotosyntes?",
    options: ["Koldioxid","Syre","Kväve","Väte"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-261",
    category: "Vetenskap",
    text: "Vad mäter en seismograf?",
    options: ["Jordbävningar","Vindhastighet","Lufttryck","Temperatur"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-262",
    category: "Vetenskap",
    text: "Vilket grundämne är diamant en form av?",
    options: ["Kol","Kisel","Kvarts","Kalcium"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-263",
    category: "Natur",
    text: "Vilket djur är störst på land?",
    options: ["Afrikansk elefant","Giraff","Noshörning","Flodhäst"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-264",
    category: "Natur",
    text: "Vilket djur är känt för att spela död när det känner sig hotat (opossum)?",
    options: ["Opossum","Igelkott","Skunk","Bältdjur"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-265",
    category: "Natur",
    text: "Vad äter en koala främst?",
    options: ["Eukalyptusblad","Bambu","Fisk","Insekter"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-266",
    category: "Natur",
    text: "Vad äter en panda främst?",
    options: ["Bambu","Eukalyptus","Fisk","Kött"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-267",
    category: "Natur",
    text: "Vilket däggdjur kan flyga?",
    options: ["Fladdermus","Flygekorre (glid)","Pingvin","Struts"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-268",
    category: "Sport",
    text: "Hur många spelare har ett fotbollslag på planen?",
    options: ["11","9","10","12"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-269",
    category: "Sport",
    text: "Hur många hål har en vanlig golfrunda?",
    options: ["18","9","12","21"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-270",
    category: "Sport",
    text: "I vilken sport använder man en puck?",
    options: ["Ishockey","Lacrosse","Bandysport","Curling"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-271",
    category: "Sport",
    text: "Var hölls de olympiska sommarspelen 2012?",
    options: ["London","Peking","Rio","Tokyo"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-272",
    category: "Sport",
    text: "Var hölls de olympiska sommarspelen 2016?",
    options: ["Rio de Janeiro","London","Tokyo","Aten"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-273",
    category: "Sport",
    text: "Vilket land vann fotbolls-VM 2018?",
    options: ["Frankrike","Kroatien","Brasilien","Tyskland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-274",
    category: "Sport",
    text: "Vilket land vann fotbolls-VM 2022?",
    options: ["Argentina","Frankrike","Brasilien","Spanien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-275",
    category: "Musik",
    text: "Hur många strängar har en vanlig gitarr?",
    options: ["6","4","5","7"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-276",
    category: "Musik",
    text: "Vilket instrument är Yo-Yo Ma mest känd för?",
    options: ["Cello","Violin","Piano","Flöjt"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-277",
    category: "Musik",
    text: "Vad kallas den högsta kvinnliga sångstämman?",
    options: ["Sopran","Alt","Tenor","Bas"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-278",
    category: "Film & TV",
    text: "Vilken skådespelare spelar Iron Man i MCU?",
    options: ["Robert Downey Jr.","Chris Evans","Chris Hemsworth","Mark Ruffalo"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-279",
    category: "Film & TV",
    text: "Vilken skådespelare spelar Jack Sparrow?",
    options: ["Johnny Depp","Orlando Bloom","Brad Pitt","Tom Cruise"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-280",
    category: "Film & TV",
    text: "I vilken stad utspelar sig Friends huvudsakligen?",
    options: ["New York","Los Angeles","Chicago","Boston"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-281",
    category: "Film & TV",
    text: "Vad heter den blå alien-rasen i Avatar?",
    options: ["Na’vi","Klingon","Ewok","Wookiee"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-282",
    category: "Litteratur",
    text: "Vem skrev Romeo och Julia?",
    options: ["William Shakespeare","Charles Dickens","Jane Austen","Mark Twain"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-283",
    category: "Litteratur",
    text: "Vilken detektiv skapades av Arthur Conan Doyle?",
    options: ["Sherlock Holmes","Hercule Poirot","Miss Marple","Sam Spade"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-284",
    category: "Litteratur",
    text: "Vem skrev Krönikor från Narnia?",
    options: ["C.S. Lewis","J.R.R. Tolkien","J.K. Rowling","Philip Pullman"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-285",
    category: "Kultur",
    text: "Vilken konstnär målade Mona Lisa?",
    options: ["Leonardo da Vinci","Michelangelo","Raphael","Rembrandt"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-286",
    category: "Kultur",
    text: "Vilken konstnär är känd för Guernica?",
    options: ["Pablo Picasso","Salvador Dalí","Vincent van Gogh","Claude Monet"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-287",
    category: "Kultur",
    text: "Vilken konstnär skar av en del av sitt öra?",
    options: ["Vincent van Gogh","Edvard Munch","Paul Gauguin","Henri Matisse"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-288",
    category: "Kultur",
    text: "Vad kallas den berömda skulpturen av Michelangelo med en ung man med slangbella?",
    options: ["David","Moses","Pietà","Tänkaren"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-289",
    category: "Teknik",
    text: "Vad betyder CPU?",
    options: ["Central Processing Unit","Computer Power Unit","Core Process Utility","Central Program Upload"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-290",
    category: "Teknik",
    text: "Vilket företag gjorde iPhone?",
    options: ["Apple","Samsung","Google","Microsoft"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-291",
    category: "Teknik",
    text: "Vad heter Googles mobiloperativsystem?",
    options: ["Android","iOS","Windows Phone","Symbian"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-292",
    category: "Teknik",
    text: "Vad betyder www i en webbadress?",
    options: ["World Wide Web","Web World Wide","Wide Web World","Wireless Web Window"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-293",
    category: "Mat & dryck",
    text: "Från vilken böna görs choklad?",
    options: ["Kakaobönan","Kaffebönan","Vaniljbönan","Sojabönan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-294",
    category: "Mat & dryck",
    text: "Vilket land är champagne skyddad ursprungsbeteckning för?",
    options: ["Frankrike","Italien","Spanien","Tyskland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-295",
    category: "Mat & dryck",
    text: "Vad är den huvudsakliga ingrediensen i hummus?",
    options: ["Kikärtor","Linser","Bönor","Ris"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-296",
    category: "Allmänt",
    text: "Hur många färger har en regnbåge traditionellt?",
    options: ["7","5","6","8"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-297",
    category: "Allmänt",
    text: "Vad kallas den längsta sidan i en rätvinklig triangel?",
    options: ["Hypotenusan","Katet","Diagonal","Bas"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-x-298",
    category: "Allmänt",
    text: "Vilket årtal inleder 2000-talet (århundradet)?",
    options: ["2001","2000","1999","2010"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-1",
    category: "Historia",
    text: "Vilket år startade trettioåriga kriget?",
    options: ["1618","1648","1523","1718"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-2",
    category: "Historia",
    text: "Vilket år slutade trettioåriga kriget?",
    options: ["1648","1618","1718","1814"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-3",
    category: "Historia",
    text: "Vem var Sveriges kung under stormaktstidens början (Gustav II Adolf)?",
    options: ["Gustav II Adolf","Karl XII","Gustav Vasa","Karl XIV Johan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-4",
    category: "Historia",
    text: "Vid vilket slag dog Gustav II Adolf 1632?",
    options: ["Lützen","Poltava","Narva","Breitenfeld"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-5",
    category: "Historia",
    text: "Vilket slag anses ha avslutat Sveriges stormaktstid 1709?",
    options: ["Poltava","Narva","Lützen","Leipzig"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-6",
    category: "Historia",
    text: "Vem grundade Stockholm enligt traditionen?",
    options: ["Birger jarl","Gustav Vasa","Olof Skötkonung","Engelbrekt"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-7",
    category: "Historia",
    text: "Vilket år anses Sverige ofta ha kristnats mer officiellt under Olof Skötkonung?",
    options: ["omkring år 1000","1523","1397","1809"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-8",
    category: "Historia",
    text: "Vad hette unionen mellan Danmark, Norge och Sverige på medeltiden?",
    options: ["Kalmarunionen","Hansan","NATO","EFTA"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-9",
    category: "Historia",
    text: "Vilket år blev Gustav Vasa kung och Sverige mer självständigt från Danmark?",
    options: ["1523","1397","1618","1809"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-10",
    category: "Historia",
    text: "Vad kallas den svenska författningen från 1809 som begränsade kungamakten?",
    options: ["1809 års regeringsform","1719 års författning","1974 års regeringsform","Magna Carta"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-11",
    category: "Historia",
    text: "Vilket år fick Sverige sin nuvarande regeringsform (huvudsakligen)?",
    options: ["1974","1809","1921","1995"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-12",
    category: "Historia",
    text: "När fick kvinnor rösträtt i Sverige (allmän och lika)?",
    options: ["1921","1909","1945","1971"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-13",
    category: "Historia",
    text: "Vilken svensk statsminister mördades 1986?",
    options: ["Olof Palme","Tage Erlander","Per Albin Hansson","Carl Bildt"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-14",
    category: "Historia",
    text: "Vilken utrikesminister mördades i Stockholm 2003?",
    options: ["Anna Lindh","Margot Wallström","Karin Söder","Birgitta Dahl"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-15",
    category: "Geografi",
    text: "Vilket är Sveriges nordligaste län?",
    options: ["Norrbotten","Västerbotten","Jämtland","Västernorrland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-16",
    category: "Geografi",
    text: "Vilken svensk ö är störst?",
    options: ["Gotland","Öland","Orust","Hisingen"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-17",
    category: "Geografi",
    text: "Vilken svensk ö ligger närmast Kalmar?",
    options: ["Öland","Gotland","Ven","Åland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-18",
    category: "Geografi",
    text: "Vilken stad ligger vid mynningen av Göta älv?",
    options: ["Göteborg","Malmö","Halmstad","Uddevalla"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-19",
    category: "Geografi",
    text: "I vilken stad ligger Turning Torso?",
    options: ["Malmö","Göteborg","Stockholm","Helsingborg"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-20",
    category: "Geografi",
    text: "Vad heter Sveriges högsta berg?",
    options: ["Kebnekaise","Sarek","Abisko","Åreskutan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-21",
    category: "Geografi",
    text: "Vilken nationalpark är Sveriges äldsta?",
    options: ["Sarek","Tyresta","Padjelanta","Stenshuvud"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-22",
    category: "Geografi",
    text: "Vilket land ligger öster om Östersjön mitt emot Mellansverige?",
    options: ["Finland","Norge","Danmark","Island"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-23",
    category: "Geografi",
    text: "Vilken flod rinner genom London?",
    options: ["Themsen","Seine","Rhen","Donau"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-24",
    category: "Geografi",
    text: "Vilken flod rinner genom Kairo?",
    options: ["Nilén","Eufrat","Tigris","Jordan"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-25",
    category: "Geografi",
    text: "Vilken stad är känd för kanalerna och gondolerna?",
    options: ["Venedig","Amsterdam","Brügge","Stockholm"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-26",
    category: "Geografi",
    text: "I vilket land ligger Machu Picchu?",
    options: ["Peru","Mexiko","Chile","Bolivia"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-27",
    category: "Geografi",
    text: "I vilket land ligger Taj Mahal?",
    options: ["Indien","Pakistan","Iran","Turkiet"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-28",
    category: "Geografi",
    text: "I vilket land ligger pyramider i Giza?",
    options: ["Egypten","Sudan","Libyen","Marocko"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-29",
    category: "Geografi",
    text: "Vilket land är känt för fjordar och fjäll i norr?",
    options: ["Norge","Danmark","Nederländerna","Belgien"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-30",
    category: "Vetenskap",
    text: "Vad kallas den kraft som håller oss kvar på jorden?",
    options: ["Gravitation","Magnetism","Friktion","Centrifugalkraft"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-31",
    category: "Vetenskap",
    text: "Vilket organ filtrerar blodet och bildar urin?",
    options: ["Njurarna","Levern","Mjälten","Bukspottkörteln"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-32",
    category: "Vetenskap",
    text: "Vad producerar bukspottkörteln som reglerar blodsocker?",
    options: ["Insulin","Adrenalin","Kortisol","Melatonin"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-33",
    category: "Vetenskap",
    text: "Vilken vitamin får kroppen främst från solljus?",
    options: ["D-vitamin","C-vitamin","B12","A-vitamin"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-34",
    category: "Vetenskap",
    text: "Vad kallas djur som äter både växter och kött?",
    options: ["Allätare","Växtätare","Köttätare","Asätare"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-35",
    category: "Vetenskap",
    text: "Hur många kromosomer har människan normalt?",
    options: ["46","23","48","44"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-36",
    category: "Vetenskap",
    text: "Vad kallas den minsta enheten i ett grundämne?",
    options: ["Atom","Molekyl","Cell","Proton"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-37",
    category: "Vetenskap",
    text: "Vilken partikel har negativ laddning?",
    options: ["Elektron","Proton","Neutron","Foton"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-38",
    category: "Vetenskap",
    text: "Vad mäter man i ampere?",
    options: ["Elektrisk ström","Spänning","Effekt","Resistans"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-39",
    category: "Vetenskap",
    text: "Vad mäter man i volt?",
    options: ["Elektrisk spänning","Ström","Effekt","Energi"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-40",
    category: "Natur",
    text: "Vilket djur är Sveriges nationaldjur?",
    options: ["Älg","Björn","Varg","Rådjur"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-41",
    category: "Natur",
    text: "Vilken fågel är Sveriges nationalfågel?",
    options: ["Koltrast","Bofink","Talgoxe","Örn"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-42",
    category: "Natur",
    text: "Vad kallas hanen hos ett rådjur?",
    options: ["Bock","Tjur","Hingst","Galt"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-43",
    category: "Natur",
    text: "Vilket träd är vanligt på svenska midsummerstänger?",
    options: ["Björk (löv)","Ek","Tall","Gran"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-44",
    category: "Natur",
    text: "Vad äter en myrslok främst?",
    options: ["Myror/termitter","Bär","Fisk","Gräs"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-45",
    category: "Natur",
    text: "Vilket havsdjur är känt för sin bläckskydd?",
    options: ["Bläckfisk","Haj","Delfin","Val"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-46",
    category: "Sport",
    text: "Hur många perioder har en ishockeymatch normalt?",
    options: ["3","2","4","5"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-47",
    category: "Sport",
    text: "Hur lång är en fotbollsmatch i ordinarie tid?",
    options: ["90 minuter","80","100","60"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-48",
    category: "Sport",
    text: "Vilket land vann ishockey-VM för herrar 2013?",
    options: ["Sverige","Kanada","Finland","Ryssland"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-49",
    category: "Sport",
    text: "I vilken sport tävlar man i slalom?",
    options: ["Alpin skidåkning","Längdskidor","Skidskytte","Backhoppning"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-50",
    category: "Sport",
    text: "Vad kallas poängställningen 40–40 i tennis?",
    options: ["Deuce (lika)","Advantage","Matchboll","Setboll"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-51",
    category: "Sport",
    text: "Hur många poäng ger en touchdown i amerikansk fotboll (utan extra)?",
    options: ["6","3","7","2"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-52",
    category: "Sport",
    text: "Varför har fotbollsmålvakter ofta en annan tröjfärg än laget?",
    options: ["För att skilja dem från utespelarna","För att de alltid är lagkapten","FIFA kräver gult","Det är bara tradition utan syfte"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-53",
    category: "Musik",
    text: "Vilket instrument har svarta och vita tangenter?",
    options: ["Piano","Gitarr","Trummor","Fiol"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-54",
    category: "Musik",
    text: "Vad kallas en grupp på fyra musiker?",
    options: ["Kvartett","Trio","Kvintett","Oktett"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-55",
    category: "Musik",
    text: "Vilken svensk duo är känd för \"It Must Have Been Love\"?",
    options: ["Roxette","ABBA","Ace of Base","Europe"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-56",
    category: "Musik",
    text: "Vilket band gjorde \"The Final Countdown\"?",
    options: ["Europe","ABBA","Roxette","Swedish House Mafia"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-57",
    category: "Musik",
    text: "Vad heter Aviciis riktiga förnamn?",
    options: ["Tim","Avicii","DJ","Eric"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-58",
    category: "Film & TV",
    text: "Vilken filmserie handlar om en pojke som överlever och går till trollkarlsskola?",
    options: ["Harry Potter","Narnia","Percy Jackson","Hunger Games"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-59",
    category: "Film & TV",
    text: "Vad heter den fiktiva afrikanska nationen i Black Panther?",
    options: ["Wakanda","Asgard","Gotham","Latveria"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-60",
    category: "Film & TV",
    text: "Vilken streamingjänst lanserade The Crown?",
    options: ["Netflix","Disney+","HBO","Amazon"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-61",
    category: "Film & TV",
    text: "Vad heter den gula familjen i The Simpsons?",
    options: ["Simpsons","Griffins","Smiths","Belocher"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-62",
    category: "Litteratur",
    text: "Vem skrev Bröderna Lejonhjärta?",
    options: ["Astrid Lindgren","Maria Gripe","Selma Lagerlöf","Elsa Beskow"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-63",
    category: "Litteratur",
    text: "Vem skrev Ronja Rövardotter?",
    options: ["Astrid Lindgren","Maria Gripe","Gunilla Bergström","Selma Lagerlöf"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-64",
    category: "Litteratur",
    text: "Vem skrev Emil i Lönneberga?",
    options: ["Astrid Lindgren","Selma Lagerlöf","Elsa Beskow","Sven Nordqvist"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-65",
    category: "Litteratur",
    text: "Vem skapade Pettson och Findus?",
    options: ["Sven Nordqvist","Astrid Lindgren","Gunilla Bergström","Jan Lööf"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-66",
    category: "Litteratur",
    text: "Vem skapade Alfons Åberg?",
    options: ["Gunilla Bergström","Astrid Lindgren","Sven Nordqvist","Elsa Beskow"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-67",
    category: "Kultur",
    text: "Vilken målare är känd för Stjärnenatt?",
    options: ["Vincent van Gogh","Claude Monet","Edvard Munch","Pablo Picasso"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-68",
    category: "Kultur",
    text: "Vilken målare är känd för Skriet?",
    options: ["Edvard Munch","Vincent van Gogh","Salvador Dalí","Gustav Klimt"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-69",
    category: "Kultur",
    text: "I vilket museum hänger Mona Lisa?",
    options: ["Louvre","Prado","Uffizi","MoMA"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-70",
    category: "Kultur",
    text: "Vad kallas japansk teckningsserie ofta?",
    options: ["Manga","Anime","Manhwa","Comic"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-71",
    category: "Teknik",
    text: "Vad betyder USB ungefär?",
    options: ["Universal Serial Bus","Ultra Speed Band","United System Bridge","User Soft Button"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-72",
    category: "Teknik",
    text: "Vilket företag äger Instagram?",
    options: ["Meta (Facebook)","Google","Amazon","Apple"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-73",
    category: "Teknik",
    text: "Vad heter Apples röstassistent?",
    options: ["Siri","Alexa","Cortana","Google Assistant"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-74",
    category: "Teknik",
    text: "Vad heter Amazons röstassistent?",
    options: ["Alexa","Siri","Cortana","Bixby"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-75",
    category: "Mat & dryck",
    text: "Vad är den huvudsakliga spannmålen i risotto?",
    options: ["Ris","Pasta","Couscous","Potatis"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-76",
    category: "Mat & dryck",
    text: "Från vilken växt görs te främst?",
    options: ["Teplantan (Camellia sinensis)","Kaffeplantan","Kakaoträdet","Mint"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-77",
    category: "Mat & dryck",
    text: "Vad kallas spanska aptitretare?",
    options: ["Tapas","Meze","Antipasti","Dim sum"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-78",
    category: "Mat & dryck",
    text: "Vilken ost är typisk för Grekland bland dessa?",
    options: ["Feta","Parmesan","Cheddar","Mozzarella"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-79",
    category: "Allmänt",
    text: "Hur många sekunder har en minut?",
    options: ["60","100","30","90"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-80",
    category: "Allmänt",
    text: "Hur många dagar har ett skottår?",
    options: ["366","365","364","367"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-81",
    category: "Allmänt",
    text: "Vad heter den tredje planeten från solen?",
    options: ["Jorden","Mars","Venus","Merkurius"],
    correctIndex: 0,
  },
  {
    id: "tp-sv-more-82",
    category: "Allmänt",
    text: "Vilket språk har flest modersmålstalare i världen ungefär?",
    options: ["Mandarin-kinesiska","Engelska","Spanska","Hindi"],
    correctIndex: 0,
  },
]
