import type { Question } from './types.js'

export const TP_EN_QUESTIONS: Question[] = [
  {
    id: "tp-en-cap-1",
    category: "Geography",
    text: "What is the capital of Sweden?",
    options: ["Stockholm","Moscow","Ottawa","Bern"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-2",
    category: "Geography",
    text: "Which country has the capital Stockholm?",
    options: ["Sweden","United Kingdom","Netherlands","Jamaica"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-3",
    category: "Geography",
    text: "What is the capital of Norway?",
    options: ["Oslo","Berlin","London","Athens"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-4",
    category: "Geography",
    text: "Which country has the capital Oslo?",
    options: ["Norway","Japan","Portugal","Indonesia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-5",
    category: "Geography",
    text: "What is the capital of Denmark?",
    options: ["Copenhagen","Athens","Bucharest","Kingston"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-6",
    category: "Geography",
    text: "Which country has the capital Copenhagen?",
    options: ["Denmark","Serbia","Greece","Argentina"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-7",
    category: "Geography",
    text: "What is the capital of Finland?",
    options: ["Helsinki","Copenhagen","Beijing","Stockholm"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-8",
    category: "Geography",
    text: "Which country has the capital Helsinki?",
    options: ["Finland","Portugal","Russia","Turkey"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-9",
    category: "Geography",
    text: "What is the capital of Iceland?",
    options: ["Reykjavik","Oslo","Berlin","Havana"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-10",
    category: "Geography",
    text: "Which country has the capital Reykjavik?",
    options: ["Iceland","Poland","Sweden","South Korea"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-11",
    category: "Geography",
    text: "What is the capital of France?",
    options: ["Paris","Ottawa","Islamabad","Tokyo"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-12",
    category: "Geography",
    text: "Which country has the capital Paris?",
    options: ["France","Thailand","South Africa","Sweden"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-13",
    category: "Geography",
    text: "What is the capital of Germany?",
    options: ["Berlin","Stockholm","Beijing","Baghdad"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-14",
    category: "Geography",
    text: "Which country has the capital Berlin?",
    options: ["Germany","Sweden","Denmark","Colombia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-15",
    category: "Geography",
    text: "What is the capital of Italy?",
    options: ["Rom","Tokyo","New Delhi","Vienna"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-16",
    category: "Geography",
    text: "Which country has the capital Rom?",
    options: ["Italy","Switzerland","Philippines","Iceland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-17",
    category: "Geography",
    text: "What is the capital of Spain?",
    options: ["Madrid","Riyadh","Rabat","Warsaw"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-18",
    category: "Geography",
    text: "Which country has the capital Madrid?",
    options: ["Spain","Greece","Finland","Kenya"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-19",
    category: "Geography",
    text: "What is the capital of Portugal?",
    options: ["Lisbon","Ankara","Bogotá","Zagreb"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-20",
    category: "Geography",
    text: "Which country has the capital Lisbon?",
    options: ["Portugal","Austria","Jamaica","United Kingdom"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-21",
    category: "Geography",
    text: "What is the capital of Greece?",
    options: ["Athens","Singapore","Budapest","Dublin"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-22",
    category: "Geography",
    text: "Which country has the capital Athens?",
    options: ["Greece","Colombia","Netherlands","USA"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-23",
    category: "Geography",
    text: "What is the capital of Poland?",
    options: ["Warsaw","Dublin","Pretoria","Singapore"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-24",
    category: "Geography",
    text: "Which country has the capital Warsaw?",
    options: ["Poland","Switzerland","India","Bangladesh"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-25",
    category: "Geography",
    text: "What is the capital of Czech Republic?",
    options: ["Prague","Washington, D.C.","Bucharest","Vienna"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-26",
    category: "Geography",
    text: "Which country has the capital Prague?",
    options: ["Czech Republic","Peru","Serbia","Belgium"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-27",
    category: "Geography",
    text: "What is the capital of Austria?",
    options: ["Vienna","Moscow","Helsinki","Lisbon"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-28",
    category: "Geography",
    text: "Which country has the capital Vienna?",
    options: ["Austria","Peru","Vietnam","Bulgaria"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-29",
    category: "Geography",
    text: "What is the capital of Switzerland?",
    options: ["Bern","Zagreb","Berlin","Amsterdam"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-30",
    category: "Geography",
    text: "Which country has the capital Bern?",
    options: ["Switzerland","Iraq","Egypt","Ireland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-31",
    category: "Geography",
    text: "What is the capital of Belgium?",
    options: ["Brussels","Vienna","Moscow","Seoul"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-32",
    category: "Geography",
    text: "Which country has the capital Brussels?",
    options: ["Belgium","Pakistan","Finland","France"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-33",
    category: "Geography",
    text: "What is the capital of Netherlands?",
    options: ["Amsterdam","New Delhi","Islamabad","Bogotá"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-34",
    category: "Geography",
    text: "Which country has the capital Amsterdam?",
    options: ["Netherlands","Saudi Arabia","Thailand","Mexico"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-35",
    category: "Geography",
    text: "What is the capital of Ireland?",
    options: ["Dublin","Cairo","Sofia","Budapest"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-36",
    category: "Geography",
    text: "Which country has the capital Dublin?",
    options: ["Ireland","Indonesia","Canada","New Zealand"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-37",
    category: "Geography",
    text: "What is the capital of United Kingdom?",
    options: ["London","Havana","Madrid","Buenos Aires"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-38",
    category: "Geography",
    text: "Which country has the capital London?",
    options: ["United Kingdom","Bangladesh","Germany","Belgium"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-39",
    category: "Geography",
    text: "What is the capital of Hungary?",
    options: ["Budapest","Abuja","Kingston","Belgrade"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-40",
    category: "Geography",
    text: "Which country has the capital Budapest?",
    options: ["Hungary","Chile","Israel","Saudi Arabia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-41",
    category: "Geography",
    text: "What is the capital of Romania?",
    options: ["Bucharest","Berlin","Budapest","Dublin"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-42",
    category: "Geography",
    text: "Which country has the capital Bucharest?",
    options: ["Romania","Cuba","Russia","Serbia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-43",
    category: "Geography",
    text: "What is the capital of Bulgaria?",
    options: ["Sofia","Manila","Reykjavik","Dublin"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-44",
    category: "Geography",
    text: "Which country has the capital Sofia?",
    options: ["Bulgaria","Hungary","Morocco","Sweden"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-45",
    category: "Geography",
    text: "What is the capital of Croatia?",
    options: ["Zagreb","Singapore","Warsaw","Budapest"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-46",
    category: "Geography",
    text: "Which country has the capital Zagreb?",
    options: ["Croatia","Kenya","Mexico","Iceland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-47",
    category: "Geography",
    text: "What is the capital of Serbia?",
    options: ["Belgrade","Oslo","Canberra","Beijing"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-48",
    category: "Geography",
    text: "Which country has the capital Belgrade?",
    options: ["Serbia","Egypt","Morocco","Iran"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-49",
    category: "Geography",
    text: "What is the capital of Ukraine?",
    options: ["Kyiv","Budapest","Lisbon","Lima"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-50",
    category: "Geography",
    text: "Which country has the capital Kyiv?",
    options: ["Ukraine","Finland","Malaysia","Italy"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-51",
    category: "Geography",
    text: "What is the capital of Turkey?",
    options: ["Ankara","Kuala Lumpur","Singapore","Paris"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-52",
    category: "Geography",
    text: "Which country has the capital Ankara?",
    options: ["Turkey","Mexico","Singapore","Spain"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-53",
    category: "Geography",
    text: "What is the capital of Russia?",
    options: ["Moscow","Manila","Rom","Havana"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-54",
    category: "Geography",
    text: "Which country has the capital Moscow?",
    options: ["Russia","Indonesia","Israel","Singapore"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-55",
    category: "Geography",
    text: "What is the capital of Japan?",
    options: ["Tokyo","Oslo","Ottawa","Beijing"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-56",
    category: "Geography",
    text: "Which country has the capital Tokyo?",
    options: ["Japan","Vietnam","Pakistan","Iraq"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-57",
    category: "Geography",
    text: "What is the capital of China?",
    options: ["Beijing","Berlin","Madrid","Vienna"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-58",
    category: "Geography",
    text: "Which country has the capital Beijing?",
    options: ["China","Russia","Switzerland","France"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-59",
    category: "Geography",
    text: "What is the capital of South Korea?",
    options: ["Seoul","Bangkok","Ottawa","Riyadh"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-60",
    category: "Geography",
    text: "Which country has the capital Seoul?",
    options: ["South Korea","Canada","Japan","Switzerland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-61",
    category: "Geography",
    text: "What is the capital of India?",
    options: ["New Delhi","Kyiv","Bucharest","Helsinki"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-62",
    category: "Geography",
    text: "Which country has the capital New Delhi?",
    options: ["India","Morocco","Singapore","Iceland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-63",
    category: "Geography",
    text: "What is the capital of Thailand?",
    options: ["Bangkok","Amsterdam","Tehran","Athens"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-64",
    category: "Geography",
    text: "Which country has the capital Bangkok?",
    options: ["Thailand","South Korea","Singapore","Morocco"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-65",
    category: "Geography",
    text: "What is the capital of Vietnam?",
    options: ["Hanoi","Tehran","Wellington","Vienna"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-66",
    category: "Geography",
    text: "Which country has the capital Hanoi?",
    options: ["Vietnam","Greece","Switzerland","Hungary"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-67",
    category: "Geography",
    text: "What is the capital of Indonesia?",
    options: ["Jakarta","Athens","Warsaw","Abuja"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-68",
    category: "Geography",
    text: "Which country has the capital Jakarta?",
    options: ["Indonesia","Cuba","Brazil","Vietnam"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-69",
    category: "Geography",
    text: "What is the capital of Australia?",
    options: ["Canberra","Wellington","Berlin","Bern"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-70",
    category: "Geography",
    text: "Which country has the capital Canberra?",
    options: ["Australia","Argentina","Iraq","Croatia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-71",
    category: "Geography",
    text: "What is the capital of New Zealand?",
    options: ["Wellington","Nairobi","Havana","Prague"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-72",
    category: "Geography",
    text: "Which country has the capital Wellington?",
    options: ["New Zealand","Nigeria","Canada","Indonesia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-73",
    category: "Geography",
    text: "What is the capital of Canada?",
    options: ["Ottawa","Amsterdam","Manila","Ankara"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-74",
    category: "Geography",
    text: "Which country has the capital Ottawa?",
    options: ["Canada","Turkey","United Kingdom","Iceland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-75",
    category: "Geography",
    text: "What is the capital of USA?",
    options: ["Washington, D.C.","Jerusalem","Amsterdam","Sofia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-76",
    category: "Geography",
    text: "Which country has the capital Washington, D.C.?",
    options: ["USA","United Kingdom","Thailand","Bangladesh"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-77",
    category: "Geography",
    text: "What is the capital of Mexico?",
    options: ["Mexico City","Buenos Aires","Manila","Baghdad"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-78",
    category: "Geography",
    text: "Which country has the capital Mexico City?",
    options: ["Mexico","Russia","Saudi Arabia","Ukraine"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-79",
    category: "Geography",
    text: "What is the capital of Brazil?",
    options: ["Brasília","Dublin","Wellington","Madrid"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-80",
    category: "Geography",
    text: "Which country has the capital Brasília?",
    options: ["Brazil","United Kingdom","Japan","Switzerland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-81",
    category: "Geography",
    text: "What is the capital of Argentina?",
    options: ["Buenos Aires","Pretoria","Dublin","Tokyo"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-82",
    category: "Geography",
    text: "Which country has the capital Buenos Aires?",
    options: ["Argentina","Austria","Thailand","Russia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-83",
    category: "Geography",
    text: "What is the capital of Chile?",
    options: ["Santiago","Zagreb","New Delhi","Beijing"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-84",
    category: "Geography",
    text: "Which country has the capital Santiago?",
    options: ["Chile","Poland","Iran","Egypt"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-85",
    category: "Geography",
    text: "What is the capital of Peru?",
    options: ["Lima","Vienna","Athens","Ottawa"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-86",
    category: "Geography",
    text: "Which country has the capital Lima?",
    options: ["Peru","Vietnam","South Korea","Greece"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-87",
    category: "Geography",
    text: "What is the capital of Colombia?",
    options: ["Bogotá","Kingston","Abuja","Zagreb"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-88",
    category: "Geography",
    text: "Which country has the capital Bogotá?",
    options: ["Colombia","Turkey","Iceland","Argentina"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-89",
    category: "Geography",
    text: "What is the capital of Egypt?",
    options: ["Cairo","London","Baghdad","Brasília"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-90",
    category: "Geography",
    text: "Which country has the capital Cairo?",
    options: ["Egypt","Czech Republic","Colombia","Spain"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-91",
    category: "Geography",
    text: "What is the capital of South Africa?",
    options: ["Pretoria","Beijing","Manila","Rabat"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-92",
    category: "Geography",
    text: "Which country has the capital Pretoria?",
    options: ["South Africa","Israel","Czech Republic","Netherlands"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-93",
    category: "Geography",
    text: "What is the capital of Kenya?",
    options: ["Nairobi","Prague","Sofia","Amsterdam"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-94",
    category: "Geography",
    text: "Which country has the capital Nairobi?",
    options: ["Kenya","Philippines","Iceland","USA"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-95",
    category: "Geography",
    text: "What is the capital of Morocco?",
    options: ["Rabat","Kuala Lumpur","Tokyo","Singapore"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-96",
    category: "Geography",
    text: "Which country has the capital Rabat?",
    options: ["Morocco","Peru","Portugal","Russia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-97",
    category: "Geography",
    text: "What is the capital of Nigeria?",
    options: ["Abuja","Ottawa","Jakarta","Warsaw"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-98",
    category: "Geography",
    text: "Which country has the capital Abuja?",
    options: ["Nigeria","Netherlands","Switzerland","Iceland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-99",
    category: "Geography",
    text: "What is the capital of Saudi Arabia?",
    options: ["Riyadh","Stockholm","Tokyo","Lisbon"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-100",
    category: "Geography",
    text: "Which country has the capital Riyadh?",
    options: ["Saudi Arabia","South Africa","Malaysia","Australia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-101",
    category: "Geography",
    text: "What is the capital of Israel?",
    options: ["Jerusalem","Bucharest","Baghdad","Belgrade"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-102",
    category: "Geography",
    text: "Which country has the capital Jerusalem?",
    options: ["Israel","Ukraine","Russia","Egypt"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-103",
    category: "Geography",
    text: "What is the capital of Iran?",
    options: ["Tehran","Bangkok","Riyadh","Jakarta"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-104",
    category: "Geography",
    text: "Which country has the capital Tehran?",
    options: ["Iran","India","Japan","Turkey"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-105",
    category: "Geography",
    text: "What is the capital of Iraq?",
    options: ["Baghdad","Rabat","Berlin","Brasília"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-106",
    category: "Geography",
    text: "Which country has the capital Baghdad?",
    options: ["Iraq","Hungary","Cuba","USA"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-107",
    category: "Geography",
    text: "What is the capital of Pakistan?",
    options: ["Islamabad","Dhaka","Dublin","Wellington"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-108",
    category: "Geography",
    text: "Which country has the capital Islamabad?",
    options: ["Pakistan","Colombia","Spain","Austria"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-109",
    category: "Geography",
    text: "What is the capital of Bangladesh?",
    options: ["Dhaka","Abuja","Helsinki","Riyadh"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-110",
    category: "Geography",
    text: "Which country has the capital Dhaka?",
    options: ["Bangladesh","Israel","Thailand","Italy"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-111",
    category: "Geography",
    text: "What is the capital of Philippines?",
    options: ["Manila","Brasília","Zagreb","Budapest"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-112",
    category: "Geography",
    text: "Which country has the capital Manila?",
    options: ["Philippines","Peru","Jamaica","Pakistan"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-113",
    category: "Geography",
    text: "What is the capital of Malaysia?",
    options: ["Kuala Lumpur","Rom","Ankara","Bucharest"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-114",
    category: "Geography",
    text: "Which country has the capital Kuala Lumpur?",
    options: ["Malaysia","Spain","Pakistan","Ireland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-115",
    category: "Geography",
    text: "What is the capital of Singapore?",
    options: ["Singapore","Seoul","Rabat","Jakarta"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-116",
    category: "Geography",
    text: "Which country has the capital Singapore?",
    options: ["Singapore","China","Spain","Finland"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-117",
    category: "Geography",
    text: "What is the capital of Cuba?",
    options: ["Havana","Warsaw","Bern","Brussels"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-118",
    category: "Geography",
    text: "Which country has the capital Havana?",
    options: ["Cuba","Turkey","Singapore","Morocco"],
    correctIndex: 0,
  },
  {
    id: "tp-en-cap-119",
    category: "Geography",
    text: "What is the capital of Jamaica?",
    options: ["Kingston","Zagreb","London","Amsterdam"],
    correctIndex: 0,
  },
  {
    id: "tp-en-land-120",
    category: "Geography",
    text: "Which country has the capital Kingston?",
    options: ["Jamaica","Canada","Thailand","South Korea"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-121",
    category: "Science",
    text: "Who is most associated with the telephone?",
    options: ["Alexander Graham Bell","Albert Einstein","Thomas Edison","Tim Berners-Lee"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-122",
    category: "Science",
    text: "Who is most associated with the practical light bulb?",
    options: ["Thomas Edison","Charles Darwin","Edward Jenner","Dmitri Mendeleev"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-123",
    category: "Science",
    text: "Who is most associated with the European printing press?",
    options: ["Johannes Gutenberg","Edward Jenner","Alexander Graham Bell","Albert Einstein"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-124",
    category: "Science",
    text: "Who is most associated with penicillin?",
    options: ["Alexander Fleming","Dmitri Mendeleev","Johannes Gutenberg","Albert Einstein"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-125",
    category: "Science",
    text: "Who is most associated with the theory of relativity?",
    options: ["Albert Einstein","Alexander Graham Bell","Edward Jenner","Charles Darwin"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-126",
    category: "Science",
    text: "Who is most associated with the first smallpox vaccine?",
    options: ["Edward Jenner","Alexander Fleming","Alexander Graham Bell","Thomas Edison"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-127",
    category: "Science",
    text: "Who is most associated with the periodic table?",
    options: ["Dmitri Mendeleev","Edward Jenner","Alexander Graham Bell","Johannes Gutenberg"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-128",
    category: "Science",
    text: "Who is most associated with radioactivity (coining the term)?",
    options: ["Marie Curie","Dmitri Mendeleev","Alexander Graham Bell","Charles Darwin"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-129",
    category: "Science",
    text: "Who is most associated with evolution by natural selection?",
    options: ["Charles Darwin","Alexander Graham Bell","Dmitri Mendeleev","Tim Berners-Lee"],
    correctIndex: 0,
  },
  {
    id: "tp-en-inv-130",
    category: "Science",
    text: "Who is most associated with the World Wide Web?",
    options: ["Tim Berners-Lee","Charles Darwin","Thomas Edison","Alexander Fleming"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-131",
    category: "History",
    text: "In what year did the Berlin Wall fall?",
    options: ["1989","2007","1492","1912"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-132",
    category: "History",
    text: "In what year did humans first land on the Moon?",
    options: ["1969","1989","1914","2007"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-133",
    category: "History",
    text: "In what year did World War I begin?",
    options: ["1914","1989","1789","1776"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-134",
    category: "History",
    text: "In what year did World War II end in Europe?",
    options: ["1945","1969","1789","1492"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-135",
    category: "History",
    text: "In what year did the Titanic sink?",
    options: ["1912","1969","2012","1776"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-136",
    category: "History",
    text: "In what year was the U.S. Declaration of Independence signed?",
    options: ["1776","2012","1912","2007"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-137",
    category: "History",
    text: "In what year did the French Revolution begin?",
    options: ["1789","1969","2007","1492"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-138",
    category: "History",
    text: "In what year did Columbus reach the Americas?",
    options: ["1492","1776","1989","1969"],
    correctIndex: 0,
  },
  {
    id: "tp-en-yr-139",
    category: "History",
    text: "In what year was the first iPhone released?",
    options: ["2007","1912","1989","1776"],
    correctIndex: 0,
  },
  {
    id: "tp-en-spo-160",
    category: "Sports",
    text: "Which sport is Wimbledon mainly associated with?",
    options: ["tennis","football/soccer","basketball","cycling"],
    correctIndex: 0,
  },
  {
    id: "tp-en-spo-161",
    category: "Sports",
    text: "Which sport is Tour de France mainly associated with?",
    options: ["cycling","football/soccer","American football","ice hockey"],
    correctIndex: 0,
  },
  {
    id: "tp-en-spo-162",
    category: "Sports",
    text: "Which sport is Super Bowl mainly associated with?",
    options: ["American football","football/soccer","basketball","cycling"],
    correctIndex: 0,
  },
  {
    id: "tp-en-spo-163",
    category: "Sports",
    text: "Which sport is Stanley Cup mainly associated with?",
    options: ["ice hockey","football/soccer","football/soccer","basketball"],
    correctIndex: 0,
  },
  {
    id: "tp-en-spo-164",
    category: "Sports",
    text: "Which sport is UEFA Champions League mainly associated with?",
    options: ["football/soccer","basketball","cycling","American football"],
    correctIndex: 0,
  },
  {
    id: "tp-en-spo-165",
    category: "Sports",
    text: "Which sport is FIFA World Cup mainly associated with?",
    options: ["football/soccer","American football","tennis","basketball"],
    correctIndex: 0,
  },
  {
    id: "tp-en-spo-166",
    category: "Sports",
    text: "Which sport is NBA Finals mainly associated with?",
    options: ["basketball","American football","tennis","football/soccer"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-167",
    category: "Science",
    text: "What is the chemical symbol for gold?",
    options: ["Au","Ag","Fe","Pb"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-168",
    category: "Science",
    text: "What is the chemical symbol for iron?",
    options: ["Fe","Ir","Au","Na"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-169",
    category: "Science",
    text: "What is the chemical symbol for sodium?",
    options: ["Na","N","S","Ne"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-170",
    category: "Science",
    text: "What is the chemical symbol for oxygen?",
    options: ["O","Ox","Oy","Or"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-171",
    category: "Science",
    text: "What is the planet closest to the Sun?",
    options: ["Mercury","Venus","Mars","Earth"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-172",
    category: "Science",
    text: "What is the largest planet in the solar system?",
    options: ["Jupiter","Saturn","Neptune","Uranus"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-173",
    category: "Science",
    text: "What is the planet known for its rings?",
    options: ["Saturn","Jupiter","Uranus","Neptune"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-174",
    category: "Science",
    text: "What is the Red Planet?",
    options: ["Mars","Venus","Mercury","Jupiter"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-175",
    category: "Science",
    text: "What is the chemical formula for water?",
    options: ["H2O","CO2","O2","NaCl"],
    correctIndex: 0,
  },
  {
    id: "tp-en-sci-176",
    category: "Science",
    text: "What is DNA's shape, often described as a?",
    options: ["double helix","single spiral","cube","pyramid"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-177",
    category: "History",
    text: "Who was the first person on the Moon?",
    options: ["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","John Glenn"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-178",
    category: "History",
    text: "Who was the first human in space?",
    options: ["Yuri Gagarin","Neil Armstrong","Alan Shepard","Valentina Tereshkova"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-179",
    category: "History",
    text: "Which empire built the Colosseum in Rome?",
    options: ["The Roman Empire","Greek Empire","Ottoman Empire","Byzantine Empire"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-180",
    category: "History",
    text: "Which pharaoh is famous for a nearly intact tomb?",
    options: ["Tutankhamun","Ramses II","Cleopatra","Akhenaten"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-181",
    category: "History",
    text: "Who was UK Prime Minister for most of WWII?",
    options: ["Winston Churchill","Neville Chamberlain","Tony Blair","Margaret Thatcher"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-182",
    category: "Geography",
    text: "What is the largest desert in the world (hot desert)?",
    options: ["Sahara","Gobi","Kalahari","Atacama"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-183",
    category: "Geography",
    text: "Which sea lies between Europe and Africa?",
    options: ["Mediterranean Sea","Black Sea","Red Sea","Caspian Sea"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-184",
    category: "Geography",
    text: "Which city is nicknamed the Big Apple?",
    options: ["New York","Los Angeles","Chicago","Boston"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-185",
    category: "Science",
    text: "About how many bones does an adult human have?",
    options: ["206","156","256","306"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-186",
    category: "Science",
    text: "Which organ pumps blood through the body?",
    options: ["The heart","The liver","The lungs","The kidneys"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-187",
    category: "Science",
    text: "Diamond is a form of which element?",
    options: ["Carbon","Silicon","Quartz","Calcium"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-188",
    category: "Nature",
    text: "What is the largest land animal?",
    options: ["African elephant","Giraffe","Rhinoceros","Hippopotamus"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-189",
    category: "Nature",
    text: "What do koalas mainly eat?",
    options: ["Eucalyptus leaves","Bamboo","Fish","Insects"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-190",
    category: "Nature",
    text: "What do giant pandas mainly eat?",
    options: ["Bamboo","Eucalyptus","Fish","Meat"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-191",
    category: "Sports",
    text: "How many players does a football/soccer team have on the field?",
    options: ["11","9","10","12"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-192",
    category: "Sports",
    text: "How many holes are on a standard golf course round?",
    options: ["18","9","12","21"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-193",
    category: "Sports",
    text: "Which sport uses a puck?",
    options: ["Ice hockey","Lacrosse","Bandy","Curling"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-194",
    category: "Sports",
    text: "Which country won the 2018 FIFA World Cup?",
    options: ["France","Croatia","Brazil","Germany"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-195",
    category: "Sports",
    text: "Which country won the 2022 FIFA World Cup?",
    options: ["Argentina","France","Brazil","Spain"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-196",
    category: "Music",
    text: "How many strings does a standard guitar have?",
    options: ["6","4","5","7"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-197",
    category: "Movies & TV",
    text: "Who plays Iron Man in the MCU?",
    options: ["Robert Downey Jr.","Chris Evans","Chris Hemsworth","Mark Ruffalo"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-198",
    category: "Movies & TV",
    text: "Who plays Jack Sparrow?",
    options: ["Johnny Depp","Orlando Bloom","Brad Pitt","Tom Cruise"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-199",
    category: "Movies & TV",
    text: "In which city is Friends mainly set?",
    options: ["New York","Los Angeles","Chicago","Boston"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-200",
    category: "Literature",
    text: "Who wrote Romeo and Juliet?",
    options: ["William Shakespeare","Charles Dickens","Jane Austen","Mark Twain"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-201",
    category: "Literature",
    text: "Which detective was created by Arthur Conan Doyle?",
    options: ["Sherlock Holmes","Hercule Poirot","Miss Marple","Sam Spade"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-202",
    category: "Culture",
    text: "Who painted the Mona Lisa?",
    options: ["Leonardo da Vinci","Michelangelo","Raphael","Rembrandt"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-203",
    category: "Culture",
    text: "Who painted Guernica?",
    options: ["Pablo Picasso","Salvador Dalí","Vincent van Gogh","Claude Monet"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-204",
    category: "Culture",
    text: "Which artist famously cut off part of his ear?",
    options: ["Vincent van Gogh","Edvard Munch","Paul Gauguin","Henri Matisse"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-205",
    category: "Tech",
    text: "What does CPU stand for?",
    options: ["Central Processing Unit","Computer Power Unit","Core Process Utility","Central Program Upload"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-206",
    category: "Tech",
    text: "Which company made the iPhone?",
    options: ["Apple","Samsung","Google","Microsoft"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-207",
    category: "Tech",
    text: "What is Google’s mobile OS called?",
    options: ["Android","iOS","Windows Phone","Symbian"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-208",
    category: "Food",
    text: "Chocolate comes from which bean?",
    options: ["Cocoa bean","Coffee bean","Vanilla bean","Soybean"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-209",
    category: "Food",
    text: "Champagne is a protected name for wine from which country?",
    options: ["France","Italy","Spain","Germany"],
    correctIndex: 0,
  },
  {
    id: "tp-en-x-210",
    category: "General",
    text: "How many colors are traditionally in a rainbow?",
    options: ["7","5","6","8"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-1",
    category: "History",
    text: "In which year did the Thirty Years’ War begin?",
    options: ["1618","1648","1523","1718"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-2",
    category: "History",
    text: "In which year did the Thirty Years’ War end?",
    options: ["1648","1618","1718","1814"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-3",
    category: "History",
    text: "Who was the first President of the United States?",
    options: ["George Washington","Thomas Jefferson","Abraham Lincoln","John Adams"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-4",
    category: "History",
    text: "Who was known as the Maid of Orléans?",
    options: ["Joan of Arc","Marie Antoinette","Catherine the Great","Elizabeth I"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-5",
    category: "History",
    text: "Which wall divided Berlin during the Cold War?",
    options: ["The Berlin Wall","Hadrian’s Wall","Great Wall of China","Antonine Wall"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-6",
    category: "History",
    text: "Which ship sank in 1912 after hitting an iceberg?",
    options: ["Titanic","Lusitania","Britannic","Olympic"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-7",
    category: "Geography",
    text: "What is the longest river in the world (commonly cited)?",
    options: ["The Nile","Amazon","Yangtze","Mississippi"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-8",
    category: "Geography",
    text: "What is the largest ocean?",
    options: ["Pacific Ocean","Atlantic Ocean","Indian Ocean","Arctic Ocean"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-9",
    category: "Geography",
    text: "Which country has the most people?",
    options: ["India","China","USA","Indonesia"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-10",
    category: "Geography",
    text: "Which desert covers much of northern Africa?",
    options: ["Sahara","Gobi","Kalahari","Atacama"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-11",
    category: "Geography",
    text: "Which mountain is the highest above sea level?",
    options: ["Mount Everest","K2","Kangchenjunga","Lhotse"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-12",
    category: "Geography",
    text: "In which country is the Great Barrier Reef?",
    options: ["Australia","New Zealand","Indonesia","Philippines"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-13",
    category: "Science",
    text: "What force keeps us on Earth?",
    options: ["Gravity","Magnetism","Friction","Centrifugal force"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-14",
    category: "Science",
    text: "Which organ filters blood and produces urine?",
    options: ["Kidneys","Liver","Spleen","Pancreas"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-15",
    category: "Science",
    text: "Which vitamin do humans mainly get from sunlight?",
    options: ["Vitamin D","Vitamin C","Vitamin B12","Vitamin A"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-16",
    category: "Science",
    text: "How many chromosomes do humans normally have?",
    options: ["46","23","48","44"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-17",
    category: "Science",
    text: "Which particle has a negative charge?",
    options: ["Electron","Proton","Neutron","Photon"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-18",
    category: "Science",
    text: "What does an ampere measure?",
    options: ["Electric current","Voltage","Power","Resistance"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-19",
    category: "Nature",
    text: "What is the largest living land animal?",
    options: ["African elephant","Giraffe","White rhinoceros","Hippopotamus"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-20",
    category: "Sports",
    text: "How many players are on a basketball team on the court?",
    options: ["5","6","7","4"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-21",
    category: "Sports",
    text: "How long is a standard football/soccer match?",
    options: ["90 minutes","80","100","60"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-22",
    category: "Sports",
    text: "How many periods are in a standard ice hockey game?",
    options: ["3","2","4","5"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-23",
    category: "Music",
    text: "Which instrument has black and white keys?",
    options: ["Piano","Guitar","Drums","Violin"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-24",
    category: "Music",
    text: "How many strings does a standard violin have?",
    options: ["4","5","6","3"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-25",
    category: "Movies & TV",
    text: "Which movie franchise features a boy wizard?",
    options: ["Harry Potter","Narnia","Percy Jackson","Hunger Games"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-26",
    category: "Movies & TV",
    text: "What is the fictional nation in Black Panther?",
    options: ["Wakanda","Asgard","Gotham","Latveria"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-27",
    category: "Literature",
    text: "Who wrote The Odyssey?",
    options: ["Homer","Virgil","Sophocles","Plato"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-28",
    category: "Literature",
    text: "Who wrote The Iliad?",
    options: ["Homer","Virgil","Ovid","Herodotus"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-29",
    category: "Culture",
    text: "Who painted The Starry Night?",
    options: ["Vincent van Gogh","Claude Monet","Edvard Munch","Pablo Picasso"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-30",
    category: "Culture",
    text: "Who painted The Scream?",
    options: ["Edvard Munch","Vincent van Gogh","Salvador Dalí","Gustav Klimt"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-31",
    category: "Culture",
    text: "In which museum is the Mona Lisa displayed?",
    options: ["The Louvre","Prado","Uffizi","MoMA"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-32",
    category: "Tech",
    text: "What does USB stand for?",
    options: ["Universal Serial Bus","Ultra Speed Band","United System Bridge","User Soft Button"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-33",
    category: "Tech",
    text: "Which company owns Instagram?",
    options: ["Meta","Google","Amazon","Apple"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-34",
    category: "Tech",
    text: "What is Apple’s voice assistant called?",
    options: ["Siri","Alexa","Cortana","Google Assistant"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-35",
    category: "Food",
    text: "What grain is risotto mainly made from?",
    options: ["Rice","Pasta","Couscous","Potato"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-36",
    category: "Food",
    text: "What plant is tea mainly made from?",
    options: ["Camellia sinensis (tea plant)","Coffee plant","Cocoa tree","Mint"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-37",
    category: "General",
    text: "How many seconds are in a minute?",
    options: ["60","100","30","90"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-38",
    category: "General",
    text: "How many days are in a leap year?",
    options: ["366","365","364","367"],
    correctIndex: 0,
  },
  {
    id: "tp-en-more-39",
    category: "General",
    text: "Which planet is third from the Sun?",
    options: ["Earth","Mars","Venus","Mercury"],
    correctIndex: 0,
  },
]
