import type { Question } from './types.js'

export const EXTRA_QUESTIONS: Question[] = [
  {
    id: "geo-x1",
    category: "Geografi",
    text: "Vilket land har huvudstaden Canberra?",
    options: ["Nya Zeeland","Australien","Fiji","Papua Nya Guinea"],
    correctIndex: 1,
  },
  {
    id: "geo-x2",
    category: "Geografi",
    text: "Vilken är Finlands huvudstad?",
    options: ["Turku","Tammerfors","Helsingfors","Oulu"],
    correctIndex: 2,
  },
  {
    id: "geo-x3",
    category: "Geografi",
    text: "I vilket land ligger staden Marrakech?",
    options: ["Algeriet","Tunisien","Marocko","Egypten"],
    correctIndex: 2,
  },
  {
    id: "geo-x4",
    category: "Geografi",
    text: "Vilket hav ligger mellan Sverige och Finland?",
    options: ["Nordsjön","Östersjön","Atlanten","Barents hav"],
    correctIndex: 1,
  },
  {
    id: "geo-x5",
    category: "Geografi",
    text: "Vilket land är känt för tulpaner och vindkraftsverk i Holland-klichén?",
    options: ["Belgien","Nederländerna","Danmark","Tyskland"],
    correctIndex: 1,
  },
  {
    id: "geo-x6",
    category: "Geografi",
    text: "Vad heter den största staden i Brasilien?",
    options: ["Brasília","Rio de Janeiro","São Paulo","Salvador"],
    correctIndex: 2,
  },
  {
    id: "geo-x7",
    category: "Geografi",
    text: "I vilket land ligger Kilimanjaro?",
    options: ["Kenya","Tanzania","Uganda","Etiopien"],
    correctIndex: 1,
  },
  {
    id: "geo-x8",
    category: "Geografi",
    text: "Vilken är Danmarks huvudstad?",
    options: ["Aarhus","Odense","Köpenhamn","Aalborg"],
    correctIndex: 2,
  },
  {
    id: "geo-x9",
    category: "Geografi",
    text: "Vilket land har flaggan med en röd cirkel på vit botten?",
    options: ["Kina","Japan","Sydkorea","Turkiet"],
    correctIndex: 1,
  },
  {
    id: "geo-x10",
    category: "Geografi",
    text: "Vilken flod rinner genom London?",
    options: ["Seine","Rhen","Themsen","Donau"],
    correctIndex: 2,
  },
  {
    id: "geo-x11",
    category: "Geografi",
    text: "Vilket land ligger på Iberiska halvön tillsammans med Spanien?",
    options: ["Italien","Portugal","Grekland","Frankrike"],
    correctIndex: 1,
  },
  {
    id: "geo-x12",
    category: "Geografi",
    text: "Vad heter huvudstaden i Kanada?",
    options: ["Toronto","Vancouver","Ottawa","Montreal"],
    correctIndex: 2,
  },
  {
    id: "geo-x13",
    category: "Geografi",
    text: "Vilket är världens minsta land till ytan?",
    options: ["Monaco","Vatikanstaten","San Marino","Liechtenstein"],
    correctIndex: 1,
  },
  {
    id: "geo-x14",
    category: "Geografi",
    text: "I vilket land ligger staden Dubai?",
    options: ["Saudiarabien","Qatar","Förenade Arabemiraten","Kuwait"],
    correctIndex: 2,
  },
  {
    id: "geo-x15",
    category: "Geografi",
    text: "Vilken kontinent tillhör Egypten främst?",
    options: ["Asien","Afrika","Europa","Oceanien"],
    correctIndex: 1,
  },
  {
    id: "geo-x16",
    category: "Geografi",
    text: "Vad heter Sveriges näst största stad?",
    options: ["Malmö","Uppsala","Göteborg","Linköping"],
    correctIndex: 2,
  },
  {
    id: "geo-x17",
    category: "Geografi",
    text: "Vilket land har huvudstaden Reykjavik?",
    options: ["Grönland","Island","Färöarna","Norge"],
    correctIndex: 1,
  },
  {
    id: "geo-x18",
    category: "Geografi",
    text: "Vilken ögrupp tillhör Mallorca?",
    options: ["Kanarieöarna","Balearerna","Azorerna","Kap Verde"],
    correctIndex: 1,
  },
  {
    id: "geo-x19",
    category: "Geografi",
    text: "I vilket land ligger staden Prague (Prag)?",
    options: ["Polen","Ungern","Tjeckien","Österrike"],
    correctIndex: 2,
  },
  {
    id: "geo-x20",
    category: "Geografi",
    text: "Vilket land har flest öar i världen?",
    options: ["Indonesien","Filippinerna","Sverige","Kanada"],
    correctIndex: 2,
  },
  {
    id: "his-x1",
    category: "Historia",
    text: "Vilket år började andra världskriget?",
    options: ["1937","1939","1941","1945"],
    correctIndex: 1,
  },
  {
    id: "his-x2",
    category: "Historia",
    text: "Vem var drottning av England under den elisabetanska eran på 1500-talet?",
    options: ["Victoria","Elizabeth I","Mary I","Anne"],
    correctIndex: 1,
  },
  {
    id: "his-x3",
    category: "Historia",
    text: "Vilket imperium byggde Colosseum?",
    options: ["Grekiska","Romerska","Osmanska","Persiska"],
    correctIndex: 1,
  },
  {
    id: "his-x4",
    category: "Historia",
    text: "När blev Sverige en demokrati med allmän rösträtt (ungefär)?",
    options: ["1905","1919–1921","1945","1971"],
    correctIndex: 1,
  },
  {
    id: "his-x5",
    category: "Historia",
    text: "Vem skrev kommunistiska manifestet tillsammans med Engels?",
    options: ["Lenin","Marx","Stalin","Trotskij"],
    correctIndex: 1,
  },
  {
    id: "his-x6",
    category: "Historia",
    text: "Vilket år invigdes Eiffeltornet?",
    options: ["1789","1889","1918","1945"],
    correctIndex: 1,
  },
  {
    id: "his-x7",
    category: "Historia",
    text: "Vem var USA:s första president?",
    options: ["Jefferson","Washington","Lincoln","Adams"],
    correctIndex: 1,
  },
  {
    id: "his-x8",
    category: "Historia",
    text: "Vilken civilisation uppfann papperet först?",
    options: ["Egypten","Kina","Grekland","Indien"],
    correctIndex: 1,
  },
  {
    id: "his-x9",
    category: "Historia",
    text: "När slutade det kalla kriget ungefär?",
    options: ["1975","1989–1991","2001","1968"],
    correctIndex: 1,
  },
  {
    id: "his-x10",
    category: "Historia",
    text: "Vem var kejsare av Frankrike under tidigt 1800-tal?",
    options: ["Louis XVI","Napoleon","Charlemagne","Robespierre"],
    correctIndex: 1,
  },
  {
    id: "his-x11",
    category: "Historia",
    text: "Vilket år invaderade Tyskland Polen?",
    options: ["1938","1939","1940","1941"],
    correctIndex: 1,
  },
  {
    id: "his-x12",
    category: "Historia",
    text: "Vad hette skeppet som Titanic tillhörde (rederi)?",
    options: ["Cunard","White Star Line","Royal Navy","Hamburg America"],
    correctIndex: 1,
  },
  {
    id: "his-x13",
    category: "Historia",
    text: "Vem målade Mona Lisa?",
    options: ["Michelangelo","Leonardo da Vinci","Raphael","Botticelli"],
    correctIndex: 1,
  },
  {
    id: "his-x14",
    category: "Historia",
    text: "Vilket land koloniserade Indien under British Raj?",
    options: ["Frankrike","Storbritannien","Portugal","Nederländerna"],
    correctIndex: 1,
  },
  {
    id: "his-x15",
    category: "Historia",
    text: "När firades Sveriges 500-årsjubileum av Gustav Vasa ungefär?",
    options: ["1920","1923","1950","1971"],
    correctIndex: 1,
  },
  {
    id: "spo-x1",
    category: "Sport",
    text: "Hur många spelare har ett handbollslag på planen?",
    options: ["5","6","7","8"],
    correctIndex: 2,
  },
  {
    id: "spo-x2",
    category: "Sport",
    text: "I vilken sport används en shuttlecock?",
    options: ["Tennis","Badminton","Squash","Pingis"],
    correctIndex: 1,
  },
  {
    id: "spo-x3",
    category: "Sport",
    text: "Hur lång är en olympisk simbassäng?",
    options: ["25 m","50 m","100 m","33 m"],
    correctIndex: 1,
  },
  {
    id: "spo-x4",
    category: "Sport",
    text: "Vilket land har vunnit flest fotbolls-VM (herrar, historiskt)?",
    options: ["Tyskland","Brasilien","Italien","Argentina"],
    correctIndex: 1,
  },
  {
    id: "spo-x5",
    category: "Sport",
    text: "Vad heter Sveriges ishockeylandslag?",
    options: ["Blågult","Tre Kronor","Nordic Ice","Kronorna"],
    correctIndex: 1,
  },
  {
    id: "spo-x6",
    category: "Sport",
    text: "Hur många hål har en standard golfbana?",
    options: ["9","12","18","24"],
    correctIndex: 2,
  },
  {
    id: "spo-x7",
    category: "Sport",
    text: "I vilken stad ligger Wembley Stadium?",
    options: ["Manchester","London","Liverpool","Birmingham"],
    correctIndex: 1,
  },
  {
    id: "spo-x8",
    category: "Sport",
    text: "Vilken sport är Serena Williams känd för?",
    options: ["Golf","Tennis","Friidrott","Simning"],
    correctIndex: 1,
  },
  {
    id: "spo-x9",
    category: "Sport",
    text: "Hur många perioder har en ishockeymatch?",
    options: ["2","3","4","5"],
    correctIndex: 1,
  },
  {
    id: "spo-x10",
    category: "Sport",
    text: "Vad kallas en poäng i rugby?",
    options: ["Goal","Try","Touch","Score"],
    correctIndex: 1,
  },
  {
    id: "spo-x11",
    category: "Sport",
    text: "Vilket land arrangerade fotbolls-VM 2022?",
    options: ["Ryssland","Qatar","USA","Brasilien"],
    correctIndex: 1,
  },
  {
    id: "spo-x12",
    category: "Sport",
    text: "Hur många poäng ger en straffspark i fotboll om den går i?",
    options: ["1","2","3","0"],
    correctIndex: 0,
  },
  {
    id: "spo-x13",
    category: "Sport",
    text: "Vilken sport använder en \"birdie\"?",
    options: ["Tennis","Golf","Badminton","Bowling"],
    correctIndex: 1,
  },
  {
    id: "spo-x14",
    category: "Sport",
    text: "Hur lång är ett varv på en standard löparbana?",
    options: ["200 m","400 m","800 m","1000 m"],
    correctIndex: 1,
  },
  {
    id: "spo-x15",
    category: "Sport",
    text: "Vad heter Zlatans efternamn?",
    options: ["Ibrahimović","Persson","Larsson","Andersson"],
    correctIndex: 0,
  },
  {
    id: "fil-x1",
    category: "Film & TV",
    text: "Vem spelade Jack i Titanic?",
    options: ["Brad Pitt","Leonardo DiCaprio","Matt Damon","Johnny Depp"],
    correctIndex: 1,
  },
  {
    id: "fil-x2",
    category: "Film & TV",
    text: "Vilken film har citatet \"May the Force be with you\"?",
    options: ["Star Trek","Star Wars","Guardians","Dune"],
    correctIndex: 1,
  },
  {
    id: "fil-x3",
    category: "Film & TV",
    text: "Vad heter den blå rasen i Avatar?",
    options: ["Na'vi","Elf","Klingon","Fremen"],
    correctIndex: 0,
  },
  {
    id: "fil-x4",
    category: "Film & TV",
    text: "Vilken studio gjorde Toy Story?",
    options: ["DreamWorks","Pixar","Illumination","Sony"],
    correctIndex: 1,
  },
  {
    id: "fil-x5",
    category: "Film & TV",
    text: "Vem regisserade Inception?",
    options: ["Spielberg","Nolan","Tarantino","Fincher"],
    correctIndex: 1,
  },
  {
    id: "fil-x6",
    category: "Film & TV",
    text: "I vilken film finns karaktären Elsa?",
    options: ["Moana","Frozen","Tangled","Brave"],
    correctIndex: 1,
  },
  {
    id: "fil-x7",
    category: "Film & TV",
    text: "Vilken serie handlar om Walter White?",
    options: ["The Sopranos","Breaking Bad","Narcos","Ozark"],
    correctIndex: 1,
  },
  {
    id: "fil-x8",
    category: "Film & TV",
    text: "Vad heter Batmans verkliga namn?",
    options: ["Clark Kent","Bruce Wayne","Peter Parker","Tony Stark"],
    correctIndex: 1,
  },
  {
    id: "fil-x9",
    category: "Film & TV",
    text: "Vilken film vann Oscarsrekord med 11 Oscars (Titanic delade)?",
    options: ["Ben-Hur","Titanic","LOTR","La La Land"],
    correctIndex: 0,
  },
  {
    id: "fil-x10",
    category: "Film & TV",
    text: "Vem spelar Deadpool i filmerna?",
    options: ["Chris Pratt","Ryan Reynolds","Hugh Jackman","Tom Hardy"],
    correctIndex: 1,
  },
  {
    id: "fil-x11",
    category: "Film & TV",
    text: "Vilken Netflix-serie utspelar sig i Hawkins?",
    options: ["Dark","Stranger Things","The Umbrella Academy","Wednesday"],
    correctIndex: 1,
  },
  {
    id: "fil-x12",
    category: "Film & TV",
    text: "Vad heter den första James Bond-filmen?",
    options: ["Goldfinger","Dr. No","Skyfall","Casino Royale"],
    correctIndex: 1,
  },
  {
    id: "fil-x13",
    category: "Film & TV",
    text: "Vilken film innehåller \"Hakuna Matata\"?",
    options: ["Aladdin","Lejonkungen","Tarzan","Jungle Book"],
    correctIndex: 1,
  },
  {
    id: "fil-x14",
    category: "Film & TV",
    text: "Vem regisserade Pulp Fiction?",
    options: ["Scorsese","Tarantino","Coppola","Stone"],
    correctIndex: 1,
  },
  {
    id: "fil-x15",
    category: "Film & TV",
    text: "Vilken skådespelare spelar Thor?",
    options: ["Chris Evans","Chris Hemsworth","Chris Pratt","Chris Pine"],
    correctIndex: 1,
  },
  {
    id: "mus-x1",
    category: "Musik",
    text: "Vilket instrument har 88 tangenter?",
    options: ["Orgel","Piano","Dragspel","Cembalo"],
    correctIndex: 1,
  },
  {
    id: "mus-x2",
    category: "Musik",
    text: "Vad heter Adele med efternamn?",
    options: ["Smith","Adkins","Johnson","Brown"],
    correctIndex: 1,
  },
  {
    id: "mus-x3",
    category: "Musik",
    text: "Vilket band sjöng \"Wonderwall\"?",
    options: ["Blur","Oasis","Radiohead","Coldplay"],
    correctIndex: 1,
  },
  {
    id: "mus-x4",
    category: "Musik",
    text: "Hur många strängar har en violin?",
    options: ["3","4","5","6"],
    correctIndex: 1,
  },
  {
    id: "mus-x5",
    category: "Musik",
    text: "Vilken artist är känd som \"Material Girl\"?",
    options: ["Cher","Madonna","Beyoncé","Lady Gaga"],
    correctIndex: 1,
  },
  {
    id: "mus-x6",
    category: "Musik",
    text: "Vad heter ABBA-medlemmen Agnethas efternamn?",
    options: ["Ulvaeus","Fältskog","Andersson","Lyngstad"],
    correctIndex: 1,
  },
  {
    id: "mus-x7",
    category: "Musik",
    text: "Vilket år dog Elvis Presley?",
    options: ["1975","1977","1980","1982"],
    correctIndex: 1,
  },
  {
    id: "mus-x8",
    category: "Musik",
    text: "Vad kallas den högsta mansrösten?",
    options: ["Bas","Baryton","Tenor","Alt"],
    correctIndex: 2,
  },
  {
    id: "mus-x9",
    category: "Musik",
    text: "Vilket band gjorde \"Stairway to Heaven\"?",
    options: ["Queen","Led Zeppelin","AC/DC","Pink Floyd"],
    correctIndex: 1,
  },
  {
    id: "mus-x10",
    category: "Musik",
    text: "Vilken svensk artist sjöng \"Euphoria\"?",
    options: ["Zara Larsson","Loreen","Robyn","Tove Lo"],
    correctIndex: 1,
  },
  {
    id: "mus-x11",
    category: "Musik",
    text: "Vad är BPM i musik?",
    options: ["Bas per minut","Beats per minute","Ballad per melody","Band play mode"],
    correctIndex: 1,
  },
  {
    id: "mus-x12",
    category: "Musik",
    text: "Vilket instrument är Jimi Hendrix mest känd för?",
    options: ["Trummor","Gitarr","Bas","Keyboard"],
    correctIndex: 1,
  },
  {
    id: "mus-x13",
    category: "Musik",
    text: "Vilken artist har albumet \"1989\"?",
    options: ["Ariana Grande","Taylor Swift","Billie Eilish","Dua Lipa"],
    correctIndex: 1,
  },
  {
    id: "mus-x14",
    category: "Musik",
    text: "Vad heter Beatles' hemstad?",
    options: ["London","Liverpool","Manchester","Birmingham"],
    correctIndex: 1,
  },
  {
    id: "mus-x15",
    category: "Musik",
    text: "Vilken not kommer efter G i C-durskalan?",
    options: ["A","B","H","F"],
    correctIndex: 0,
  },
  {
    id: "sci-x1",
    category: "Vetenskap",
    text: "Vad är H i det periodiska systemet?",
    options: ["Helium","Väte","Hafnium","Holmium"],
    correctIndex: 1,
  },
  {
    id: "sci-x2",
    category: "Vetenskap",
    text: "Hur många kromosomer har en människa normalt?",
    options: ["23","46","48","44"],
    correctIndex: 1,
  },
  {
    id: "sci-x3",
    category: "Vetenskap",
    text: "Vad mäter en Geigermätare?",
    options: ["Ljud","Strålning","Tryck","Temperatur"],
    correctIndex: 1,
  },
  {
    id: "sci-x4",
    category: "Vetenskap",
    text: "Vilken planet har tydligast ringar?",
    options: ["Jupiter","Saturnus","Uranus","Neptunus"],
    correctIndex: 1,
  },
  {
    id: "sci-x5",
    category: "Vetenskap",
    text: "Vad är kokpunkten för vatten vid havsnivå?",
    options: ["90°C","100°C","110°C","120°C"],
    correctIndex: 1,
  },
  {
    id: "sci-x6",
    category: "Vetenskap",
    text: "Vilket organ pumpar blod?",
    options: ["Lever","Hjärta","Njure","Lunga"],
    correctIndex: 1,
  },
  {
    id: "sci-x7",
    category: "Vetenskap",
    text: "Vad står DNA för (ungefär)?",
    options: ["Data nucleic acid","Deoxiribonukleinsyra","Dynamic nerve axon","Dual neuron array"],
    correctIndex: 1,
  },
  {
    id: "sci-x8",
    category: "Vetenskap",
    text: "Vilken kraft håller oss på jorden?",
    options: ["Magnetism","Gravitation","Friction","Centrifugal"],
    correctIndex: 1,
  },
  {
    id: "sci-x9",
    category: "Vetenskap",
    text: "Vad är Au i periodiska systemet?",
    options: ["Silver","Guld","Aluminium","Argon"],
    correctIndex: 1,
  },
  {
    id: "sci-x10",
    category: "Vetenskap",
    text: "Hur många tänder har en vuxen människa normalt?",
    options: ["28","32","36","24"],
    correctIndex: 1,
  },
  {
    id: "sci-x11",
    category: "Vetenskap",
    text: "Vad kallas djur som bara äter växter?",
    options: ["Karnivorer","Herbivorer","Omnivorer","Detritivorer"],
    correctIndex: 1,
  },
  {
    id: "sci-x12",
    category: "Vetenskap",
    text: "Vilken gas är vanligast i jordens atmosfär?",
    options: ["Syre","Kväve","Koldioxid","Argon"],
    correctIndex: 1,
  },
  {
    id: "sci-x13",
    category: "Vetenskap",
    text: "Vad är en ljusår ett mått på?",
    options: ["Tid","Avstånd","Hastighet","Energi"],
    correctIndex: 1,
  },
  {
    id: "sci-x14",
    category: "Vetenskap",
    text: "Vilket blodkärl leder blod från hjärtat?",
    options: ["Ven","Artär","Kapillär","Lymfa"],
    correctIndex: 1,
  },
  {
    id: "sci-x15",
    category: "Vetenskap",
    text: "Vad är kemiska tecknet för järn?",
    options: ["Ir","Fe","Jr","Na"],
    correctIndex: 1,
  },
  {
    id: "mat-x1",
    category: "Mat & Dryck",
    text: "Vilket land kommer paella ifrån?",
    options: ["Italien","Spanien","Portugal","Grekland"],
    correctIndex: 1,
  },
  {
    id: "mat-x2",
    category: "Mat & Dryck",
    text: "Vad är hummus gjort av främst?",
    options: ["Linser","Kikärtor","Bönor","Ärtor"],
    correctIndex: 1,
  },
  {
    id: "mat-x3",
    category: "Mat & Dryck",
    text: "Vilken ost är blåmögel?",
    options: ["Mozzarella","Gorgonzola","Halloumi","Ricotta"],
    correctIndex: 1,
  },
  {
    id: "mat-x4",
    category: "Mat & Dryck",
    text: "Vad betyder \"al dente\"?",
    options: ["Mycket mjuk","Lagom tuggig","Bränd","Kryddig"],
    correctIndex: 1,
  },
  {
    id: "mat-x5",
    category: "Mat & Dryck",
    text: "Vilket land är känt för kimchi?",
    options: ["Japan","Sydkorea","Kina","Vietnam"],
    correctIndex: 1,
  },
  {
    id: "mat-x6",
    category: "Mat & Dryck",
    text: "Vad är en croissant främst gjord av?",
    options: ["Potatis","Smördeg","Ris","Majs"],
    correctIndex: 1,
  },
  {
    id: "mat-x7",
    category: "Mat & Dryck",
    text: "Vilken frukt används i guacamole förutom lime?",
    options: ["Mango","Avokado","Päron","Banan"],
    correctIndex: 1,
  },
  {
    id: "mat-x8",
    category: "Mat & Dryck",
    text: "Vad heter den japanska rätten med rå fisk på ris?",
    options: ["Ramen","Sushi","Tempura","Udon"],
    correctIndex: 1,
  },
  {
    id: "mat-x9",
    category: "Mat & Dryck",
    text: "Vilket krydda ger curry sin gula färg ofta?",
    options: ["Paprika","Gurkmeja","Kummin","Koriander"],
    correctIndex: 1,
  },
  {
    id: "mat-x10",
    category: "Mat & Dryck",
    text: "Vad är tofu gjort av?",
    options: ["Ris","Sojabönor","Vete","Majs"],
    correctIndex: 1,
  },
  {
    id: "mat-x11",
    category: "Mat & Dryck",
    text: "Vilket land kommer falafel ifrån (Mellanöstern)?",
    options: ["Indien","Mellanöstern","Mexiko","Grekland"],
    correctIndex: 1,
  },
  {
    id: "mat-x12",
    category: "Mat & Dryck",
    text: "Vad kallas italiensk glass?",
    options: ["Sorbet","Gelato","Frozen yogurt","Custard"],
    correctIndex: 1,
  },
  {
    id: "mat-x13",
    category: "Mat & Dryck",
    text: "Vilken dryck görs av fermenterade druvor?",
    options: ["Öl","Vin","Cider","Sake"],
    correctIndex: 1,
  },
  {
    id: "mat-x14",
    category: "Mat & Dryck",
    text: "Vad är den huvudsakliga ingrediensen i bröd?",
    options: ["Socker","Mjöl","Olja","Ägg"],
    correctIndex: 1,
  },
  {
    id: "mat-x15",
    category: "Mat & Dryck",
    text: "Vilken nöt används ofta i pesto?",
    options: ["Valnöt","Pinjenöt","Mandel","Cashew"],
    correctIndex: 1,
  },
  {
    id: "tek-x1",
    category: "Teknik",
    text: "Vad står USB för?",
    options: ["Universal Serial Bus","United System Board","Ultra Speed Byte","User Storage Block"],
    correctIndex: 0,
  },
  {
    id: "tek-x2",
    category: "Teknik",
    text: "Vilket företag gör Windows?",
    options: ["Apple","Microsoft","Google","IBM"],
    correctIndex: 1,
  },
  {
    id: "tek-x3",
    category: "Teknik",
    text: "Vad är en URL?",
    options: ["En filtyp","En webbadress","Ett virus","Ett lösenord"],
    correctIndex: 1,
  },
  {
    id: "tek-x4",
    category: "Teknik",
    text: "Vilket språk används främst för webbens struktur?",
    options: ["CSS","HTML","Python","SQL"],
    correctIndex: 1,
  },
  {
    id: "tek-x5",
    category: "Teknik",
    text: "Vad är RAM i en dator?",
    options: ["Lagring","Arbetsminne","Processor","Skärm"],
    correctIndex: 1,
  },
  {
    id: "tek-x6",
    category: "Teknik",
    text: "Vilket företag äger YouTube?",
    options: ["Meta","Google","Amazon","Apple"],
    correctIndex: 1,
  },
  {
    id: "tek-x7",
    category: "Teknik",
    text: "Vad betyder AI?",
    options: ["Automatic Input","Artificiell intelligens","Advanced Internet","App Interface"],
    correctIndex: 1,
  },
  {
    id: "tek-x8",
    category: "Teknik",
    text: "Vilken konsol är PlayStation från?",
    options: ["Nintendo","Sony","Microsoft","Sega"],
    correctIndex: 1,
  },
  {
    id: "tek-x9",
    category: "Teknik",
    text: "Vad är ett pixel?",
    options: ["Ett ljud","En bildpunkt","Ett program","Ett nätverk"],
    correctIndex: 1,
  },
  {
    id: "tek-x10",
    category: "Teknik",
    text: "Vilket protokoll används för säkra webbplatser?",
    options: ["FTP","HTTP","HTTPS","SMTP"],
    correctIndex: 2,
  },
  {
    id: "tek-x11",
    category: "Teknik",
    text: "Vad är Git främst till för?",
    options: ["Design","Versionshantering","Databas","Spel"],
    correctIndex: 1,
  },
  {
    id: "tek-x12",
    category: "Teknik",
    text: "Vilket företag skapade Android?",
    options: ["Apple","Google","Samsung","Nokia"],
    correctIndex: 1,
  },
  {
    id: "tek-x13",
    category: "Teknik",
    text: "Vad är en GPU?",
    options: ["Hårddisk","Grafikprocessor","Nätverkskort","Batteri"],
    correctIndex: 1,
  },
  {
    id: "tek-x14",
    category: "Teknik",
    text: "Vad betyder \"www\" i en adress?",
    options: ["World Wide Web","Web World Wide","Wireless Web Wire","Wide Web Window"],
    correctIndex: 0,
  },
  {
    id: "tek-x15",
    category: "Teknik",
    text: "Vilket format är vanligt för bilder på webben?",
    options: ["EXE","PNG","DLL","ISO"],
    correctIndex: 1,
  },
  {
    id: "mix-x1",
    category: "Allmänt",
    text: "Hur många planeter har solsystemet (officiellt)?",
    options: ["7","8","9","10"],
    correctIndex: 1,
  },
  {
    id: "mix-x2",
    category: "Allmänt",
    text: "Vad är Sveriges nationaldag?",
    options: ["1 maj","6 juni","24 juni","13 december"],
    correctIndex: 1,
  },
  {
    id: "mix-x3",
    category: "Allmänt",
    text: "Hur många ben har en spindel?",
    options: ["6","8","10","12"],
    correctIndex: 1,
  },
  {
    id: "mix-x5",
    category: "Allmänt",
    text: "Vad heter den största planeten?",
    options: ["Saturnus","Jupiter","Neptunus","Uranus"],
    correctIndex: 1,
  },
  {
    id: "mix-x6",
    category: "Allmänt",
    text: "Hur många bokstäver har det engelska alfabetet?",
    options: ["24","26","28","29"],
    correctIndex: 1,
  },
  {
    id: "mix-x7",
    category: "Allmänt",
    text: "Vad kallas en babykänguru?",
    options: ["Killing","Joey","Cub","Pup"],
    correctIndex: 1,
  },
  {
    id: "mix-x8",
    category: "Allmänt",
    text: "Vilket djur är känt för svarta och vita ränder?",
    options: ["Giraff","Zebra","Tiger","Panda"],
    correctIndex: 1,
  },
  {
    id: "mix-x9",
    category: "Allmänt",
    text: "Hur många sekunder är en minut?",
    options: ["30","60","90","100"],
    correctIndex: 1,
  },
  {
    id: "mix-x10",
    category: "Allmänt",
    text: "Vad är huvudstaden i Italien?",
    options: ["Milano","Rom","Neapel","Florens"],
    correctIndex: 1,
  },
  {
    id: "mix-x11",
    category: "Allmänt",
    text: "Vilket språk talas i Brasilien?",
    options: ["Spanska","Portugisiska","Franska","Italienska"],
    correctIndex: 1,
  },
  {
    id: "mix-x12",
    category: "Allmänt",
    text: "Hur många hjärtan har en bläckfisk?",
    options: ["1","2","3","4"],
    correctIndex: 2,
  },
  {
    id: "mix-x13",
    category: "Allmänt",
    text: "Vad heter världens högsta berg?",
    options: ["K2","Everest","Kangchenjunga","Makalu"],
    correctIndex: 1,
  },
  {
    id: "mix-x14",
    category: "Allmänt",
    text: "Vilken månad kommer efter juni?",
    options: ["Maj","Juli","Augusti","September"],
    correctIndex: 1,
  },
  {
    id: "mix-x16",
    category: "Allmänt",
    text: "Vilket land har flest invånare i Europa (exkl. Ryssland)?",
    options: ["Frankrike","Tyskland","Storbritannien","Italien"],
    correctIndex: 1,
  },
  {
    id: "mix-x17",
    category: "Allmänt",
    text: "Vad kallas en grupp fiskar?",
    options: ["Flock","Stim","Svärm","Pack"],
    correctIndex: 1,
  },
  {
    id: "mix-x18",
    category: "Allmänt",
    text: "Hur många grader är en rät vinkel?",
    options: ["45","90","180","360"],
    correctIndex: 1,
  },
  {
    id: "mix-x19",
    category: "Allmänt",
    text: "Vad är kemiska formeln för koksalt?",
    options: ["H2O","NaCl","CO2","CaCO3"],
    correctIndex: 1,
  },
  {
    id: "mix-x20",
    category: "Allmänt",
    text: "Vilken planet är närmast jorden (oftast)?",
    options: ["Merkurius","Venus","Mars","Månen"],
    correctIndex: 1,
  },
  {
    id: "pop-x1",
    category: "Popkultur",
    text: "Vad heter Mario's bror?",
    options: ["Wario","Luigi","Toad","Yoshi"],
    correctIndex: 1,
  },
  {
    id: "pop-x2",
    category: "Popkultur",
    text: "Vilken färg är Sonic the Hedgehog?",
    options: ["Röd","Blå","Grön","Gul"],
    correctIndex: 1,
  },
  {
    id: "pop-x3",
    category: "Popkultur",
    text: "Vad heter Harry Potters skola?",
    options: ["Beauxbatons","Hogwarts","Durmstrang","Ilvermorny"],
    correctIndex: 1,
  },
  {
    id: "pop-x4",
    category: "Popkultur",
    text: "Vilken app ägs av Meta tillsammans med Instagram?",
    options: ["TikTok","WhatsApp","Snapchat","Telegram"],
    correctIndex: 1,
  },
  {
    id: "pop-x5",
    category: "Popkultur",
    text: "Vad heter Minecraft-skaparen (alias)?",
    options: ["Notch","Dream","Herobrine","Crafty"],
    correctIndex: 0,
  },
  {
    id: "pop-x6",
    category: "Popkultur",
    text: "Vilken färg är Among Us-crewmaten ofta default?",
    options: ["Blå","Röd","Grön","Gul"],
    correctIndex: 1,
  },
  {
    id: "pop-x7",
    category: "Popkultur",
    text: "Vad heter dedikerade fans till Taylor Swift?",
    options: ["Beliebers","Swifties","Directioners","Barbz"],
    correctIndex: 1,
  },
  {
    id: "pop-x8",
    category: "Popkultur",
    text: "Vilken streamingtjänst har \"The Mandalorian\"?",
    options: ["Netflix","Disney+","HBO","Prime"],
    correctIndex: 1,
  },
  {
    id: "pop-x9",
    category: "Popkultur",
    text: "Vad heter Iron Mans AI-assistent?",
    options: ["Friday","Jarvis","Alfred","Cortana"],
    correctIndex: 1,
  },
  {
    id: "pop-x10",
    category: "Popkultur",
    text: "Vilket spel har rutorna 2048?",
    options: ["Tetris","2048","Candy Crush","Sudoku"],
    correctIndex: 1,
  },
  {
    id: "pop-x11",
    category: "Popkultur",
    text: "Vad heter Pikachus tränare?",
    options: ["Misty","Ash","Brock","Gary"],
    correctIndex: 1,
  },
  {
    id: "pop-x12",
    category: "Popkultur",
    text: "Vilken filmserie har \"One Ring\"?",
    options: ["Harry Potter","Sagan om Ringen","Narnia","Star Wars"],
    correctIndex: 1,
  },
  {
    id: "pop-x13",
    category: "Popkultur",
    text: "Vad heter den stora ape i Donkey Kong?",
    options: ["Mario","Donkey Kong","Crash","Banjo"],
    correctIndex: 1,
  },
  {
    id: "pop-x14",
    category: "Popkultur",
    text: "Vilken plattform är Twitch mest känd för?",
    options: ["Musik","Live-streaming","Shopping","Nyheter"],
    correctIndex: 1,
  },
  {
    id: "pop-x15",
    category: "Popkultur",
    text: "Vad heter Batmans butler?",
    options: ["Jarvis","Alfred","Lucius","Gordon"],
    correctIndex: 1,
  },
  {
    id: "swe-x1",
    category: "Sverige",
    text: "Vad heter Sveriges största sjö?",
    options: ["Vättern","Vänern","Mälaren","Hjälmaren"],
    correctIndex: 1,
  },
  {
    id: "swe-x2",
    category: "Sverige",
    text: "I vilken stad ligger Turning Torso?",
    options: ["Stockholm","Göteborg","Malmö","Uppsala"],
    correctIndex: 2,
  },
  {
    id: "swe-x3",
    category: "Sverige",
    text: "Vad kallas Sveriges riksdagshusplats?",
    options: ["Sergels torg","Helgeandsholmen","Gamla stan","Norrmalm"],
    correctIndex: 1,
  },
  {
    id: "swe-x4",
    category: "Sverige",
    text: "Vilken svensk uppfann dynamiten?",
    options: ["Celsius","Nobel","Ericsson","Dalén"],
    correctIndex: 1,
  },
  {
    id: "swe-x5",
    category: "Sverige",
    text: "Vad heter den svenska valutan?",
    options: ["Euro","Krona","Mark","Daler"],
    correctIndex: 1,
  },
  {
    id: "swe-x6",
    category: "Sverige",
    text: "Vilken färg har en svensk postlåda traditionellt?",
    options: ["Blå","Gul","Röd","Grön"],
    correctIndex: 1,
  },
  {
    id: "swe-x7",
    category: "Sverige",
    text: "Vad firas på Lucia?",
    options: ["13 november","13 december","24 december","6 januari"],
    correctIndex: 1,
  },
  {
    id: "swe-x8",
    category: "Sverige",
    text: "Vilken svensk stad kallas \"lilla Paris\"?",
    options: ["Uppsala","Linköping","Norrköping","Gävle"],
    correctIndex: 0,
  },
  {
    id: "swe-x9",
    category: "Sverige",
    text: "Vad heter den svenska nationalsången?",
    options: ["Du gamla, du fria","Sverige","Näckens polska","Uti vår hage"],
    correctIndex: 0,
  },
  {
    id: "swe-x10",
    category: "Sverige",
    text: "Vilket land gränsar Sverige till i öster över havet?",
    options: ["Norge","Finland","Danmark","Polen"],
    correctIndex: 1,
  },
  {
    id: "swe-x11",
    category: "Sverige",
    text: "Vad är IKEA mest känt för?",
    options: ["Bilar","Möbler","Telefoner","Mat"],
    correctIndex: 1,
  },
  {
    id: "swe-x12",
    category: "Sverige",
    text: "Vilken svensk artist vann ESC 2012?",
    options: ["Loreen","Måns","Eric Saade","Helena"],
    correctIndex: 0,
  },
  {
    id: "swe-x13",
    category: "Sverige",
    text: "Vad heter den svenska polisen i folkmun-färger?",
    options: ["Blåljus","Polisen","Blågula","Kronan"],
    correctIndex: 1,
  },
  {
    id: "swe-x14",
    category: "Sverige",
    text: "I vilket landskap ligger Kiruna?",
    options: ["Västerbotten","Lappland","Norrbotten","Jämtland"],
    correctIndex: 2,
  },
  {
    id: "swe-x15",
    category: "Sverige",
    text: "Vad kallas svensk mellanöl ungefär i folkmun?",
    options: ["Lättöl","Folköl","Starköl","Pilsner"],
    correctIndex: 1,
  },
  {
    id: "nat-x1",
    category: "Natur",
    text: "Vilket djur är känt för att byta färg?",
    options: ["Panda","Kameleont","Koala","Älg"],
    correctIndex: 1,
  },
  {
    id: "nat-x2",
    category: "Natur",
    text: "Vad äter en koala främst?",
    options: ["Bambu","Eukalyptus","Gräs","Fisk"],
    correctIndex: 1,
  },
  {
    id: "nat-x3",
    category: "Natur",
    text: "Vilket djur har snabel?",
    options: ["Noshörning","Elefant","Flodhäst","Tapir"],
    correctIndex: 1,
  },
  {
    id: "nat-x4",
    category: "Natur",
    text: "Hur många ben har en insekt normalt?",
    options: ["4","6","8","10"],
    correctIndex: 1,
  },
  {
    id: "nat-x5",
    category: "Natur",
    text: "Vad kallas en honlejon?",
    options: ["Tik","Lejoninna","Hona","Drottning"],
    correctIndex: 1,
  },
  {
    id: "nat-x6",
    category: "Natur",
    text: "Vilket djur sover upp och ner?",
    options: ["Uggla","Fladdermus","Säl","Koala"],
    correctIndex: 1,
  },
  {
    id: "nat-x7",
    category: "Natur",
    text: "Vad är världens snabbaste landdjur?",
    options: ["Lejon","Gepard","Häst","Antilop"],
    correctIndex: 1,
  },
  {
    id: "nat-x8",
    category: "Natur",
    text: "Vilket djur producerar honung?",
    options: ["Geting","Bi","Humla","Fjäril"],
    correctIndex: 1,
  },
  {
    id: "nat-x9",
    category: "Natur",
    text: "Vad kallas en babyelefant?",
    options: ["Killing","Kalv","Unge","Cub"],
    correctIndex: 1,
  },
  {
    id: "nat-x10",
    category: "Natur",
    text: "Vilket havsdjur har tentakler och bläck?",
    options: ["Haj","Bläckfisk","Delfin","Val"],
    correctIndex: 1,
  },
  {
    id: "nat-x11",
    category: "Natur",
    text: "Vad är en pingvin?",
    options: ["Däggdjur","Fågel","Fisk","Amfibie"],
    correctIndex: 1,
  },
  {
    id: "nat-x12",
    category: "Natur",
    text: "Vilket djur har svartvit päls och äter bambu?",
    options: ["Zebra","Panda","Skunk","Lemur"],
    correctIndex: 1,
  },
  {
    id: "nat-x13",
    category: "Natur",
    text: "Hur andas fiskar?",
    options: ["Lungor","Gälar","Hud","Näsa"],
    correctIndex: 1,
  },
  {
    id: "nat-x14",
    category: "Natur",
    text: "Vad kallas hundens ungar?",
    options: ["Kattungar","Valpar","Killingar","Kycklingar"],
    correctIndex: 1,
  },
  {
    id: "nat-x15",
    category: "Natur",
    text: "Vilket djur är Sveriges nationaldjur?",
    options: ["Björn","Älg","Varg","Rådjur"],
    correctIndex: 1,
  },
  {
    id: "misc-x1",
    category: "Allmänt",
    text: "Vad är pi avrundat till två decimaler?",
    options: ["3,12","3,14","3,16","3,41"],
    correctIndex: 1,
  },
  {
    id: "misc-x2",
    category: "Allmänt",
    text: "Hur många sidor har en hexagon?",
    options: ["5","6","7","8"],
    correctIndex: 1,
  },
  {
    id: "misc-x4",
    category: "Allmänt",
    text: "Vilken enhet mäter man ström i?",
    options: ["Volt","Ampere","Watt","Ohm"],
    correctIndex: 1,
  },
  {
    id: "misc-x5",
    category: "Allmänt",
    text: "Vad är motsatsen till norr?",
    options: ["Öst","Syd","Väst","Zenit"],
    correctIndex: 1,
  },
  {
    id: "misc-x6",
    category: "Allmänt",
    text: "Hur många minuter är 2,5 timmar?",
    options: ["120","150","180","90"],
    correctIndex: 1,
  },
  {
    id: "misc-x7",
    category: "Allmänt",
    text: "Vad är romerska siffran X?",
    options: ["5","10","50","100"],
    correctIndex: 1,
  },
  {
    id: "misc-x8",
    category: "Allmänt",
    text: "Vilken färg har klorofyll?",
    options: ["Röd","Grön","Blå","Gul"],
    correctIndex: 1,
  },
  {
    id: "misc-x9",
    category: "Allmänt",
    text: "Vad kallas 1000 meter?",
    options: ["Hektometer","Kilometer","Mil","Megameter"],
    correctIndex: 1,
  },
  {
    id: "misc-x10",
    category: "Allmänt",
    text: "Hur många grader i en full cirkel?",
    options: ["180","270","360","400"],
    correctIndex: 2,
  },
  {
    id: "misc-x12",
    category: "Allmänt",
    text: "Vilket ämne är flytande vid rumstemperatur och metalliskt?",
    options: ["Natrium","Kvicksilver","Järn","Zink"],
    correctIndex: 1,
  },
  {
    id: "misc-x13",
    category: "Allmänt",
    text: "Vad mäter man i decibel?",
    options: ["Ljus","Ljud","Tryck","Hastighet"],
    correctIndex: 1,
  },
  {
    id: "misc-x14",
    category: "Allmänt",
    text: "Hur många kort finns i en vanlig kortlek (utan jokrar)?",
    options: ["48","52","54","56"],
    correctIndex: 1,
  },
  {
    id: "misc-x15",
    category: "Allmänt",
    text: "Vad är det högsta värdet på en tärning (standard)?",
    options: ["5","6","8","12"],
    correctIndex: 1,
  },
  {
    id: "misc-x16",
    category: "Allmänt",
    text: "Vilken riktning pekar kompassens nål mot?",
    options: ["Syd","Magnetisk norr","Öst","Väst"],
    correctIndex: 1,
  },
  {
    id: "misc-x18",
    category: "Allmänt",
    text: "Hur många bitar är en byte?",
    options: ["4","8","16","32"],
    correctIndex: 1,
  },
  {
    id: "misc-x19",
    category: "Allmänt",
    text: "Vad betyder \"foto\" i grekiskan ungefär?",
    options: ["Ljud","Ljus","Färg","Bild"],
    correctIndex: 1,
  },
  {
    id: "misc-x20",
    category: "Allmänt",
    text: "Vilket år började 2000-talet?",
    options: ["1999","2000","2001","2010"],
    correctIndex: 2,
  },
]
