import type { Question } from './types.js'

export const EN_QUESTIONS: Question[] = [
  {
    id: "en-geo-1",
    category: "Geography",
    text: "What is the capital of France?",
    options: ["Lyon","Paris","Marseille","Nice"],
    correctIndex: 1,
  },
  {
    id: "en-geo-2",
    category: "Geography",
    text: "Which ocean is the largest?",
    options: ["Atlantic","Indian","Pacific","Arctic"],
    correctIndex: 2,
  },
  {
    id: "en-geo-3",
    category: "Geography",
    text: "Which country has the most people?",
    options: ["USA","India","China","Indonesia"],
    correctIndex: 1,
  },
  {
    id: "en-geo-4",
    category: "Geography",
    text: "What is the longest river in the world?",
    options: ["Amazon","Nile","Yangtze","Mississippi"],
    correctIndex: 1,
  },
  {
    id: "en-geo-5",
    category: "Geography",
    text: "Mount Everest is in which mountain range?",
    options: ["Andes","Alps","Himalayas","Rockies"],
    correctIndex: 2,
  },
  {
    id: "en-geo-6",
    category: "Geography",
    text: "Which desert is the largest hot desert?",
    options: ["Gobi","Sahara","Kalahari","Mojave"],
    correctIndex: 1,
  },
  {
    id: "en-geo-7",
    category: "Geography",
    text: "What is the capital of Japan?",
    options: ["Osaka","Kyoto","Tokyo","Nagoya"],
    correctIndex: 2,
  },
  {
    id: "en-geo-8",
    category: "Geography",
    text: "Which country is both in Europe and Asia?",
    options: ["Spain","Turkey","Egypt","Morocco"],
    correctIndex: 1,
  },
  {
    id: "en-geo-9",
    category: "Geography",
    text: "What is the smallest continent?",
    options: ["Europe","Australia","Antarctica","South America"],
    correctIndex: 1,
  },
  {
    id: "en-geo-10",
    category: "Geography",
    text: "Which US state is an archipelago?",
    options: ["Florida","Hawaii","Alaska","California"],
    correctIndex: 1,
  },
  {
    id: "en-geo-11",
    category: "Geography",
    text: "What is the capital of Canada?",
    options: ["Toronto","Ottawa","Vancouver","Montreal"],
    correctIndex: 1,
  },
  {
    id: "en-geo-12",
    category: "Geography",
    text: "Which sea separates Europe and Africa?",
    options: ["Black Sea","Red Sea","Mediterranean","Caspian"],
    correctIndex: 2,
  },
  {
    id: "en-geo-13",
    category: "Geography",
    text: "Where is the Great Barrier Reef?",
    options: ["Brazil","Australia","Indonesia","Philippines"],
    correctIndex: 1,
  },
  {
    id: "en-geo-14",
    category: "Geography",
    text: "What is the capital of Egypt?",
    options: ["Alexandria","Cairo","Giza","Luxor"],
    correctIndex: 1,
  },
  {
    id: "en-geo-15",
    category: "Geography",
    text: "Which country is shaped like a boot?",
    options: ["Greece","Italy","Portugal","Norway"],
    correctIndex: 1,
  },
  {
    id: "en-geo-16",
    category: "Geography",
    text: "What is the capital of South Korea?",
    options: ["Busan","Seoul","Incheon","Daegu"],
    correctIndex: 1,
  },
  {
    id: "en-geo-17",
    category: "Geography",
    text: "Which river flows through Egypt?",
    options: ["Congo","Nile","Niger","Zambezi"],
    correctIndex: 1,
  },
  {
    id: "en-geo-18",
    category: "Geography",
    text: "What is the capital of Brazil?",
    options: ["Rio","São Paulo","Brasília","Salvador"],
    correctIndex: 2,
  },
  {
    id: "en-geo-19",
    category: "Geography",
    text: "Which country has the city of Marrakesh?",
    options: ["Algeria","Morocco","Tunisia","Libya"],
    correctIndex: 1,
  },
  {
    id: "en-geo-20",
    category: "Geography",
    text: "What is the highest waterfall in the world?",
    options: ["Niagara","Angel Falls","Victoria Falls","Iguazu"],
    correctIndex: 1,
  },
  {
    id: "en-his-1",
    category: "History",
    text: "In which year did WWII end in Europe?",
    options: ["1943","1945","1944","1946"],
    correctIndex: 1,
  },
  {
    id: "en-his-2",
    category: "History",
    text: "Who was the first President of the USA?",
    options: ["Jefferson","Washington","Adams","Lincoln"],
    correctIndex: 1,
  },
  {
    id: "en-his-3",
    category: "History",
    text: "The Berlin Wall fell in which year?",
    options: ["1987","1989","1991","1985"],
    correctIndex: 1,
  },
  {
    id: "en-his-4",
    category: "History",
    text: "Who discovered penicillin?",
    options: ["Pasteur","Fleming","Curie","Darwin"],
    correctIndex: 1,
  },
  {
    id: "en-his-5",
    category: "History",
    text: "Ancient pyramids of Giza are in which country?",
    options: ["Mexico","Egypt","Peru","Sudan"],
    correctIndex: 1,
  },
  {
    id: "en-his-6",
    category: "History",
    text: "Who wrote the Declaration of Independence (main author)?",
    options: ["Franklin","Jefferson","Washington","Madison"],
    correctIndex: 1,
  },
  {
    id: "en-his-7",
    category: "History",
    text: "The Renaissance began in which country?",
    options: ["France","Italy","Spain","England"],
    correctIndex: 1,
  },
  {
    id: "en-his-8",
    category: "History",
    text: "Who was known as the Maid of Orléans?",
    options: ["Marie Antoinette","Joan of Arc","Catherine","Elizabeth"],
    correctIndex: 1,
  },
  {
    id: "en-his-9",
    category: "History",
    text: "The Titanic sank in which year?",
    options: ["1910","1912","1914","1918"],
    correctIndex: 1,
  },
  {
    id: "en-his-10",
    category: "History",
    text: "Who was the first person on the Moon?",
    options: ["Aldrin","Armstrong","Collins","Gagarin"],
    correctIndex: 1,
  },
  {
    id: "en-his-11",
    category: "History",
    text: "The Roman Empire's capital was?",
    options: ["Athens","Rome","Constantinople","Carthage"],
    correctIndex: 1,
  },
  {
    id: "en-his-12",
    category: "History",
    text: "Who painted the ceiling of the Sistine Chapel?",
    options: ["Da Vinci","Michelangelo","Raphael","Donatello"],
    correctIndex: 1,
  },
  {
    id: "en-his-13",
    category: "History",
    text: "World War I began in which year?",
    options: ["1912","1914","1916","1918"],
    correctIndex: 1,
  },
  {
    id: "en-his-14",
    category: "History",
    text: "Who was Cleopatra the queen of?",
    options: ["Greece","Egypt","Rome","Persia"],
    correctIndex: 1,
  },
  {
    id: "en-his-15",
    category: "History",
    text: "The Industrial Revolution began in?",
    options: ["USA","Britain","Germany","France"],
    correctIndex: 1,
  },
  {
    id: "en-spo-1",
    category: "Sports",
    text: "How many players are on a soccer team on the field?",
    options: ["9","10","11","12"],
    correctIndex: 2,
  },
  {
    id: "en-spo-2",
    category: "Sports",
    text: "How often are the Summer Olympics held?",
    options: ["2 years","3 years","4 years","5 years"],
    correctIndex: 2,
  },
  {
    id: "en-spo-3",
    category: "Sports",
    text: "A marathon is about how many kilometers?",
    options: ["21","42","50","26"],
    correctIndex: 1,
  },
  {
    id: "en-spo-4",
    category: "Sports",
    text: "Which country invented basketball?",
    options: ["Canada","USA","UK","France"],
    correctIndex: 1,
  },
  {
    id: "en-spo-5",
    category: "Sports",
    text: "How many Grand Slam tennis tournaments are there yearly?",
    options: ["3","4","5","6"],
    correctIndex: 1,
  },
  {
    id: "en-spo-6",
    category: "Sports",
    text: "In baseball, how many strikes for an out?",
    options: ["2","3","4","5"],
    correctIndex: 1,
  },
  {
    id: "en-spo-7",
    category: "Sports",
    text: "FIFA World Cup is held every how many years?",
    options: ["2","3","4","5"],
    correctIndex: 2,
  },
  {
    id: "en-spo-8",
    category: "Sports",
    text: "What sport uses a shuttlecock?",
    options: ["Tennis","Badminton","Squash","Golf"],
    correctIndex: 1,
  },
  {
    id: "en-spo-9",
    category: "Sports",
    text: "How many periods in ice hockey?",
    options: ["2","3","4","5"],
    correctIndex: 1,
  },
  {
    id: "en-spo-10",
    category: "Sports",
    text: "Which sport is played at Wimbledon?",
    options: ["Cricket","Tennis","Golf","Rugby"],
    correctIndex: 1,
  },
  {
    id: "en-spo-11",
    category: "Sports",
    text: "A standard golf course has how many holes?",
    options: ["9","12","18","24"],
    correctIndex: 2,
  },
  {
    id: "en-spo-12",
    category: "Sports",
    text: "What color flag ends a Formula 1 race?",
    options: ["Red","Yellow","Checkered","Green"],
    correctIndex: 2,
  },
  {
    id: "en-spo-13",
    category: "Sports",
    text: "How long is an Olympic swimming pool?",
    options: ["25m","50m","100m","33m"],
    correctIndex: 1,
  },
  {
    id: "en-spo-14",
    category: "Sports",
    text: "Which country has won the most men's football World Cups?",
    options: ["Germany","Brazil","Italy","Argentina"],
    correctIndex: 1,
  },
  {
    id: "en-spo-15",
    category: "Sports",
    text: "In basketball, a free throw is worth how many points?",
    options: ["1","2","3","4"],
    correctIndex: 0,
  },
  {
    id: "en-mov-1",
    category: "Movies & TV",
    text: "Who directed Jurassic Park?",
    options: ["Cameron","Spielberg","Nolan","Scott"],
    correctIndex: 1,
  },
  {
    id: "en-mov-2",
    category: "Movies & TV",
    text: "Which movie features the quote \"I'll be back\"?",
    options: ["Predator","The Terminator","Aliens","RoboCop"],
    correctIndex: 1,
  },
  {
    id: "en-mov-3",
    category: "Movies & TV",
    text: "Wakanda is featured in which Marvel film?",
    options: ["Thor","Black Panther","Iron Man","Doctor Strange"],
    correctIndex: 1,
  },
  {
    id: "en-mov-4",
    category: "Movies & TV",
    text: "What is the name of the hobbit played by Elijah Wood?",
    options: ["Sam","Frodo","Bilbo","Merry"],
    correctIndex: 1,
  },
  {
    id: "en-mov-5",
    category: "Movies & TV",
    text: "Which streaming service made Stranger Things?",
    options: ["HBO","Netflix","Disney+","Prime"],
    correctIndex: 1,
  },
  {
    id: "en-mov-6",
    category: "Movies & TV",
    text: "Who plays Jack Sparrow?",
    options: ["Orlando Bloom","Johnny Depp","Depp","Bloom"],
    correctIndex: 1,
  },
  {
    id: "en-mov-7",
    category: "Movies & TV",
    text: "The movie Frozen is about which princess?",
    options: ["Ariel","Elsa","Belle","Moana"],
    correctIndex: 1,
  },
  {
    id: "en-mov-8",
    category: "Movies & TV",
    text: "Which actor plays Iron Man?",
    options: ["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],
    correctIndex: 1,
  },
  {
    id: "en-mov-9",
    category: "Movies & TV",
    text: "What year was the first Star Wars film released?",
    options: ["1975","1977","1980","1983"],
    correctIndex: 1,
  },
  {
    id: "en-mov-10",
    category: "Movies & TV",
    text: "Who directed Titanic (1997)?",
    options: ["Spielberg","Cameron","Zemeckis","Scott"],
    correctIndex: 1,
  },
  {
    id: "en-mov-11",
    category: "Movies & TV",
    text: "Hogwarts is from which franchise?",
    options: ["Narnia","Harry Potter","LOTR","Percy Jackson"],
    correctIndex: 1,
  },
  {
    id: "en-mov-12",
    category: "Movies & TV",
    text: "Which show is set in Westeros?",
    options: ["The Witcher","Game of Thrones","Vikings","Rome"],
    correctIndex: 1,
  },
  {
    id: "en-mov-13",
    category: "Movies & TV",
    text: "What is the toy cowboy's name in Toy Story?",
    options: ["Buzz","Woody","Rex","Hamm"],
    correctIndex: 1,
  },
  {
    id: "en-mov-14",
    category: "Movies & TV",
    text: "Who voiced Darth Vader originally?",
    options: ["Mark Hamill","James Earl Jones","Harrison Ford","Alec Guinness"],
    correctIndex: 1,
  },
  {
    id: "en-mov-15",
    category: "Movies & TV",
    text: "Which studio makes Minions movies?",
    options: ["Pixar","Illumination","DreamWorks","Disney"],
    correctIndex: 1,
  },
  {
    id: "en-mus-1",
    category: "Music",
    text: "How many strings does a standard guitar have?",
    options: ["4","5","6","7"],
    correctIndex: 2,
  },
  {
    id: "en-mus-2",
    category: "Music",
    text: "Which band sang Bohemian Rhapsody?",
    options: ["The Beatles","Queen","Led Zeppelin","Pink Floyd"],
    correctIndex: 1,
  },
  {
    id: "en-mus-3",
    category: "Music",
    text: "Who is known as the King of Pop?",
    options: ["Elvis","Michael Jackson","Prince","Madonna"],
    correctIndex: 1,
  },
  {
    id: "en-mus-4",
    category: "Music",
    text: "Which instrument has 88 keys?",
    options: ["Organ","Piano","Harp","Accordion"],
    correctIndex: 1,
  },
  {
    id: "en-mus-5",
    category: "Music",
    text: "Beatles were formed in which city?",
    options: ["London","Liverpool","Manchester","Birmingham"],
    correctIndex: 1,
  },
  {
    id: "en-mus-6",
    category: "Music",
    text: "What does DJ stand for?",
    options: ["Digital Jockey","Disc Jockey","Dance Judge","Drum Jammer"],
    correctIndex: 1,
  },
  {
    id: "en-mus-7",
    category: "Music",
    text: "Which female artist released the album 1989?",
    options: ["Adele","Taylor Swift","Beyoncé","Rihanna"],
    correctIndex: 1,
  },
  {
    id: "en-mus-8",
    category: "Music",
    text: "A typical octave has how many notes?",
    options: ["7","8","12","5"],
    correctIndex: 1,
  },
  {
    id: "en-mus-9",
    category: "Music",
    text: "Who sang Hello (2015)?",
    options: ["Rihanna","Adele","Sia","Pink"],
    correctIndex: 1,
  },
  {
    id: "en-mus-10",
    category: "Music",
    text: "Which Swedish act won Eurovision 1974?",
    options: ["Roxette","ABBA","Ace of Base","Europe"],
    correctIndex: 1,
  },
  {
    id: "en-mus-11",
    category: "Music",
    text: "What is the highest male singing voice?",
    options: ["Bass","Baritone","Tenor","Alto"],
    correctIndex: 2,
  },
  {
    id: "en-mus-12",
    category: "Music",
    text: "Which woodwind is famous in jazz?",
    options: ["Flute","Saxophone","Oboe","Clarinet"],
    correctIndex: 1,
  },
  {
    id: "en-mus-13",
    category: "Music",
    text: "BPM in music stands for?",
    options: ["Band Play Mode","Beats Per Minute","Bass Pulse Meter","Beat Pitch Mix"],
    correctIndex: 1,
  },
  {
    id: "en-mus-14",
    category: "Music",
    text: "Who is famous for the song Shape of You?",
    options: ["Shawn Mendes","Ed Sheeran","Justin Bieber","Sam Smith"],
    correctIndex: 1,
  },
  {
    id: "en-mus-15",
    category: "Music",
    text: "Which classical composer became deaf?",
    options: ["Mozart","Beethoven","Bach","Chopin"],
    correctIndex: 1,
  },
  {
    id: "en-sci-1",
    category: "Science",
    text: "What planet is known as the Red Planet?",
    options: ["Venus","Mars","Jupiter","Mercury"],
    correctIndex: 1,
  },
  {
    id: "en-sci-2",
    category: "Science",
    text: "What is H2O?",
    options: ["Salt","Water","Oxygen","Hydrogen"],
    correctIndex: 1,
  },
  {
    id: "en-sci-3",
    category: "Science",
    text: "How many bones in an adult human body (approx)?",
    options: ["156","206","256","306"],
    correctIndex: 1,
  },
  {
    id: "en-sci-4",
    category: "Science",
    text: "What gas do plants absorb for photosynthesis?",
    options: ["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"],
    correctIndex: 1,
  },
  {
    id: "en-sci-5",
    category: "Science",
    text: "What is the chemical symbol for gold?",
    options: ["Ag","Au","Go","Gd"],
    correctIndex: 1,
  },
  {
    id: "en-sci-6",
    category: "Science",
    text: "Light travels fastest through?",
    options: ["Water","Air","Vacuum","Glass"],
    correctIndex: 2,
  },
  {
    id: "en-sci-7",
    category: "Science",
    text: "What is the hardest natural substance?",
    options: ["Quartz","Diamond","Steel","Granite"],
    correctIndex: 1,
  },
  {
    id: "en-sci-8",
    category: "Science",
    text: "Earth is the which planet from the Sun?",
    options: ["2nd","3rd","4th","5th"],
    correctIndex: 1,
  },
  {
    id: "en-sci-9",
    category: "Science",
    text: "What do bees collect to make honey?",
    options: ["Pollen","Nectar","Sap","Dew"],
    correctIndex: 1,
  },
  {
    id: "en-sci-10",
    category: "Science",
    text: "What organ pumps blood?",
    options: ["Liver","Heart","Lung","Kidney"],
    correctIndex: 1,
  },
  {
    id: "en-sci-11",
    category: "Science",
    text: "What is absolute zero in Celsius (approx)?",
    options: ["0","-100","-273","-373"],
    correctIndex: 2,
  },
  {
    id: "en-sci-12",
    category: "Science",
    text: "DNA is primarily found in which part of a cell?",
    options: ["Cytoplasm","Nucleus","Membrane","Ribosome"],
    correctIndex: 1,
  },
  {
    id: "en-sci-13",
    category: "Science",
    text: "What force keeps planets in orbit?",
    options: ["Magnetism","Gravity","Friction","Electricity"],
    correctIndex: 1,
  },
  {
    id: "en-sci-14",
    category: "Science",
    text: "What is the boiling point of water at sea level?",
    options: ["90°C","100°C","110°C","120°C"],
    correctIndex: 1,
  },
  {
    id: "en-sci-15",
    category: "Science",
    text: "Which vitamin is produced from sunlight on skin?",
    options: ["A","B12","C","D"],
    correctIndex: 3,
  },
  {
    id: "en-foo-1",
    category: "Food",
    text: "Sushi originates from which country?",
    options: ["China","Japan","Korea","Thailand"],
    correctIndex: 1,
  },
  {
    id: "en-foo-2",
    category: "Food",
    text: "Guacamole's main ingredient is?",
    options: ["Tomato","Avocado","Pepper","Onion"],
    correctIndex: 1,
  },
  {
    id: "en-foo-3",
    category: "Food",
    text: "Which cheese is classic on Margherita pizza?",
    options: ["Cheddar","Mozzarella","Gouda","Feta"],
    correctIndex: 1,
  },
  {
    id: "en-foo-4",
    category: "Food",
    text: "Espresso originates from which country?",
    options: ["France","Italy","Spain","Portugal"],
    correctIndex: 1,
  },
  {
    id: "en-foo-5",
    category: "Food",
    text: "Which fruit is botanically a berry: banana?",
    options: ["No","Yes","Only plantains","Only green"],
    correctIndex: 1,
  },
  {
    id: "en-foo-6",
    category: "Food",
    text: "Tacos are traditionally from?",
    options: ["Spain","Mexico","Italy","Peru"],
    correctIndex: 1,
  },
  {
    id: "en-foo-7",
    category: "Food",
    text: "What is tofu made from?",
    options: ["Rice","Soybeans","Wheat","Corn"],
    correctIndex: 1,
  },
  {
    id: "en-foo-8",
    category: "Food",
    text: "Champagne must come from which country?",
    options: ["Italy","Spain","France","Germany"],
    correctIndex: 2,
  },
  {
    id: "en-foo-9",
    category: "Food",
    text: "Which spice is saffron from?",
    options: ["Root","Flower stigma","Bark","Seed"],
    correctIndex: 1,
  },
  {
    id: "en-foo-10",
    category: "Food",
    text: "Paella is a dish from?",
    options: ["Italy","Spain","Portugal","Greece"],
    correctIndex: 1,
  },
  {
    id: "en-foo-11",
    category: "Food",
    text: "What does al dente mean for pasta?",
    options: ["Very soft","Firm to bite","Burnt","Spicy"],
    correctIndex: 1,
  },
  {
    id: "en-foo-12",
    category: "Food",
    text: "Kimchi is associated with which country?",
    options: ["Japan","South Korea","China","Vietnam"],
    correctIndex: 1,
  },
  {
    id: "en-foo-13",
    category: "Food",
    text: "Which nut is used in classic pesto?",
    options: ["Almond","Pine nut","Walnut","Cashew"],
    correctIndex: 1,
  },
  {
    id: "en-foo-14",
    category: "Food",
    text: "Dark chocolate contains which bean?",
    options: ["Coffee","Cocoa","Vanilla","Soy"],
    correctIndex: 1,
  },
  {
    id: "en-foo-15",
    category: "Food",
    text: "Wasabi is traditionally from which country?",
    options: ["China","Japan","India","Thailand"],
    correctIndex: 1,
  },
  {
    id: "en-tec-1",
    category: "Tech",
    text: "What does CPU stand for?",
    options: ["Central Processing Unit","Computer Power Unit","Core Program Utility","Central Program Upload"],
    correctIndex: 0,
  },
  {
    id: "en-tec-2",
    category: "Tech",
    text: "Which company makes the iPhone?",
    options: ["Google","Apple","Samsung","Microsoft"],
    correctIndex: 1,
  },
  {
    id: "en-tec-3",
    category: "Tech",
    text: "What does WWW stand for?",
    options: ["World Wide Web","Web World Wide","Wide Web World","Wireless Web World"],
    correctIndex: 0,
  },
  {
    id: "en-tec-4",
    category: "Tech",
    text: "Which language runs in web browsers natively?",
    options: ["Python","JavaScript","Ruby","C++"],
    correctIndex: 1,
  },
  {
    id: "en-tec-5",
    category: "Tech",
    text: "What does USB stand for?",
    options: ["Universal Serial Bus","United System Board","Ultra Speed Byte","User Storage Block"],
    correctIndex: 0,
  },
  {
    id: "en-tec-6",
    category: "Tech",
    text: "Git is used for?",
    options: ["Design","Version control","Networking","Gaming"],
    correctIndex: 1,
  },
  {
    id: "en-tec-7",
    category: "Tech",
    text: "Which company owns YouTube?",
    options: ["Meta","Google","Amazon","Apple"],
    correctIndex: 1,
  },
  {
    id: "en-tec-8",
    category: "Tech",
    text: "RAM is a type of?",
    options: ["Storage drive","Working memory","Graphics card","Power supply"],
    correctIndex: 1,
  },
  {
    id: "en-tec-9",
    category: "Tech",
    text: "HTTPS is more secure than HTTP because of?",
    options: ["Speed","Encryption","Color","Cookies"],
    correctIndex: 1,
  },
  {
    id: "en-tec-10",
    category: "Tech",
    text: "Android is primarily developed by?",
    options: ["Apple","Google","Microsoft","IBM"],
    correctIndex: 1,
  },
  {
    id: "en-tec-11",
    category: "Tech",
    text: "A pixel is a?",
    options: ["Sound unit","Picture element","File format","Network protocol"],
    correctIndex: 1,
  },
  {
    id: "en-tec-12",
    category: "Tech",
    text: "What does AI commonly stand for?",
    options: ["Automatic Input","Artificial Intelligence","Advanced Internet","App Interface"],
    correctIndex: 1,
  },
  {
    id: "en-tec-13",
    category: "Tech",
    text: "Which console is made by Sony?",
    options: ["Xbox","PlayStation","Switch","Steam Deck"],
    correctIndex: 1,
  },
  {
    id: "en-tec-14",
    category: "Tech",
    text: "Wi-Fi is mainly used for?",
    options: ["Cooking","Wireless networking","Printing only","Cooling"],
    correctIndex: 1,
  },
  {
    id: "en-tec-15",
    category: "Tech",
    text: "PDF stands for?",
    options: ["Print Document File","Portable Document Format","Public Data Form","Page Design File"],
    correctIndex: 1,
  },
  {
    id: "en-gen-1",
    category: "General",
    text: "How many days are in a leap year?",
    options: ["364","365","366","367"],
    correctIndex: 2,
  },
  {
    id: "en-gen-2",
    category: "General",
    text: "How many continents are there?",
    options: ["5","6","7","8"],
    correctIndex: 2,
  },
  {
    id: "en-gen-4",
    category: "General",
    text: "How many degrees in a right angle?",
    options: ["45","90","180","360"],
    correctIndex: 1,
  },
  {
    id: "en-gen-5",
    category: "General",
    text: "What color do you get mixing blue and yellow?",
    options: ["Purple","Green","Orange","Brown"],
    correctIndex: 1,
  },
  {
    id: "en-gen-6",
    category: "General",
    text: "How many seconds in a minute?",
    options: ["30","60","90","100"],
    correctIndex: 1,
  },
  {
    id: "en-gen-7",
    category: "General",
    text: "What is the largest mammal?",
    options: ["Elephant","Blue whale","Giraffe","Hippo"],
    correctIndex: 1,
  },
  {
    id: "en-gen-8",
    category: "General",
    text: "How many sides does a hexagon have?",
    options: ["5","6","7","8"],
    correctIndex: 1,
  },
  {
    id: "en-gen-9",
    category: "General",
    text: "Pi is approximately?",
    options: ["2.14","3.14","4.14","1.41"],
    correctIndex: 1,
  },
  {
    id: "en-gen-10",
    category: "General",
    text: "How many cards in a standard deck (no jokers)?",
    options: ["48","52","54","56"],
    correctIndex: 1,
  },
  {
    id: "en-gen-11",
    category: "General",
    text: "What is the opposite of north?",
    options: ["East","South","West","Up"],
    correctIndex: 1,
  },
  {
    id: "en-gen-12",
    category: "General",
    text: "How many hours in two days?",
    options: ["24","36","48","60"],
    correctIndex: 2,
  },
  {
    id: "en-gen-13",
    category: "General",
    text: "A decade is how many years?",
    options: ["5","10","20","100"],
    correctIndex: 1,
  },
  {
    id: "en-gen-14",
    category: "General",
    text: "What do you call a baby dog?",
    options: ["Kitten","Puppy","Cub","Calf"],
    correctIndex: 1,
  },
  {
    id: "en-gen-15",
    category: "General",
    text: "How many wheels does a typical car have?",
    options: ["2","3","4","6"],
    correctIndex: 2,
  },
  {
    id: "en-gen-16",
    category: "General",
    text: "What is the square root of 64?",
    options: ["6","7","8","9"],
    correctIndex: 2,
  },
  {
    id: "en-gen-17",
    category: "General",
    text: "How many letters in the English alphabet?",
    options: ["24","26","28","30"],
    correctIndex: 1,
  },
  {
    id: "en-gen-18",
    category: "General",
    text: "Water freezes at what Celsius temperature?",
    options: ["-10","0","10","32"],
    correctIndex: 1,
  },
  {
    id: "en-gen-19",
    category: "General",
    text: "How many months have 31 days?",
    options: ["5","6","7","8"],
    correctIndex: 2,
  },
  {
    id: "en-pop-1",
    category: "Pop Culture",
    text: "What color is Pikachu?",
    options: ["Red","Yellow","Blue","Green"],
    correctIndex: 1,
  },
  {
    id: "en-pop-2",
    category: "Pop Culture",
    text: "Mario's brother is named?",
    options: ["Wario","Luigi","Toad","Yoshi"],
    correctIndex: 1,
  },
  {
    id: "en-pop-3",
    category: "Pop Culture",
    text: "Harry Potter's school is called?",
    options: ["Beauxbatons","Hogwarts","Durmstrang","Ilvermorny"],
    correctIndex: 1,
  },
  {
    id: "en-pop-4",
    category: "Pop Culture",
    text: "Which app is owned by Meta with Instagram?",
    options: ["TikTok","WhatsApp","Snapchat","X"],
    correctIndex: 1,
  },
  {
    id: "en-pop-5",
    category: "Pop Culture",
    text: "The One Ring is from which series?",
    options: ["Narnia","Lord of the Rings","Harry Potter","Wheel of Time"],
    correctIndex: 1,
  },
  {
    id: "en-pop-6",
    category: "Pop Culture",
    text: "Sonic the Hedgehog is what color?",
    options: ["Red","Blue","Green","Orange"],
    correctIndex: 1,
  },
  {
    id: "en-pop-7",
    category: "Pop Culture",
    text: "Batman's butler is named?",
    options: ["Jarvis","Alfred","Lucius","Gordon"],
    correctIndex: 1,
  },
  {
    id: "en-pop-8",
    category: "Pop Culture",
    text: "Minecraft was created by (alias)?",
    options: ["Notch","Dream","Herobrine","Stampy"],
    correctIndex: 0,
  },
  {
    id: "en-pop-9",
    category: "Pop Culture",
    text: "Which platform is famous for live streaming games?",
    options: ["Spotify","Twitch","Pinterest","Reddit"],
    correctIndex: 1,
  },
  {
    id: "en-pop-10",
    category: "Pop Culture",
    text: "Shrek is what color?",
    options: ["Blue","Green","Purple","Brown"],
    correctIndex: 1,
  },
  {
    id: "en-pop-11",
    category: "Pop Culture",
    text: "Iron Man's AI assistant is often called?",
    options: ["Cortana","Jarvis","Siri","Alexa"],
    correctIndex: 1,
  },
  {
    id: "en-pop-12",
    category: "Pop Culture",
    text: "Pokémon Ash's first partner is often?",
    options: ["Charmander","Pikachu","Squirtle","Bulbasaur"],
    correctIndex: 1,
  },
  {
    id: "en-pop-13",
    category: "Pop Culture",
    text: "Which social app uses short vertical videos famously?",
    options: ["LinkedIn","TikTok","Pinterest","Reddit"],
    correctIndex: 1,
  },
  {
    id: "en-pop-14",
    category: "Pop Culture",
    text: "The Force is from which franchise?",
    options: ["Star Trek","Star Wars","Dune","Stargate"],
    correctIndex: 1,
  },
  {
    id: "en-pop-15",
    category: "Pop Culture",
    text: "Who lives in a pineapple under the sea?",
    options: ["Patrick","SpongeBob","Squidward","Mr. Krabs"],
    correctIndex: 1,
  },
]
