import type { Question } from './types.js'

export const SV_MORE_QUESTIONS: Question[] = [
  {
    id: "sv-more-1",
    category: "Sverige",
    text: "Vilken svensk stad har broarna över Göta älv mest känt?",
    options: ["Malmö","Göteborg","Stockholm","Uppsala"],
    correctIndex: 1,
  },
  {
    id: "sv-more-2",
    category: "Sverige",
    text: "Vad heter Sveriges statsministertitel?",
    options: ["President","Statsminister","Kung","Talman"],
    correctIndex: 1,
  },
  {
    id: "sv-more-3",
    category: "Sverige",
    text: "Vilken färg har en svensk räddningsväst ofta?",
    options: ["Blå","Orange","Grön","Svart"],
    correctIndex: 1,
  },
  {
    id: "sv-more-4",
    category: "Sverige",
    text: "Vad kallas svensk knäckebröd på engelska ofta?",
    options: ["Soft bread","Crispbread","Toast","Bagel"],
    correctIndex: 1,
  },
  {
    id: "sv-more-5",
    category: "Sverige",
    text: "Vilken svensk bilmärkesgrundare är kopplad till Volvo?",
    options: ["Wallenberg","Gabrielsson/G. Larson","Kamprad","Rausing"],
    correctIndex: 1,
  },
  {
    id: "sv-more-6",
    category: "Sverige",
    text: "Vad firas med majbrasa ofta?",
    options: ["Lucia","Valborg","Midsommar","Nyår"],
    correctIndex: 1,
  },
  {
    id: "sv-more-7",
    category: "Sverige",
    text: "Vilken svensk ö har Visby?",
    options: ["Öland","Gotland","Tjörn","Orust"],
    correctIndex: 1,
  },
  {
    id: "sv-more-8",
    category: "Sverige",
    text: "Vad heter den svenska lagboken i folkmun-ish?",
    options: ["SFS","Lagboken","Civilrätten","Balken"],
    correctIndex: 1,
  },
  {
    id: "sv-more-9",
    category: "Sverige",
    text: "Vilken sport är Vasaloppet?",
    options: ["Skidåkning","Löpning","Cykling","Simning"],
    correctIndex: 0,
  },
  {
    id: "sv-more-10",
    category: "Sverige",
    text: "Vad kallas Sveriges högsta berg?",
    options: ["Kebnekaise","Sarektjåkkå","Storlien","Åreskutan"],
    correctIndex: 0,
  },
  {
    id: "sv-more-11",
    category: "Sverige",
    text: "Vilken dryck är lingondricka gjord på?",
    options: ["Blåbär","Lingon","Hallon","Jordgubbar"],
    correctIndex: 1,
  },
  {
    id: "sv-more-12",
    category: "Sverige",
    text: "Vad heter den svenska nobelprisutdelningen i december i?",
    options: ["Göteborg","Stockholm","Oslo","Uppsala"],
    correctIndex: 1,
  },
  {
    id: "sv-more-13",
    category: "Sverige",
    text: "Vilken svensk författare skrev Pippi Långstrump?",
    options: ["Maria Gripe","Astrid Lindgren","Selma Lagerlöf","Karin Boye"],
    correctIndex: 1,
  },
  {
    id: "sv-more-14",
    category: "Sverige",
    text: "Vad är en \"loppis\"?",
    options: ["Konsert","Loppmarknad","Bilkö","Skola"],
    correctIndex: 1,
  },
  {
    id: "sv-more-15",
    category: "Sverige",
    text: "Vilken månad är midsommar oftast?",
    options: ["Maj","Juni","Juli","Augusti"],
    correctIndex: 1,
  },
  {
    id: "sv-more-16",
    category: "Sverige",
    text: "Vad heter den svenska älgjaktens säsong ungefär?",
    options: ["Vår","Höst","Vinter","Sommar"],
    correctIndex: 1,
  },
  {
    id: "sv-more-17",
    category: "Sverige",
    text: "Vilken svensk kedja säljer köttbullar i varuhus världen över?",
    options: ["H&M","IKEA","Lindex","Åhléns"],
    correctIndex: 1,
  },
  {
    id: "sv-more-18",
    category: "Sverige",
    text: "Vad kallas den svenska skolavslutningen i juni ofta?",
    options: ["Lucia","Studenten","Valborg","Kräftskiva"],
    correctIndex: 1,
  },
  {
    id: "sv-more-19",
    category: "Sverige",
    text: "Vilken fisk är vanlig i sillbuffé?",
    options: ["Torsk","Sill","Lax","Makrill"],
    correctIndex: 1,
  },
  {
    id: "sv-more-20",
    category: "Sverige",
    text: "Vad heter den svenska flaggstångens toppprydnad ofta?",
    options: ["Kula","Spira","Krona","Stjärna"],
    correctIndex: 0,
  },
  {
    id: "sv-more-21",
    category: "Sverige",
    text: "Vilken svensk stad är känd för kanelbullar-fikatypiskt studentliv?",
    options: ["Kiruna","Uppsala","Kiruna","Visby"],
    correctIndex: 1,
  },
  {
    id: "sv-more-22",
    category: "Sverige",
    text: "Vad är en \"fika\"?",
    options: ["Middag","Kaffepaus med tilltugg","Frukost","Träning"],
    correctIndex: 1,
  },
  {
    id: "sv-more-23",
    category: "Sverige",
    text: "Vilken färg har en svensk nödutgångsskylt ofta?",
    options: ["Röd","Grön","Blå","Gul"],
    correctIndex: 1,
  },
  {
    id: "sv-more-24",
    category: "Sverige",
    text: "Vad heter den svenska myntenheten i mindre?",
    options: ["Mark","Öre","Penny","Cent"],
    correctIndex: 1,
  },
  {
    id: "sv-more-25",
    category: "Sverige",
    text: "Vilken svensk popduo är Roxette?",
    options: ["ABBA","Marie Fredriksson & Per Gessle","Ace of Base","Cardigans"],
    correctIndex: 1,
  },
  {
    id: "sv-more-26",
    category: "Sverige",
    text: "Vad kallas Sveriges västkustskärgård mest känt kring?",
    options: ["Stockholm","Göteborg","Luleå","Kalmar"],
    correctIndex: 1,
  },
  {
    id: "sv-more-27",
    category: "Sverige",
    text: "Vilken svensk sport är bandy mest lik?",
    options: ["Fotboll","Ishockey/fotbollshybrid","Tennis","Golf"],
    correctIndex: 1,
  },
  {
    id: "sv-more-28",
    category: "Sverige",
    text: "Vad är Surströmming?",
    options: ["Ost","Fermenterad sill","Korv","Bröd"],
    correctIndex: 1,
  },
  {
    id: "sv-more-29",
    category: "Sverige",
    text: "Vilken svensk nationalpark är Sarek i?",
    options: ["Skåne","Lappland","Småland","Bohuslän"],
    correctIndex: 1,
  },
  {
    id: "sv-more-30",
    category: "Sverige",
    text: "Vad heter den svenska kungafamiljens efternamn?",
    options: ["Bernadotte","Vasa","Folkunga","Holstein"],
    correctIndex: 0,
  },
]
